### ISSUE TITLE
Enable Esri Data Format

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#10]
Es wäre gut, wenn die Daten in diesem Format (gleich wie Italien und China) aufbereitet werden:

Pro Tag eine Zeile für alle Kantone
https://github.com/zdavatz/covid19_ch/blob/master/data-cantons-csv/dd-covid19-ch-cantons-20200318-example.csv

Pro Tag eine Zeile für die ganze Schweiz.
https://github.com/zdavatz/covid19_ch/blob/master/data-switzerland-csv/dd-covid19-ch-switzerland-20200318-example.csv

Dann kann man die Daten direkt ins Esri reinziehen. Siehe z.B. [Italien](http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1), [JohnHopkins](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

**Comment by zdavatz** [comment]
Wir pflegen jetzt die Höhen und Breitengrade ein.

**Comment by tlorusso** [comment]
Thanks for all your valuable inputs @zdavatz!

The italian standard is great! However at the moment we are still far away from having all this information (currently positive etc.), the current format of the files aims at collecting the essential information as it is available for the Cantons and make data collection easy. As soon as we are ready to merge, we can create one single national file that can be transformed easily in what you need (at least for the figures that are comparable). We sure can add Canton ods etc then.

**Comment by zdavatz** [comment]
Sure, take your time. We are working on it as well, see: https://github.com/zdavatz/covid19_ch#data-per-canton

**Comment by zdavatz** [comment]
The goal is to grab your data, build the Italian format and while doing so create a report file, that shows which of your files are incomplete or not up to date and then load everything into our Map at: http://covid19.ddrobotec.com/

See: https://github.com/zdavatz/covid19_ch/issues/11
