### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ebeusch** [openZH/covid_19#102]
Currently the readme doesn't reflect that most canton's are scraped by @baryluk 's army of scrapers.

**Comment by tlorusso** [comment]
@metaodi is setting the scrapers up. So far just SG is productive, further will follow. We'll update the Readme shortly.

**Comment by metaodi** [comment]
@ebeusch this is correct, the "army of scrapers" is not yet deployed. I'll update the README when it's done.
Let's keep this issue open as a reminder.

**Comment by baryluk** [comment]
@metaodi Amazing work. Hope to see it working soon :)

**Comment by metaodi** [comment]
see #124 😉

**Comment by metaodi** [comment]
The README is now up-to-date in terms of which cantons are scraped and which are updated manually. To check the status of each scraper, take a look at the [STATUS](https://github.com/openZH/covid_19/blob/master/scrapers/STATUS.md) page, where a green badge is displayed if the scraper was successful (or red respectively if not successful)

**Comment by zdavatz** [comment]
great page, thank you!
