### ISSUE TITLE
New file for number of tests per day for Basel-Stadt

### ISSUE THREAD

**Issue by jb3-2** [openZH/covid_19#1026]
We publish weekly numbers of tests (total, negative, positive) for people living in Basel-Stadt: https://data.bs.ch/explore/dataset/100094 - @metaodi Can you please scrape those and add a new CSV file to the repo? Thanks!

**Comment by metaodi** [comment]
We will define a structure for this data and then start to integrate your data in this repo.

**Comment by andreasamsler** [comment]
@jb3-2 to get it right: BS is publishing once per week the daily numbers of tests (total, negative, positive), correct?

**Comment by jb3-2** [comment]
@andreasamsler Correct! We get the data each Friday and put them online Friday afternoon.

**Comment by metaodi** [comment]
It's finally done: #1342

The file is here: https://github.com/openZH/covid_19/blob/master/fallzahlen_tests/fallzahlen_kanton_BS_tests.csv
