### ISSUE TITLE
Y axis is off in "Daily Percentage of Positive Tests"

### ISSUE THREAD

**Issue by toupeira** [openZH/covid_19#1036]
I noticed that the Y axis of the ["Daily Percentage of Positive Tests" chart](https://www.corona-data.ch/#tests-ratio-graph) is showing values in the range of 0.0 - 1.0, but should be using 0 - 100 like the next graph "Daily Percentage of Positive Tests and Daily Tests per 10'000 (Last 7 Days)" below.

**Comment by metaodi** [comment]
@daenuprobst I guess this feedback is for you.

I'm closing the issue here, since it doesn't belong here. corona-data.ch uses the data of this repository, but it's a separate project.

**Comment by toupeira** [comment]
@metaodi thanks! I didn't see any other way to contact you on the website, and I don't have a Twitter account :wink:
