### ISSUE TITLE
Scraper for GL

### ISSUE THREAD

**Issue by ebeusch** [openZH/covid_19#107]
Glarus is finally publishing [numbers](https://www.gl.ch/verwaltung/finanzen-und-gesundheit/gesundheit/coronavirus.html/4817#Fallzahlen)
@baryluk or others: can you write a scraper?

**Comment by baryluk** [comment]
Ok. On it now. Give me few minutes.

**Comment by baryluk** [comment]
GL is implemented, and part of https://github.com/openZH/covid_19/pull/108

**Comment by zdavatz** [comment]
Great work!
