### ISSUE TITLE
AG seems to deliver more data again (adjust scrapers...)

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1078]
AG delivers again hospitalisations... see here:
https://www.ag.ch/de/themen_1/coronavirus_2/lagebulletins/lagebulletins_1.jsp?sectionId=1862071&accordId=0

**Comment by rsalzer** [comment]
I added a pull request for the historical data: https://github.com/openZH/covid_19/pull/1082

**Comment by metaodi** [comment]
Since AG now even provides a XLSX file, I again rewrote the scraper to parse this XLSX: https://github.com/openZH/covid_19/pull/1084
