### ISSUE TITLE
Smaller repo?

### ISSUE THREAD

**Issue by tdegeus** [openZH/covid_19#1079]
The current repository is 1gb. It would be nice to have an option to clone a lot less.

**Comment by metaodi** [comment]
You can create a `shallow` clone of this repository using the [`depth` parameter of `git clone`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt)

example to only get the last 5 revisions:

```
git clone --depth=5 https://github.com/openZH/covid_19.git
```

This should reduce the size drastically if you don't need the history.

**Comment by tdegeus** [comment]
Awesome ! Thanks !
