### ISSUE TITLE
Strange drop of current_hosp in GE

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1093]
There seems to be a strange drop in current hospitalisations in GE in may. Is this really accurate?
https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_GE_total.csv

See here (last row on the screenshot):
<img width="671" alt="image" src="https://user-images.githubusercontent.com/17248257/94870574-216ed480-0448-11eb-8562-5cb6803512dd.png">

**Comment by metaodi** [comment]
Thanks for this issue. In the most current XLSX of GE the values for `current_hosp` start on 2020-05-19 and there are no values prior to that. So it seems we have some historic data that is no longer valid. I think we should follow the publication of GE and remove all `current_hosp` values prior to 2020-05-19.
