### ISSUE TITLE
SZ: xlsx file disappeared

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#1099]
https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948 doesn't link to Excel file any more but shows very basic:
Corona Fallzahlen (Stand: 5. Oktober 2020): 642 bestätigte Fälle, 25 Verstorbene, 538 Genesene

**Comment by metaodi** [comment]
I disabled SZ for the moment.

**Comment by metaodi** [comment]
It's back 😄
