### ISSUE TITLE
Create snapshots via web.archive.org

### ISSUE THREAD

**Issue by retomerz** [openZH/covid_19#111]
First, thanks for you work.

Scrapers should create a snapshot [1] from the source homepage.
This should be done, at least, once a day.
Even when the source is not changed.
Because this will also document that a source (canton/BAG) has *not* published new data.

[1] https://archive.readme.io/docs/creating-a-snapshot

**Comment by baryluk** [comment]
That is a good idea. I think it is important to preserve the original source page verbatim for reference, and as you said to document also lack of updates.

**Comment by zdavatz** [comment]
Ok, just do not change any links for filenames here https://www.functor.xyz/covid_19/scrapers/outputs/?M=r without prior warning and time.

**Comment by baryluk** [comment]
@zdavatz No, all these filenames will valid forever. I do not plan deleting or renaming them.

But I want to also save original source of each website it is scraping from. I will add a separate subdirectory for this.

**Comment by zdavatz** [comment]
great, like this if a canton changes their website we know when and what changed. So we could/can always call them up and ask about the changes. 👍👏🇨🇭🤣👌

**Comment by retomerz** [comment]
The thing with a snapshot on web.archive.org is:
It is a well-known, trusted immutable archive.
Even for government it would not be easy to manipulate or to shut down archive.org

(Of course it makes also sense that you also store the page on the scraper server)

**Comment by baryluk** [comment]
Good point. We should have both. I will try to trigger web.archive.org snapshot using this API from my scripts running on my server.

Thanks for pointing this out.

**Comment by baryluk** [comment]
#122 should make it very easy to do. Should be ready very soon.

**Comment by baryluk** [comment]
@retomerz Good news. I managed to use the API with success automatically from our scripts. Soon all data we scrape for all cantons will be asked to be snapshoted every hour or so. We could be smart in the future, to only scrape if there are changes, but as you said, it is also good to have information about lack of changes.

**Comment by tlorusso** [comment]
@retomerz @baryluk Thank you guys for bringing this up and trying to find a solution. To perserve snapshots of the scraped pages would reeally help us to ensure every number can be traced back transparently to where it was published. This would be an important signal when it comes to raise the trust in the quality of the collected data.

**Comment by baryluk** [comment]
Sorry, I forgot about it, and was lost in my other commits. PR open now to implement it for all scrapers.
