### ISSUE TITLE
Use different source for JU-scraper

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1118]
The JU-scraper seems to be deactivated.
The source now is an xls as I see but without up-to-date information (last update 2020-09-30).

The same information (last update yesterday...) can also be found on this site:
https://www.jura.ch/fr/Autorites/Coronavirus/Chiffres-H-JU/Evolution-des-cas-COVID-19-dans-le-Jura.html

**Comment by rsalzer** [comment]
Added the missing numbers for now ... https://github.com/openZH/covid_19/pull/1119

**Comment by metaodi** [comment]
Jura used to have an xls download on that page, but it's gone since yesterday, that's why the scraper is currently deactivated. We didn't yet get any feedback from them, but good to know that they put the numbers on the website. I will adapt the scraper accordingly.

**Comment by rsalzer** [comment]
I can not guarantee if they will publish persistently on the new site ... but probably no one can for any scraper ;-)

**Comment by simgraworldwide** [comment]
I was told by JU that they are going to upload the xls again and update it weekly but it seems that the table accessible via the abovementioned URL is updated daily so I too suggest to adapt the scraper to the new source.
