### ISSUE TITLE
Scraper for OW, AR, SO, and ZG

### ISSUE THREAD

**Issue by ebeusch** [openZH/covid_19#112]
@baryluk once more more work for you:
https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962
Obwalden now publishes numbers under "Anzahl Infizierte"

**Comment by ebeusch** [comment]
Also, AR
https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/
at the very bottom of the site.

I'm basically going through the list from your server, and checking outstanding ones. (And assuming AI doesn't work well for parsing)

**Comment by zdavatz** [comment]
Great work @ebeusch thank you!

**Comment by ebeusch** [comment]
Now, SO is also online
https://corona.so.ch/

**Comment by baryluk** [comment]
Perfect. On it.

**Comment by ebeusch** [comment]
And last: ZG
https://www.zg.ch/behoerden/gesundheitsdirektion/amt-fuer-gesundheit/corona

FR is the only one missing afaict. Will try to contact them like SZ.

**Comment by baryluk** [comment]
All implemented, will add a pull request in few minutes.

**Comment by zdavatz** [comment]
@baryluk supercool! Monitoring all cantons and their publicdomain data with your scrapers is the right thing to do. If something changes, we can document it with Issues and Commits.
