### ISSUE TITLE
VD Case numbers do not line up with website

### ISSUE THREAD

**Issue by duerrsimon** [openZH/covid_19#1141]
Case numbers for Vaud do not line up with website of Vaud. 

E.g in this dataset between 6.10 (11144 cases) 7.10 (11280 cases) 136 new cases where reported
However, on their website this number cannot be found
![image](https://user-images.githubusercontent.com/16979577/95581212-e74d9600-0a38-11eb-9996-2246c19d13a3.png)

Do they count differently?

**Comment by simgraworldwide** [comment]
I have contacted VD concerning the discrepancies between their data and their plots and am waiting for their response. However, the data relevant to us is what VD provides via https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/ and in an excel-spreadsheet via https://www.vd.ch/fileadmin/user_upload/accueil/coronavirus/stats12octobre/G12_HOP_POST_EPID_OMC_HOSP_SI_TA_v2.xlsx.

**Comment by simgraworldwide** [comment]
According to VD there might be differences between the tables and the plots. This is due to due to differently timed updates of the two types of data.
