### ISSUE TITLE
Fix UR scraper

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#115]
It just broken, because website changed format a bit.

It is now in form of a table. Should be easy to fix.

On it.

**Comment by zdavatz** [comment]
Thank you!

**Comment by zdavatz** [comment]
@baryluk If we can somehow build a twitter-bot or something, that posts to twitter when a canton changes its website format (your parser fails), that would be great! Like this we all can be notified and we can also monitor the Cantonal Public Domain data ;), as we rely on the that information for our public safety.
