### ISSUE TITLE
FR: adjust printed source

### ISSUE THREAD

**Issue by simgraworldwide** [openZH/covid_19#1165]
Currently, we print https://www.fr.ch/sites/default/files/2020-10/201013_statistiques_situation_COVID_site_V2.xlsx as the source for the FR data despite there only being case number data for the districts (no hospitalisations etc.).
We should change the printed source to https://www.fr.ch/de/gesundheit/covid-19/coronavirus-statistik-ueber-die-entwicklung-im-kanton.

**Comment by metaodi** [comment]
I think the source is correct. FR publishes one excel file for the districts and the canton as a whole. It contains all data that we have of FR (including hospitalisation, deceased etc.)
