### ISSUE TITLE
Scraper for NW does not update

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#118]
I see here https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt that NW should have 39 for the 23.03.2020 cases, but here https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_NW_total.csv I still see the 23.03.2020 missing. Maybe this is just a case of [FIX] fix all scrapers #103 ?

**Comment by baryluk** [comment]
The output from scrappers is not automatically integrated into csv files yes. We are working on it. In the mean time, we need to be still updating csv files manually. Scrapers help a bit in that tho.

**Comment by zukunft** [comment]
OK. Thanks for the Info and all the scrapers.

**Comment by metaodi** [comment]
I'm currently working on the integration of all the scrapers incl. automatically updating the CSVs on GitHub.

**Comment by jb3-2** [comment]
@metaodi You‘re a hero.

**Comment by metaodi** [comment]
Fixed in #124

**Comment by metaodi** [comment]
NW is now automatically updated.
