### ISSUE TITLE
BL district scraper new confirmed values are wrong

### ISSUE THREAD

**Issue by maekke** [openZH/covid_19#1185]
It looks like the scraped values are quite off. Dividing the values by 14 days (what is claimed on the chart) seems to give reasonable range of the values, but still not really correct.
Anyone got an idea on how to improve this?

**Comment by metaodi** [comment]
Maybe @CorinneHuegli can help?

**Comment by CorinneHuegli** [comment]
@maekke the values in column "newConfCases" are the cumulative new cases within the previous 14 days. Please delete for now. It won't work from that chart. I will check tomorrow if we can provide another chart with the daily numbers per district (cumulative and new). Ok?

**Comment by metaodi** [comment]
BL district scraper is disabled now.

And I removed the data in #1191

**Comment by CorinneHuegli** [comment]
Please reactivate BL district scraper. 
The data was added manually today (cases until yesterday). For values from today on please scrape from new iframe: https://cocontrol.bl.ch/public/dbw/123 here https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/covid-19-faelle-kanton-basel-landschaft
The new chart is starting in June. So for new values starting from 2020-10-16 please add +528 for District 1301, +65 for District 1302, +177 for District 1303, +81 for District 1304 and +15 for District 1305.
Hope that works out.

**Comment by maekke** [comment]
@CorinneHuegli cool, thanks a lot, I've updated the scraper with your information! The csv output is identical, so I hope everything is fine :sweat_smile:

**Comment by CorinneHuegli** [comment]
Thank you 😀
