### ISSUE TITLE
AG: scrap weekly district data 

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1193]
Canton AG publishes total numbers by district: https://www.ag.ch/de/themen_1/coronavirus_2/lagebulletins/lagebulletins_1.jsp

The data is in a jpg, which gives quite good result using tesseract as OCR.

I currently download a daily copy of the jpeg to make further analysis, see example: 
[ag_snapshots.tar.gz](https://github.com/openZH/covid_19/files/5391596/ag_snapshots.tar.gz)

Problems
a) the publication rythm is not clear. Usually it was Friday, but for example this week they changed the numbers on Wednesday.
b) there is no date information in the picture, only in the subtext.
e.g. "Kanton Aargau – Inzidenz pro 100'000 Einwohner nach Bezirken seit Start Contact Tracing Center (Conti) 11. Mai 2020 (Stand: 13.10.2020, 08:20 Uhr)"

**Comment by metaodi** [comment]
@balzamas I implemented this scraper as suggested by you. Thank you! Let's see how stable it works over time.

**Comment by balzamas** [comment]
Thank you @metaodi !
Here are all the files I fetched, timestamp in the file name:

[ag_fetch.tar.gz](https://github.com/openZH/covid_19/files/5440727/ag_fetch.tar.gz)
