### ISSUE TITLE
GE, SZ, VG failed

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#120]
@baryluk 

I ran it again, now I get:
```
GE - - - FAILED
SZ - - - FAILED
VD - - - FAILED
```
Can you add a verbose option, to show where it fails? Does that make sense?

**Comment by baryluk** [comment]
VD does work. You can see it working here: https://www.functor.xyz/covid_19/scrapers/outputs/2020-03-23T21%3A05%2B01%3A00.txt for example  Some sites like to block sometimes IP addresses.

SZ doesn't work , and can't be fixed sorry.

GE just got broken, due to change in PDF format from GE. I am working on it.

Thx.


Verbose option to print more details makes sense. I already started working on it some time ago to log details.

**Comment by zdavatz** [comment]
@baryluk ok, thank you Sir! 🚀🦠🚨- I will keep testing.

**Comment by zukunft** [comment]
... and SZ and FR have very old data. I have requested an update via email, but no reaction until now. Does someone have contacts that we can use?

**Comment by baryluk** [comment]
GE got fixed in d7a172fa707528ddc3448b50f2dcd6cd31a667de

**Comment by ebeusch** [comment]
@zukunft I'm on both SZ and FR.
FR told me they will put numbers online starting from today (see #129)
I wrote to KFS regarding numbers for SZ and they told me that my request has been forwarded to  "Amt für Gesundheit und Soziales", so let's see if they will answer.

**Comment by zukunft** [comment]
Thanks for the support. I got the same answer from SZ. I think, GE is a good reference. Looks like they have an efficient setup.

**Comment by zdavatz** [comment]
Little update about different sources: https://www.watson.ch/schweiz/gesundheit/220460287-warum-die-zahlen-zum-coronavirus-in-der-schweiz-so-unterschiedlich-sind

**Comment by baryluk** [comment]
@zdavatz Please don't put different cantons issues into same issue on github. it really makes things way more harder to track. Same with https://github.com/openZH/covid_19/issues/132

**Comment by zdavatz** [comment]
Ok!

**Comment by ebeusch** [comment]
@zdavatz can you close this issue? SZ has it's own now (incl. data link) and so does FR (not very succesful so far) so I think this is all taken care of.

**Comment by zdavatz** [comment]
Ok, closing now, thank you!
