### ISSUE TITLE
OW deaths from today seems new instead of cumulated

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1231]
The newest data from canton OW seems to include new deaths instead of the cumulated:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/17248257/96904015-dbc98880-1496-11eb-8acc-5382602f2722.png">

See from their website:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/17248257/96904209-13383500-1497-11eb-82dd-7ccbb9ab7003.png">

https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962

**Comment by metaodi** [comment]
Yes, our [CSV validation got the same error](https://github.com/openZH/covid_19/runs/1293777374?check_suite_focus=true). We'll contact OW to fix their source. In the meantime the scraper is disabled and the value in the CSV was fixed.

**Comment by metaodi** [comment]
OW fixed their source and the scraper is running again.
