### ISSUE TITLE
SZ district data seems to contain positive cases

### ISSUE THREAD

**Issue by maekke** [openZH/covid_19#1246]
The SZ scraped district data seems to contain the "positive Fälle" values, which seem to be the number of isolated cases according to the ["Medienmitteilung"](https://www.sz.ch/public/upload/assets/49281/MM_Coronavirus_22_10_2020.pdf).
The data is also not 100% consistent, for example the sum of the district values on 2020-10-22 is 1024, but the pdf lists 1025.

Not sure if this scraper is useful at all?

Plus the second question would be to add the "positive Fälle" as isolated to the (normal) SZ scraper?

**Comment by metaodi** [comment]
I would add it to the standard SZ scraper as `current_isolated`.
About consitency: sometimes the residence of a person is unknown/unclear, so it's possible to end up with more cases on a cantonal level.

**Comment by maekke** [comment]
> I would add it to the standard SZ scraper as `current_isolated`.
Okay done in #1259 

> About consitency: sometimes the residence of a person is unknown/unclear, so it's possible to end up with more cases on a cantonal level.
I agree with the consistency here. But I still think that the `TotalConfCases` in the SZ district data are actually more "current cases" than the total...
But I could be wrong :man_shrugging:

**Comment by metaodi** [comment]
@maekke can we close this issue, since #1259 is merged or is there still something open regarding district data vs. cantonal data?

**Comment by maekke** [comment]
Let's close it!
