### ISSUE TITLE
Add world data (e.g. italy, south-corea) in same format for comparison

### ISSUE THREAD

**Issue by netzwerg** [openZH/covid_19#125]
When visualizing data, it would be great to be able to compare CH-data with trajectories of other countries, most notably Italy and South-Corea.

Specifically, we'd like to develop "small multiples", [displaying each CH-canton](https://twitter.com/luescher_sandro/status/1242137542297825286?s=20).

Visualization could be along the lines of this FT viz, thus we need world data to provide the lines in the grey backdrop:

![image](https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fcom.ft.imagepublish.upp-prod-eu.s3.amazonaws.com%2F9c58dd44-6c77-11ea-89df-41bea055720b?fit=scale-down&quality=highest&source=next&width=1260)

**Comment by zdavatz** [comment]
@netzwerg where do you have the South Korea Data from?

**Comment by netzwerg** [comment]
@zdavatz I don't know yet, that needs to be investigated. Some data seems to be available, e.g. on [Wikipedia](https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_South_Korea#Line_chart_for_cases_in_South_Korea).

**Comment by zdavatz** [comment]
try here: https://github.com/CSSEGISandData/COVID-19/

**Comment by jb3-2** [comment]
South Korean data can be found here:

https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv

**Comment by Eisit** [comment]
I opened (and closed, see comments as for why) a similar ticket for neighbouring countries: https://github.com/openZH/covid_19/issues/77

You can note the links listed there.

**Comment by netzwerg** [comment]
Closing this in favor of: https://renkulab.io/projects/covid-19/covid-19-public-data
