### ISSUE TITLE
Add population data

### ISSUE THREAD

**Issue by SandroLuescher** [openZH/covid_19#127]
Add raw population data (residents and absolute number of people over 65 per canton) to the panel files.

https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv

**Comment by tlorusso** [comment]
Thanks for bringing this up @SandroLuescher. Personally, i think its better to keep the cantonal files as slim as possible, as they're centered on data collection. As soon as we have set up a process to generate a csv containing the data for all cantons we can consider whether to add additional information. As a first step, feel free to add a separate csv with population numbers, that can easily be joined to the case data.

**Comment by zdavatz** [comment]
I would also collect population data per canton in a separate file.

**Comment by tlorusso** [comment]
Closing this for now.
