### ISSUE TITLE
TG: add district scraper

### ISSUE THREAD

**Issue by maekke** [openZH/covid_19#1275]
Page 6 contains the "Total kumuliert" and "Letzte 7 Tage" values that should be sufficient to create a scraper with weekly data.

https://www.tg.ch/public/upload/assets/103465/FP_LageTG_Wochenbericht.pdf

**Comment by metaodi** [comment]
I'll ask TG to provide this data in a machine-readable form, so that we don't have to scrape another PDF.

**Comment by maekke** [comment]
Great, thanks!

**Comment by metaodi** [comment]
TG added their district data on opendata.swiss as CSV: https://opendata.swiss/de/dataset/covid_19-fallzahlen-kanton-thurgau

Thanks @dkoltg!
