### ISSUE TITLE
new_hosp not filled for most cantons

### ISSUE THREAD

**Issue by jgrosseo** [openZH/covid_19#1279]
Is there a source where new_hosp is filled for whole CH or the separate cantons? 
COVID19_Fallzahlen_CH_total_v2.csv  has it for very few cantons.

Thanks, Jan

**Comment by metaodi** [comment]
Unfortunatly only very few cantons provide this number. If you find a source for this variable for a canton, that we do not yet have, please tell us, so we can integrate it.
On the other hand most cantons provide `current_hosp`, so at least a bit information about the hospitalisations is available. More infirmation about intensive care is available at https://icumonitoring.ch/

**Comment by jgrosseo** [comment]
Thanks for your quick reply, Stefan.

I just realized that the BAG xls for the daily report contains the new hospitalizations aggregated over Switzerland (but not per canton): 
It is in column D here:
https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx
