### ISSUE TITLE
Scraper FR

### ISSUE THREAD

**Issue by ebeusch** [openZH/covid_19#129]
Received an email answer from FR that they will start putting the numbers on their [website](https://www.fr.ch/) as of today (time unclear) and keep updating them from today onwards.

Their email was:
_Bonjour Madame
Nous avons bien reçu votre demande.
A ce sujet, dès aujourd’hui les chiffres concernant le canton de Fribourg seront publiés sur le site de l’Etat de Fribourg (www.fr.ch) et seront régulièrement mis à jour._

This serves as a reminder to myself or others to check the website periodically today.

**Comment by baryluk** [comment]
No updates yet as of now (2020-03-024 19:39). Still no numbers there or in few other pages.

**Comment by ebeusch** [comment]
Sent them an email once more (2020-03-25 16:12)

**Comment by grssnbchr** [comment]
I wonder where @daenuprobst has his FR figures from? Cf. https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv

**Comment by zdavatz** [comment]
> I wonder where @daenuprobst has his FR figures from? Cf. https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv

Good question ;) - think some special contacts. But lets see. Or just post an issue.

**Comment by ebeusch** [comment]
> I wonder where @daenuprobst has his FR figures from? Cf. https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv

Direct line to the canton, is my guess

**Comment by zdavatz** [comment]
> Direct line to the canton, is my guess

Yes mine as well. Not good and not helpful at all. @andreasamsler should get started together with @mmznrSTAT and call up their colleagues in FR and get the ball rolling for more transparency. Stupid political games going on here.

**Comment by zdavatz** [comment]
If FR will not react till tomorrow I will call them here by phone: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/77567056-e3a45880-6ec6-11ea-9250-4871ea998e55.png)

**Comment by ebeusch** [comment]
@zdavatz I have not yet received an email from FR regarding my second query and neither find any numbers online. So it would be good if you could make that call. (But I also think @andreasamsler,@mmznrSTAT @tlorusso carry more weight if they can go via ZH-stat to FR-stat)

**Comment by baryluk** [comment]
It would be best to have numbers directly available on: https://www.fr.ch/covid19 and https://www.fr.ch/de/covid19  and/or https://www.fr.ch/covid19/sante/covid-19/coronavirus-informations-actuelles and https://www.fr.ch/de/covid19/gesundheit/covid-19/coronavirus-aktuelle-informationen 

Also I personally think it is little bit confusing to have essentially two pages for the same things, that differ and provide partially same but not the same info.

If the info is not there by 14:30 today, could you call them @andreasamsler ?

**Comment by zdavatz** [comment]
> If FR will not react till tomorrow I will call them here by phone:
> ![latest-screenshot](https://user-images.githubusercontent.com/4953/77567056-e3a45880-6ec6-11ea-9250-4871ea998e55.png)

Ich habe die Assistentin von Frau Demierre erreicht (Frau Marianne Spindel) und sie ziemlich deutlich gefragt, warum Kanton FR der einzige Kanton der Schweiz ist, der noch keine Daten auf seiner Website publiziert.

**Comment by DonChef660** [comment]
FR Daten über BAG, Stand 25.03.2020: 251
https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

**Comment by zdavatz** [comment]
> FR Daten über BAG, Stand 25.03.2020: 251
> https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

Ja Danke, die Zahlen sind von gestern. Die Kantone sollte zur Zeit immer noch schneller sein, bis dann die Ärzte und Labore beginnen die editierbaren PDF zu verwenden. Siehe https://corona.bergi-it-consulting.ch/bag-formulare

**Comment by ebeusch** [comment]
_Nous avons bien reçu votre demande.

Les chiffres concernant le canton de Fribourg seront mis à jour sur le site de l’Etat de Fribourg  (www.fr.ch) à partir de 15h cet après-midi._

Halleluja! (I dare to hope - but I don't dare to make any more requests to them)

**Comment by zdavatz** [comment]
> _Nous avons bien reçu votre demande. Les chiffres concernant le canton de Fribourg seront mis à jour sur le site de l’Etat de Fribourg ([www.fr.ch](http://www.fr.ch)) à partir de 15h cet après-midi._
> Folgens Frau Rebetez.
> 
> Halleluja! (I dare to hope - but I don't dare to make any more requests to them)

Saubi!

**Comment by grssnbchr** [comment]
Finally... Imho it's better to wait for these data than to "pollute" the collection with BAG data...

**Comment by zukunft** [comment]
Got the same email ... nevertheless we should support FR if they request, so that the can concentrate on the "real/medical" issues.

**Comment by zdavatz** [comment]
> Finally... Imho it's better to wait for these data than to "pollute" the collection with BAG data...

@grssnbchr Not pollute, compare it in the scraper output. That is a BIG difference. See #211

**Comment by pnwscm60** [comment]
I had the same email yesterday... Let's hope, that today it becomes reality ;-). it's not so unexpected. I live in canton of Fribourg and the authorities are not loving transparancy!

**Comment by zdavatz** [comment]
> I had the same email yesterday... Let's hope, that today it becomes reality ;-). it's not so unexpected. I live in canton of Fribourg and the authorities are not loving transparancy!

Looks like it.

**Comment by mdeff** [comment]
I don't think @daenuprobst has a direct line to FR for his numbers at <https://github.com/daenuprobst/covid19-cases-switzerland>. If I understood correctly he used the cantonal prevalence published by BAG to fill in missing cantonal cases. His fatalities for FR are way off (1 on his data, 4 announced by media, more from a source I know at the hospital, see <https://github.com/daenuprobst/covid19-cases-switzerland/issues/38>). Let's hope they'll publish data again on <https://fr.ch>.

**Comment by zdavatz** [comment]
Just use the data from here now: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

**Comment by ebeusch** [comment]
> Just use the data from here now: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

Let's not do that - because FR just uploaded historic data!!! (I feel like it's my birthday).

@baryluk (or other scrapers I don't know by name) it's here: https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton

**Comment by pnwscm60** [comment]
Halleluja!
___________________________________________

Covid-19 geht uns alle an: Bleibt zu Hause, haltet Abstand und befolgt die Weisungen von Bund und Kanton!

Grafik zur Entwicklung ohne Massnahmen: https://ebpswiss.ch/animation.html <https://ebpswiss.ch/animation.html>
Seite Bundesamt für Gesundheit: https://www.bag.admin.ch/bag/de/home.html <https://www.bag.admin.ch/bag/de/home.html>
Aktuelle Fallzahlen: https://corona-data.ch <https://corona-data.ch/>
Patientenverfügung FMH (Kurzversion): https://www.fmh.ch/files/pdf23/fmh_pv_kv_2019_d.pdf <https://www.fmh.ch/files/pdf23/fmh_pv_kv_2019_d.pdf>

**Comment by zdavatz** [comment]
great job @ebeusch

**Comment by rsalzer** [comment]
> I wonder where @daenuprobst has his FR figures from? Cf. https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv

He uses the BAG-data to estimate FR ...

**Comment by zukunft** [comment]
Great.

**Comment by rsalzer** [comment]
Is someone already working on this? ;)

**Comment by baryluk** [comment]
@ebeusch Excellent.

That is perfect!

On it.

**Comment by zukunft** [comment]
2020-03-11,,FR,,16,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
--
2020-03-12,,FR,,22,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-13,,FR,,29,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-14,,FR,,36,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-15,,FR,,40,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-16,,FR,,45,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-17,,FR,,59,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-18,,FR,,86,  ,,,,0,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-19,,FR,,111,  ,,,,1,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-20,,FR,,145,  ,,,,1,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-21,,FR,,167,  ,,,,2,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-22,,FR,,202,  ,,,,3,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-23,,FR,,226,35,,,,4,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-24,,FR,,255,35,,,,5,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-25,,FR,,293,39,,,,6,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
2020-03-26,,FR,,309,44,,,,11,https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton

**Comment by ebeusch** [comment]
I feel like the stalking ex that can finally let it go.... thanks guys for taking over from now on :)

**Comment by tlorusso** [comment]
PR anyone? Not at my PC currently.

**Comment by rsalzer** [comment]
@zukunft Do a PR for it ... untill the scraper will work. Finally updated data for all cantons.

**Comment by zukunft** [comment]
On it

**Comment by baryluk** [comment]
Coding now.

```
 ./scrape_fr.sh
FR
Downloading: https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
Scraped at: 2020-03-26T15:28:22+01:00
Date and time: 26.03.20
Confirmed cases: 309
Deaths: 11
Hospitalized: 44
```

But, it is a little bit ugly:

```
m = re.search(r'<table class="table table-condensed table-hover">(.*?)</table>', d, flags=re.MULTILINE | re.DOTALL)
if not m:
  assert False, "Can't find table"

d = m[1]

print("Date and time:", sc.find('<tr>\s*<td>(\d\d\.\d\d\.\d\d)</td>', d))
print("Confirmed cases:", sc.find('<tr>\s*<td>(\d\d\.\d\d\.\d\d)</td>\s*<td>([0-9+]+|&nbsp;)</td>\s*<td>([0-9+]+|&nbsp;)</td>\s*<td>([0-9+]+|&nbsp;)</td>', d, group=4))
print("Deaths:", sc.find('<tr>\s*<td>(\d\d\.\d\d\.\d\d)</td>\s*<td>([0-9+]+|&nbsp;)</td>\s*<td>([0-9+]+|&nbsp;)</td>', d, group=3))
print("Hospitalized:", sc.find('<tr>\s*<td>(\d\d\.\d\d\.\d\d)</td>\s*<td>([0-9+]+|&nbsp;)</td>', d, group=2))
```

I would be interested to see @zukunft approach.

**Comment by MTBEnthusiast** [comment]
Site "https://www.fr.ch/de/covid19/gesundheit/covid-19/coronavirus-statistik-ueber-die-entwicklungen-im-kanton" should be used

**Comment by grssnbchr** [comment]
> Just use the data from here now: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx
> ![latest-screenshot](https://user-images.githubusercontent.com/4953/77650837-400d8380-6f6c-11ea-8f39-c239bad6e87d.png)

No, that would be exactly the wrong thing to do, I think. That's what I meant by polluting. But anyway, don't want to interfere too much with your great work, people. Thank you!

**Comment by rsalzer** [comment]
We got FR data now. The scraper is already in development. So no need for BAG data anymore 😇

**Comment by baryluk** [comment]
We can develop a separate tool for cross-checking BAG data, but we will see. Maybe tomorrow. We are archiving these files.

**Comment by baryluk** [comment]
@zukunft Ah I see now. Thanks for backfilling FR data into CSV. Awesome.

**Comment by zdavatz** [comment]
@baryluk I am now getting:
```
Traceback (most recent call last):
  File "././scrape_fr.sh", line 49, in <module>
    assert m, "Can't find table"
AssertionError: Can't find table
FR -                      -       - FAILED 2020-03-26T17:05:24+01:00 Missing date. Missing cases https://www.fr.ch/covid19/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton
```
