### ISSUE TITLE
ICU patients/ventilation

### ISSUE THREAD

**Issue by rneher** [openZH/covid_19#13]
Thanks a lot. great work. 

We are keen to use these data in 
neherlab.org/covid19/

It would be useful to add a column for patients in intensive care.  Italy provides good examples here

https://github.com/pcm-dpc/COVID-19

**Comment by andreasamsler** [comment]
Hi @rneher, you have been or are in contact already about that with Fabienne, right? Best, Andreas

**Comment by tlorusso** [comment]
We have added the column. As soon as we find a source for this information, we'll start to add it to the files.
