### ISSUE TITLE
Bestätigte Fälle und Hospitalisierungen

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#130]
I think a lot of Cantons will go in this direction: 
`Bestätigte Fälle` and `Hospitalisierungen`

https://www.gl.ch/verwaltung/finanzen-und-gesundheit/gesundheit/coronavirus.html/4817/l/de#Fallzahlen

we should also try to scrape `Hospitalisierungen` as much as possible. CC @baryluk

**Comment by zukunft** [comment]
I would say yes. I think Geneva is a kind of reference at the moment.

**Comment by baryluk** [comment]
Agreed.
Yes, we are starting to be doing it slowly.
We need to surface it in the parser too.

**Comment by metaodi** [comment]
Related to #237

**Comment by metaodi** [comment]
Fixed with #237 and to track more cantons #295 was created.
