### ISSUE TITLE
Scrape hospital capacities

### ISSUE THREAD

**Issue by dr-itz** [openZH/covid_19#1313]
Here https://www.vtg.admin.ch/de/organisation/astab/san/ksd/spitalkapazitaeten.html we have a per canton overview of the hospital capacities and occupations. The data is updated on Tue and Fri.

I'm thinking of a new file with one line per canton and date with the values from both tables

Would this fit here?

**Comment by dr-itz** [comment]
...and they stopped updating it...

**Comment by metaodi** [comment]
At least for ZH the numbers per hospital are in this repository: https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_zh/COVID19_Belegung_Intensivpflege.csv
