### ISSUE TITLE
Positive testing numbers missing

### ISSUE THREAD

**Issue by ineiti** [openZH/covid_19#1318]
The (positive) testing numbers don't seem to be updated anymore - could you scrape something like

https://covid-19-schweiz.bagapps.ch/fr-3.html

to get the data?

**Comment by metaodi** [comment]
related to #909 and #1026 

This is basically the content of PR #1280 and @maekke has the BAG data here https://github.com/maekke/bag_data

Some time ago we decided to only integrate data communicated by the cantons. Some cantons provide the BAG data themselves, and we're in the process of integrating it.

**Comment by metaodi** [comment]
The scrapers are now in place for a bunch of cantons, the data is here: https://github.com/openZH/covid_19/tree/master/fallzahlen_tests
