### ISSUE TITLE
Data from SZ and FR missing

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#132]
Die Kantone Schwyz (77 Infizierte, bisher kein Todesfall) und Freiburg (202 Fälle, 4 Verstorbene) liefern ihre Zahlen nur auf Anfrage. Da keine flächendeckenden Tests gemacht würden, seien die Fallzahlen «keine relevante Zahl», begründet Freiburg seinen passive Informationspolitik.

see: https://www.blick.ch/news/politik/aktuelle-coronavirus-zahlen-der-schweiz-so-informieren-kantone-ueber-die-corona-fallzahlen-id15810865.html

@baryluk all other Cantons should now be available on the website.

**Comment by ebeusch** [comment]
Also, see #129 
FR sent me this email:
_Bonjour Madame
Nous avons bien reçu votre demande.
A ce sujet, dès aujourd’hui les chiffres concernant le canton de Fribourg seront publiés sur le site de l’Etat de Fribourg  (www.fr.ch) et seront régulièrement mis à jour._
Still not seeing anything on their website though

**Comment by zdavatz** [comment]
@ebeusch grande! Looking forward to that!

**Comment by tlorusso** [comment]
Great! Thx @ebeusch :)

**Comment by zukunft** [comment]
I just called SZ and they are "working on it". As soon, they have something, they will send me (and probably many others) an email.

**Comment by ebeusch** [comment]
Great! Thanks for going after them @zukunft

**Comment by zdavatz** [comment]
@zukunft please convince them to publish on their website.

**Comment by zukunft** [comment]
Yes, will do, but one step after the other. Looks like they are collecting the information at the moment. 

And it looks to me that the BAG will also improve the collection process: https://www.hin.ch/covid-19-faelle-ans-bag-melden/ . Once this is done and working, we all will get much better data. And based on that, maybe we should create a tracing app based e.g. on owntracks.org ?

Reason: I want to go out again!

**Comment by zdavatz** [comment]
@zukunft yes, I know about the HIN Link, I told them to put it up. ;) The problem is, that the BAG still publishes non editable PDF files, so we put up a HOW-TO to help the BAG: have a look here: https://github.com/tgdbepe4/corona_ch_bag_formulare/blob/master/tests/Machbarkeit%20BAG%20Meldeformulare%20mit%20digialen%20Formularfeldern.pdf

Also, while you are talking to the Cantons, can you please tell them to use these Links:

With the following files the cursor jumps properly to the next input field if you press `Tab``

https://github.com/tgdbepe4/corona_ch_bag_formulare/tree/master/tests

**Comment by ebeusch** [comment]
I've kept checking FR's [website](www.fr.ch) (incl. links to subsections) all day and either I'm blind or the promised update still hasn't happened. If anyone could take a second check, that'd be appreciated.
If there's indeed no data for FR, I'll wait until tomorrow afternoon and then pester them again.

**Comment by zukunft** [comment]
I also don't find anything. Same in SZ. Maybe they are simply too afraid to ask for help.

**Comment by zukunft** [comment]
SZ has updated the numbers and they are already included. Now just FR is missing.

**Comment by ebeusch** [comment]
@zdavatz let's also close this.

**Comment by zdavatz** [comment]
Ok sure, closing now.
