### ISSUE TITLE
VS: district scraper fails

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#1326]
The [district scraper of VS currently fails](https://github.com/openZH/covid_19/runs/1353568829?check_suite_focus=true):

```
Populating database from CSV fallzahlen_kanton_VS_bezirk...
Run the district scraper...
Traceback (most recent call last):
  File "/home/runner/work/covid_19/covid_19/scrapers/scrape_vs_districts.py", line 97, in <module>
    district_values.append(int(value))
ValueError: invalid literal for int() with base 10: '146         16'
Error: Process completed with exit code 1.
```

**Comment by metaodi** [comment]
@maekke any ideas? I guess the PDF changed again a little bit.

**Comment by maekke** [comment]
Sure, I'll have a look in a bit! Need some fresh air first...

**Comment by metaodi** [comment]
@maekke really appreciate all the work you do for this repo. Please take care of yourself! 🙏
