### ISSUE TITLE
ZH: integrate ‚current_icu‘

### ISSUE THREAD

**Issue by amslera** [openZH/covid_19#1327]
Since today GD-ZH is reporting daily ‚current_icu‘ in https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_zh/COVID19_Fallzahlen_Kanton_ZH_total.csv

This variable/value is not integrated yet into https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv_v2

**Comment by metaodi** [comment]
on it.
