### ISSUE TITLE
Scraper for VD failed?

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#133]
I see data for the 23.03.2020 here https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/.
... and here https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt I see failed.

**Comment by zukunft** [comment]
Strange, if I run the version local I get:

Scraped at: 2020-03-24T13:20:38+01:00
Date and time: 23.03.2020
Confirmed cases: 2162
Deaths: 17

**Comment by tlorusso** [comment]
@zukunft VD is not automized yet : https://github.com/openZH/covid_19/blob/master/scrapers/STATUS.md

**Comment by dgerber** [comment]
I think there is now and then an issue with multiple redirects. Working on it...
