### ISSUE TITLE
Correction of case-numbers for the Canton of Zurich (affects the nine days before the 04.11.2020)

### ISSUE THREAD

**Issue by tlorusso** [openZH/covid_19#1332]
Due to an IT problem, one laboratory in the Canton of Zurich did not report any positive test results for nine days. The cases were recorded retroactively on the 4.11.2020. This has no effect on the number of cases on 4.11.2020.

**Comment by metaodi** [comment]
Here is the commit of this change: https://github.com/openZH/covid_19/commit/5a9fc826bc57f4b48460956654e291624c47d304
