### ISSUE TITLE
Typo in Bern?

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1344]
There seems to be a strange high number in Bern on 2020-10-08
<img width="520" alt="image" src="https://user-images.githubusercontent.com/17248257/98471672-48aa8580-21ee-11eb-9e55-de6bc81b152b.png">

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_BE_total.csv

Seems to be this commit:
https://github.com/openZH/covid_19/commit/69b0ec147f3a1622834daed4ac3b8a311d5213cf

**Comment by nachkontrolle** [comment]
The be.ch/corona site messed up with the dates 08.10.2020 instead of 08.10.2020 today.. 19'233 reflects the total number to date - I suspect this was then scraped?

**Comment by metaodi** [comment]
I adapted out scraper to fix the typo here: https://github.com/openZH/covid_19/pull/1345

The new data should be there in a minute.

**Comment by rsalzer** [comment]
Merci!
