### ISSUE TITLE
LU scraping URL changed

### ISSUE THREAD

**Issue by BrianG4** [openZH/covid_19#1358]
currently: [https://www.lustat.ch/analysen/gesundheit/corona-reporting](https://www.lustat.ch/analysen/gesundheit/corona-reporting)
with different page layout

**Comment by metaodi** [comment]
This is the reason why currently the scraper is disabled. We are in contact with LU to see if we can get the data in a machine-readble form. If not, we will adapt the scraper for the new page layout.

**Comment by BrianG4** [comment]
Thanks metaodi

**Comment by maekke** [comment]
@metaodi at least for the cases there is a csv available at https://www.lustat.ch/files_ftp/daten/covid/cov_faellekombi.csv
(fun fact the month is off by one)
