### ISSUE TITLE
SG: new columns for rapid antigen test ("Schnelltest")?

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#1363]
Since today, SG has separate columns for PCR and Schnelltest in the [CSV they provide](https://www.sg.ch/ueber-den-kanton-st-gallen/statistik/covid-19/_jcr_content/Par/sgch_downloadlist_729873930/DownloadListPar/sgch_download.ocFile/KantonSG_C19-Tests_download.csv).

Maybe we should adapt our tests scraper accordingly.

cc @maekke

**Comment by metaodi** [comment]
Or should we just use the sum of both columns?

**Comment by maekke** [comment]
I'm not really sure. If we want to stick to the principle to store, what we get from the cantons, we would need to add PCR pos, neg, tot and postivity, same for antigen tests. What we have now, would be the sum...
Kind of complicated, but maybe the cleanest?

**Comment by metaodi** [comment]
Let's keep this issue open for the moment, no need to rush. If other cantons provide this data, we can consider it again.
