### ISSUE TITLE
SO: hosp seems to have more then doubled in one day

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1368]
There seems to be something wrong with the current_hosp in SO.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/17248257/99076497-8545fa80-25bb-11eb-8733-6b9979973898.png">

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_SO_total.csv

**Comment by simgraworldwide** [comment]
SO is about to correct the data, thanks for the notification!

**Comment by metaodi** [comment]
The source was fixed and the scraper picked ul the new data in commit https://github.com/openZH/covid_19/commit/768c69fd29131d76716f731ff2e307407bdd35d7
