### ISSUE TITLE
VS: Monthey Week 45: Value 60 instead 601 stored

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1401]
The document https://www.vs.ch/documents/6756452/7008787/2020%2011%2011%20-%20Synthese%20COVID-19%20VS%20Woche45 shows the value of 601 for the district of Monthey, but 60 is stored in the https://github.com/openZH/covid_19/blob/master/fallzahlen_bezirke/fallzahlen_kanton_VS_bezirk.csv
Other values for week 45 are correct.

**Comment by maekke** [comment]
good point, should be manually fixed in #1403 - thanks for the heads up!
