### ISSUE TITLE
UR scraper fails

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#141]
Currently the UR scraper fails:

```
Run the scraper...
Traceback (most recent call last):
  File "/home/runner/work/covid_19/covid_19/scrapers/parse_scrape_output.py", line 170, in <module>
    print("{:2} {:<16} {:>7} {:>7} OK {}".format(abbr, date, cases, deaths if not deaths is None else "-", scrape_time))
TypeError: unsupported format string passed to NoneType.__format__
Export database to CSV...
```
cc @baryluk

**Comment by metaodi** [comment]
The [website](https://www.ur.ch/themen/2920) changed:


> Der Kantonale Führungsstab hat am heutigen Lagerapport zur Kenntnis genommen, dass im Kanton Uri zurzeit 25 Personen mit dem Coronavirus infiziert sind (Stand: 24. März 2020, 12.00 Uhr). Eine Person ist hospitalisiert. Eine Person ist genesen.

**Comment by ebeusch** [comment]
One more item for the to-do list: kindly ask all cantons to please stick to one format.

**Comment by zdavatz** [comment]
We should actually show them what the format is, also in terms of the URL path.

**Comment by ebeusch** [comment]
@zdavatz that would be ideal but we should also keep in mind that smaller cantons might not have the resources to do so.

**Comment by zdavatz** [comment]
yes, then a simple HTML file could suffice.

**Comment by baryluk** [comment]
On it.

**Comment by baryluk** [comment]
Fixed
