### ISSUE TITLE
New source for JU scraper

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#146]
https://www.jura.ch/fr/Autorites/Coronavirus/Chiffres/Evolution-des-cas-COVID-19-dans-le-Jura.html

**Comment by zdavatz** [comment]
Thank you! cc @baryluk can we grab this?

**Comment by baryluk** [comment]
Yes. That is nice. The current scrapper works now, but this table is probably going to be a bit more stable, and has information about other things. So we can grab it, but low priority as of today. Some other scrapers to be fixed first.

**Comment by zdavatz** [comment]
We are now going to automate your scrapers for our [Dashboard](http://covid19.ddrobotec.com/), see: https://github.com/zdavatz/covid19_ch

**Comment by baryluk** [comment]
Still low priority, as existing scraper works, and the table provides historical information to.

But I will make a new scraper for JU today. As the data linked by @andreasamsler also provides information about hospitalizations, ICU, and deaths (none fortunately yet, but table is easy to parse if it changes), which will be useful for our datasets.

**Comment by baryluk** [comment]
I just started working on this. Because it does provide some extra information, which we will be using soon in the importer.

**Comment by baryluk** [comment]
FYI. The URL changed: https://www.jura.ch/fr/Autorites/Coronavirus/Chiffres-H-JU/Evolution-des-cas-COVID-19-dans-le-Jura.html

**Comment by baryluk** [comment]
```
$ ./scrape_ju.sh  
JU
Downloading: https://www.jura.ch/fr/Autorites/Coronavirus/Accueil/Coronavirus-Informations-officielles-a-la-population-jurassienne.html
Scraped at: 2020-03-27T23:22:37+01:00
Date and time: 27 mars 2020 (16h)
Confirmed cases: 112
Downloading: https://www.jura.ch/fr/Autorites/Coronavirus/Chiffres-H-JU/Evolution-des-cas-COVID-19-dans-le-Jura.html
Scraped at: 2020-03-27T23:22:37+01:00
Date and time: 27 mars 2020
Confirmed cases: 112
Hospitalized: 16
ICU: 4
```

It should also pickup automatically numbers for deceased, once they are non empty in the table.
