### ISSUE TITLE
FR: sheet in xls for tests is missing

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#1476]
Up until today the XLS from FR contained a sheet called `tests COVID19`, which contained the data about tests. It is now missing.

**Comment by simgraworldwide** [comment]
The request is pending.

**Comment by maekke** [comment]
They also removed the graph from https://www.fr.ch/sante/covid-19/coronavirus-statistiques-evolution-de-la-situation-dans-le-canton this week.

**Comment by metaodi** [comment]
I removed the executable flag from `scrape_fr_tests.py`, so that the test run of all scraper does not run this scraper.

**Comment by maekke** [comment]
The tests data is back. But it's split up into Antigen and PCR tests (both quantity and positivity rate).
Not sure how we should handle this, I think we have a similar issue with SG (but they provide the individual and total values). I see the following options:
- just add the total number tests, but leave out positivity rate
- add the total number of tests and calculate the positivity rate
- start splitting up tests data into PCR, Antigen and Total data

@metaodi what do you think suits best here?
