### ISSUE TITLE
150% Spitalauslastung

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1486]
The "Intensivpflege-Belegung" shows 150% occupancy for "Hirslanden Klinik im Park". Is this right?

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_zh/COVID19_Belegung_Intensivpflege.csv

<img width="695" alt="image" src="https://user-images.githubusercontent.com/17248257/102258440-b3856580-3eec-11eb-96d6-d36c44d2f953.png">

**Comment by tlorusso** [comment]
The reported numbers are correct. The "Klinik im Park" has 6 certified ICU beds that are currently occupied. Additionally they have three not certified intensive care beds, which are occupied as well.
