### ISSUE TITLE
Need to Update BL scrapper - Data now as graph on new webpage

### ISSUE THREAD

**Issue by deragent** [openZH/covid_19#149]
The data of BL is now published as a graph on the following webpage: https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/covid-19-faelle-kanton-basel-landschaft

**Comment by zdavatz** [comment]
good to know.

**Comment by deragent** [comment]
I implemented a new scrapper for the new BL data source in https://github.com/openZH/covid_19/pull/148

**Comment by deragent** [comment]
Solved with #148
