### ISSUE TITLE
GE: Numbers inconsistent

### ISSUE THREAD

**Issue by jgrosseo** [openZH/covid_19#1491]
The numbers of GE seem not be right since December 6th. The cases per day are always 37.
The root cause seems to be the GE excel sheet at https://www.ge.ch/document/21502/telecharger
which reports inconsistent numbers in column B (cumul cas) and C (nombre cas). You can see this by comparing to column D which I added and which computes the difference to the day before:
![image](https://user-images.githubusercontent.com/25029837/102478734-40036580-405e-11eb-88ef-7560cf5199e1.png)

Could you alert the GE office about this?

**Comment by andreasamsler** [comment]
Thanks @jgrosseo, for your message. We've informed the contact point in GE about the issue in their data source, and expect them to fix it, so this can be resolved quickly.

**Comment by amslera** [comment]
Update: At the moment GE ‚ncumul_conf‘ are not plausible after 2020-11-01.

**Comment by jgrosseo** [comment]
The original GE source as well as the aggregation seems fixed now. Thanks for the quick action. I am closing this.
