### ISSUE TITLE
Limited maintenance of data from Cantons & FL over the festive period (affects not: data from Canton of Zurich)

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#1501]
Dear users and interested folks

As we cannot rule out hiccups in Covid19 data communicated by cantons & FL on their websites over the festive period, we have to expect inconsistencies in cantonal time series in our repository until 4 January.

> Maintenance of our initiative, which has been supported by many volunteers since March, is therefore limited.

However, thanks to our colleagues at the FOPH and many others, it is no longer as necessary as it has been over the past few months. 

> We recommend: Consider for key variables changing your data source to FOPH's API, providing the current valid URLs to FOPH's data: https://covid19.admin.ch/api/data/context
Additional documentation: https://www.covid19.admin.ch/api/data/documentation

We'd like to express our gratitude to all those who have helped to identify, address and close gaps in Covid19 public health data.

In addition to FOPH's data, our repo https://github.com/openZH/covid_19 contains more data from cantons & FL; some provide variables that go beyond key variables, some data with higher granularity.

If necessary, you can reach us via twitter. We'd like you to check GitHub first.

Many thanks.

**Comment by fabian** [comment]
Additional Documentation for the FOPH API: https://www.covid19.admin.ch/api/data/documentation

**Comment by metaodi** [comment]
Since this period is over, I'm closing this issue now.
