### ISSUE TITLE
Port scrapers from bash to Python

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#152]
Bash is nice and it was quick to add many scraper, but we do see many failures, and it leads to some issues.

1. Not many people are familiar with bash, grep, sed, awk, to help with fix contribution.
2. Currently we use `set -e` (without `set -x`), which means if the scraper fails, it leaves no useful error messages.
3. Due to nature of `sed`, it often needs to be protected by extraneous and somehow redundant `grep` or `head -1` around it. This is because if the `sed` doesn't match anything on the line, it will output the line as is, malforming the output.

Use of Python (we can port one scraper at a time) will help:

1. More familiar.
2. Easier use of functions, logging, and exception messages, which should help with debugging.
3. Instead of using `grep+sed+tricks`, or `sed` with `s/^.*....().....*$/\1/` trickery, we can just use something like `re.search("...()...", d)[1]`, or a helper function (shared by scrapers) to make it ever easier. This should actually make shorter and cleaner script (no redundant `grep+sed`), that is also a bit more robust against parsing of multiple lines (no need for `head -1`, and eliminate some other steps that we do in bash right now.
4. Python has raw strings, which helps with regexp writing, due to reduction of backslash escaping needed.

**Comment by zdavatz** [comment]
Ok! Sounds like a plan although `awk` is great, as Linus says ;).

**Comment by metaodi** [comment]
The scraper for SG that is run by GitHub actions is already written in Python: https://github.com/openZH/covid_19/blob/master/scrapers/scraper_canton_sg.py

And i still have some floating around from morph.io, so I can simply move them here.

**Comment by baryluk** [comment]
The script you have is not just a scraper (it does few other things), and is 5 times longer than needs to be. The same can be achieved in just few lines of code.

I will port most of he bash scrapers to Python today, it is a very easy process. Nothing fancy.

**Comment by metaodi** [comment]
@baryluk I agree it's longer than needed (the scraper part being from L35-L52). But IMHO the sqlite part really makes sense to manage input and output:

- it defines a clear schema
- I can add constraints (like a UNIQUE) and therefore make sure to only generate one entry per date + time
- make sure the data in the CSV file is always used as an input (and if it's invalid it breaks)

Feel free to rewrite it shorter, but please be aware that we need more than "just a scraper", the result must be added to the existing file without losing information (e.g. if someone manually added data to a column the scraper does not provide).

**Comment by baryluk** [comment]
@metaodi Yes, it is just a job of other scripts to do that.

The scraper output can easily be consumed by others (after paring by parser).

Here is the prototype for ZH: https://github.com/baryluk/covid_19/commit/72de5616652280d6ba9b306d3ff68a776572a725

**Comment by metaodi** [comment]
Oh okay. This is really just a 1:1 port to python without using any library or idioms.

But it's an okayish first step, let's iterate if needed :wink:

**Comment by baryluk** [comment]
I would say it is very idiomatic. KISS principle. :wink:

**Comment by baryluk** [comment]
PR for the library and ZH scraper sent: https://github.com/openZH/covid_19/pull/158

I also have AI scraper done using same library. It is really short and readable.

**Comment by zdavatz** [comment]
This output should only contain the successful data, not the errors or the error output: https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt

If the script fails, then just ad a timestamp when it failed.

See also: https://github.com/zdavatz/covid19_ch/issues/17

Our [Dashboard](http://covid19.ddrobotec.com/) is now updating every hour and it make no sense to write a parser for the parser.

**Comment by ebeusch** [comment]
If it's worth anything: https://github.com/ebeusch/covid-19_scraper_LU
here's my python attempt for LU from the past weekend. maybe you can use one line or two ^^'

**Comment by metaodi** [comment]
I close this issue. The ZH scraper was successfully migrated from shell to python. And AI has been implemented in the same manner.

Finally with SG we have yet another python scraper with a different approach. Feel free to migrate or implement other scrapers as well.

**Comment by baryluk** [comment]
@metaodi Could you please leave it open for a moment. I have almost all existing scrapers ported, just didn't make a PR for it, because of some other PRs in progress, and issues with merges.

**Comment by baryluk** [comment]
@ebeusch I will take a look. It might be useful to have parser for some number as words. For example https://www.ur.ch/themen/2920 for UR, states number of deaths as a word.

**Comment by baryluk** [comment]
Porting status:

```
scrape_ag.sh:#!/bin/sh
scrape_ai.sh:#!/usr/bin/env python3
scrape_ar.sh:#!/usr/bin/env python3
scrape_be.sh:#!/usr/bin/env python3
scrape_bl.sh:#!/bin/sh
scrape_bs.sh:#!/bin/sh
scrape_ge.sh:#!/bin/sh
scrape_gl.sh:#!/usr/bin/env python3
scrape_gr.sh:#!/usr/bin/env python3
scrape_ju.sh:#!/usr/bin/env python3
scrape_lu.sh:#!/bin/sh
scrape_ne.sh:#!/usr/bin/env python3
scrape_nw.sh:#!/usr/bin/env python3
scrape_ow.sh:#!/usr/bin/env python3
scrape_sg.sh:#!/bin/sh
scrape_sh.sh:#!/usr/bin/env python3
scrape_so.sh:#!/usr/bin/env python3
scrape_sz.sh:#!/usr/bin/env python3
scrape_tg.sh:#!/usr/bin/env python3
scrape_ti.sh:#!/usr/bin/env python3
scrape_ur.sh:#!/usr/bin/env python3
scrape_vd.sh:#!/bin/sh
scrape_vs.sh:#!/usr/bin/env python3
scrape_zg.sh:#!/usr/bin/env python3
scrape_zh.sh:#!/usr/bin/env python3
```

**Comment by zdavatz** [comment]
great work, @baryluk

**Comment by baryluk** [comment]
Ack. Good. Thanks for testing.

VD works for me.

What kind of shell are you using? (`ls -l /bin/sh`)

I already sent fix for NW (both bash and python version, and it is in the pythonize branch). Their page was updated ~2 hours ago.

I also just updated the GE to also show URL. It was not showing because of slightly different logic in PDF downloader. Now it should be same as others.

I will address timestamp for failures next.

**Comment by zdavatz** [comment]
> ls -l /bin/sh
`/bin/sh -> bash`

**Comment by baryluk** [comment]
> > ls -l /bin/sh
> 
> `/bin/sh -> bash`

@zdavatz Ok. Filled a bug about it. https://github.com/openZH/covid_19/issues/205   It can be fixed to work in bash too probably. Or we can make it work in Python too. It is the last one not implemented in Python.

**Comment by zdavatz** [comment]
Request for failed timestamp issue is here: https://github.com/openZH/covid_19/issues/206
