### ISSUE TITLE
Canton ZG: Deceased drops to 0

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1524]
There seems to be an issue with Zug:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/17248257/103286085-fb71b580-49df-11eb-8374-778882e91279.png">

**Comment by metaodi** [comment]
Yes we noticed that as well (this is the "Validare CSV" job running on this repo):

![Screenshot_20201229-165304](https://user-images.githubusercontent.com/538415/103296516-85c51400-49f6-11eb-9ce5-bd7287303b36.png)

We are currently waiting for ZG to fix their data.

**Comment by metaodi** [comment]
In the meantime I disabled the scraper of ZG and removed the `0` value

**Comment by amslera** [comment]
Resolved: https://github.com/openZH/covid_19/commit/7b02425ebce01a8eefee8b55abaa26fa82f65081
