### ISSUE TITLE
Wrong year in new entry for SO

### ISSUE THREAD

**Issue by sizuest** [openZH/covid_19#1551]
One new entry of SO is showing the wrong year:

date | time | abbreviation_canton_and_fl | ncumul_tested | ncumul_conf | new_hosp | current_hosp | current_icu | current_vent | ncumul_released | ncumul_deceased | source | current_isolated | current_quarantined | current_quarantined_riskareatravel | TotalPosTests1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
04.01.**2020** | 01:00 | SO |   | **10992** |   | 68 | 13 |   |   | 217 | https://corona.so.ch/index.php?id=27979 |

**Comment by sizuest** [comment]
Correction: It's kind of a double entry. It should only be entred once for 04.01.2021. Instead the entry is also made for 04.01.2020:

date | time | abbreviation_canton_and_fl | ncumul_tested | ncumul_conf | new_hosp | current_hosp | current_icu | current_vent | ncumul_released | ncumul_deceased | source | current_isolated | current_quarantined | current_quarantined_riskareatravel | TotalPosTests1 | ninst_ICU_intub
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
04.01.2020 | 01:00 | SO |   | **10992** |   | 68 | 13 |   |   | 217 | https://corona.so.ch/index.php?id=27979 |   |  
04.01.2021 | 01:00 | SO |   | **10992** |   | 68 | 13 |   |   |   | https://corona.so.ch/ |   |   |   |

**Comment by metaodi** [comment]
jup we're on it #1549

**Comment by metaodi** [comment]
SO publishes the wrong year on their [website](https://corona.so.ch/index.php?id=27979):

![grafik](https://user-images.githubusercontent.com/538415/103635868-6de71600-4f49-11eb-8e71-79d7b5993dbe.png)

We will ask them to change their website and this should be resolved.

**Comment by metaodi** [comment]
It's fixed in the repo with https://github.com/openZH/covid_19/commit/d48b52008c4bd717e16180850cffd72e219c9085
