### ISSUE TITLE
Hospital occupancy

### ISSUE THREAD

**Issue by chnuessli** [openZH/covid_19#1565]
Hello all.

First, very interesting work you've invested the last few months - kudos!
I took a look at the abandoned repo (https://github.com/openZH/covid19_hospitalinfra) as in my/our interest is the hospital data is there an effort to reactivate the other repo, or to integrate this data in this repo?
Since i know, the hospitals must report their capacity to the health departments.

Looking forward to this discussion.

Greets Christian

**Comment by andreasamsler** [comment]
Hi @chnuessli, thanks for reaching out, I am contacting you directly. Best, Andreas

**Comment by andreasamsler** [comment]
Clarified: obsolete.
