### ISSUE TITLE
District data Thurgau

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1576]
The csv from Thurgau seems to be broken, only entries for Week 1 2020 (should be 2021?) and all the old data is missing. 

Is there a way to check with canton of Thrugau?

**Comment by andreasamsler** [comment]
Thanks, we're checking with TG.

**Comment by dkoltg** [comment]
Where exactly is the problem to be fixed?

**Comment by dkoltg** [comment]
I have seen it now and will fix it so that 2020 and 2021 will be shown in the data. Sorry for that!

**Comment by dkoltg** [comment]
Problem should be solved :)

**Comment by balzamas** [comment]
Thank you for the quick fix!

**Comment by metaodi** [comment]
I removed the wrong values from week 1 2020, since they should actually be 2021: https://github.com/openZH/covid_19/pull/1577
