### ISSUE TITLE
Bezirke Zürich - totals start with 0 in new year

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1584]
The latest numbers (ISO-Week 1 of 2021) seem to have the totals equal to the new cases.  
I hope it is not intended to reset the totals to 0 just because of a new year ...

Example:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/17248257/104253531-fa776400-5474-11eb-99dc-cbcce1b467a3.png">

https://github.com/openZH/covid_19/blob/master/fallzahlen_bezirke/fallzahlen_kanton_ZH_bezirk.csv

**Comment by andreasamsler** [comment]
Analysed, and assigned to @GD-ZH to be fixed.

**Comment by amslera** [comment]
Update: „Die kumulierten Fälle stimmen alle nicht, da jetzt von KW 1 aufsummiert wurde, das heisst KW 9 hat schon die kumulativen Fälle von KW 1. (..) Stimmt nach dem Pushen  (von heute Dienstagnachmittag) wieder.“

**Comment by andreasamsler** [comment]
Fixed with https://github.com/openZH/covid_19/commit/65674ce6d2aea9a22fc073805668d2783c2e8fe1#diff-11df868428340f97a63775a677693156abdf7e82bb733b75a40d5017abf2bd70
