### ISSUE TITLE
AR: doesn't publish case data anymore

### ISSUE THREAD

**Issue by imsodin** [openZH/covid_19#1624]
AR does not report case data on their site any more, but refers to the BAG data. They still do report CT and vaccination data: https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/

The scraper thus doesn't pick up new data any more. What's the policy here - get as complete a data set as possible, thus as the canton is referencing BAG, should the case data be obtained from there; Or have a cantonal dataset that's independent from BAG, thus update the scraper to only update CT/vaccination data?  
(The dashboard doesn't represent that as a failure, resp. indicates that data is more than 24h old - I guess that's some weekend workaround.)

**Comment by andreasamsler** [comment]
Thanks for your question. Our policy has always been to include only those data in our repository that are published by the cantons & FL on their own web channels. Over time, they did so in an increasingly machine-readable way, which allowed us to continue to operate this source.

Meanwhile, case numbers are easily available for reuse via FOPH's API: https://github.com/openZH/covid_19/discussions/1479#discussioncomment-214356

For cantons where this is the case, as in AR, we will discuss how to make this transparent.

**Comment by andreasamsler** [comment]
Discussed, will be fixed with #1626

**Comment by metaodi** [comment]
The table in the README (https://github.com/openZH/covid_19#latest-updates) now has up-to-date information from which date the latest data of a canton is in our repository. Specifically for AR there are information in the table about the FOPH data.

The table self-updates after every scraper run.

**Comment by imsodin** [comment]
The status table was just a secondary issue. And it still isn't working: It says there's data on 2021-02-01. There is no data since 2021-01-26: https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_AR_total.csv

The main issue is that the scraper does not work any more because the website changed when AR stopped reporting cases. They still do report CT and vaccination data, which could still be scraped.

**Comment by andreasamsler** [comment]
Thanks @imsodin, separate issue opened about AR scraper #1629
