### ISSUE TITLE
AR scraper

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#1629]
@imsodin reported (https://github.com/openZH/covid_19/issues/1624#issue-797703696) that AR scraper does not work any more because the website changed when AR stopped reporting cases. They still do report CT and vaccination data, which could still be scraped.

**Comment by andreasamsler** [comment]
Analysed. @imsodin: variables 'current_isolated | current_quarantined | current_quarantined_riskareatravel | current_quarantined_total' are being scraped (s. rows on the right)

Status update table in our README atm is covering the latest data update of any (if only one) variable. Will make that more clear with words.

We decided not (yet) to collect vaccination data in this Repo, before variables are not harmonized by Cantons and FOPH (which we expect to see around mid-February).

**Comment by andreasamsler** [comment]
Documentation (row titles) updated.

**Comment by imsodin** [comment]
Uh, my bad. Sorry for the noise and thanks for the quick reactions, and generally all the work you do!
