### ISSUE TITLE
refresh of (french Chrome) view: 14 jours and then 14 years

### ISSUE THREAD

**Issue by jumpyjpl** [openZH/covid_19#1636]
When I load the for the 1st time the page,  (https://rsalzer.github.io/COVID_19_CH/) windows 10 english and chrome in french, I get the message:
Nombre de nouvelles infections pour 100 000 habitants en **14 jours**
then 2 seconde later I get 
Nombre de nouvelles infections pour 100 000 habitants en **14 ans**
If I do a refresh I get the same reaction!
Anyway great information Information

Jpl

**Comment by andreasamsler** [comment]
Please post your issue in the repo of the maker of the application, which you are referring to, thanks: https://github.com/rsalzer/COVID_19_CH
