### ISSUE TITLE
ZH: adapt scraper to get isolated/quarantined

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#1637]
@GD-ZH is publishing isolated/quarantined in a new table on https://www.zh.ch/de/gesundheit/coronavirus.html#main_table

Isolated/quarantined are not scraped correctly anymore; that data is not pushed by @GD-ZH into our repo :(

I therefore see no better option atm (.cc @tlorusso) than to adapt the scraper.

**Comment by metaodi** [comment]
on it.

**Comment by andreasamsler** [comment]
Looking forward onto your take regarding https://shkspr.mobi/blog/2021/01/the-unreasonable-effectiveness-of-simple-html/ if our ZHweb CMS delivers simple HTML ;)
