### ISSUE TITLE
Scraper for SZ

### ISSUE THREAD

**Issue by ebeusch** [openZH/covid_19#164]
@baryluk SZ now has numbers as pointed out by @zukunft in #132 
They are listed under "Allgemeine Informationen" on the [official website](https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948)

By now I have also received an email from SZ informing of the above. I have asked them if they plan to also publish numbers of hospitalised. They said so far they are not aware of more types of numbers being published in the future but that they will forward my input ;)

**Comment by baryluk** [comment]
Ok. I don't see any pull request fixing / implementing new source for SZ, so lets me take this.

**Comment by baryluk** [comment]
Ok. PR incoming.

**Comment by deragent** [comment]
If necessary, I also have a working version for SZ.

**Comment by baryluk** [comment]
@deragent Thanks deragent. Feel free to compare with the current version at https://github.com/openZH/covid_19/blob/master/scrapers/scrape_sz.sh
