### ISSUE TITLE
Hospitalisation values BE

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#1726]
Hospitalisation values of BE from https://www.besondere-lage.sites.be.ch/de/start/news/fallzahlen.html are atm not harvested.
- have they been, and from which source?
- values have got asterisks attached, might that be an issue?

Thanks for further analysing the issue, and proposing how to deal with this.

**Comment by metaodi** [comment]
Here is the code:

https://github.com/openZH/covid_19/blob/a2aadd6bb20655aab204c3f677e7b0d627207e91/scrapers/scrape_be.py#L26-L29

i.e. an asterisks indicates and non-current value and is ignored.

**Comment by andreasamsler** [comment]
Many thanks, so "is ignored" means, that:
a. the asterisk is ignored, and values would be scraped or
b. values with asterisks are ignored, and not scraped?

**Comment by metaodi** [comment]
> Many thanks, so "is ignored" means, that:
> a. the asterisk is ignored, and values would be scraped or
> b. values with asterisks are ignored, and not scraped?
> 

b.
