### ISSUE TITLE
Data ZH

### ISSUE THREAD

**Issue by MTBEnthusiast** [openZH/covid_19#1765]
Data from the canton of Zurich are not updated

**Comment by andreasamsler** [comment]
Monday 2021-04-19, no data was updated by @GD-ZH (except: travel self quarantine, https://github.com/openZH/covid_19/tree/master#canton-zurich-travel-self-quarantine) due to a public holiday (Sechseläuten).

**Comment by MTBEnthusiast** [comment]
Shame on me!!!!

 

Rolf

 

 

Diese E-Mail kann vertrauliche und/oder rechtlich geschützte Informationen beinhalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unerlaubte Weitergabe dieser E-Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this email in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this email is strictly forbidden.

 

Von: Andreas Amsler ***@***.***> 
Gesendet: Dienstag, 20. April 2021 08:43
An: openZH/covid_19 ***@***.***>
Cc: MTBEnthusiast ***@***.***>; Author ***@***.***>
Betreff: Re: [openZH/covid_19] Data ZH (#1765)

 

Monday 2021-04-19, no data was updated by @GD-ZH <https://github.com/GD-ZH>  (except: travel self quarantine, https://github.com/openZH/covid_19/tree/master#canton-zurich-travel-self-quarantine) due to a public holiday (Sechseläuten).

**Comment by andreasamsler** [comment]
Don't be so hard on yourself :)
