### ISSUE TITLE
Fribourg ... deaths instead of cases

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1772]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/17248257/115992401-dc6de380-a5cd-11eb-84f3-8585bfc51cb0.png">

Canton FR seems to have reported the wrong death-totals yesterday.

**Comment by andreasamsler** [comment]
Thanks, we're checking with FR.

**Comment by andreasamsler** [comment]
FR seems to have corrected the mix-up in the meantime. Can you confirm @rsalzer ?

**Comment by rsalzer** [comment]
Thank you!
