### ISSUE TITLE
Add historized data for VS

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#179]
https://www.vs.ch/documents/6756452/7008787/Sit%20Epid%20-%20%C3%89tat%20Stand%2025.03.2020.pdf

**Comment by zukunft** [comment]
Can do, but can you have a look at #167?

**Comment by zukunft** [comment]
@ andreasamsler  Now included in #180

**Comment by tlorusso** [comment]
I will look into #180 tomorrow. Thx a lot @zukunft. Feel free to go for #179 already :)

**Comment by tlorusso** [comment]
Done! Thanks @zukunft :)
