### ISSUE TITLE
Canton JU: Scraper not working?

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1843]
Last numbers are from July 13th. Website seems to contain newer data: https://www.jura.ch/fr/Autorites/Coronavirus/Infos-Actualite/Statistiques-COVID/Evolution-des-cas-COVID-19-dans-le-Jura.html

**Comment by metaodi** [comment]
Yes, I'm on it: #1841

It's quite painful as I have to scrape a Power BI table which loads new data when scrolling, so it's a bit cumbersome.

**Comment by metaodi** [comment]
Fixed with #1841
