### ISSUE TITLE
Das BAG publiziert nun seinen eigenen offiziellen Zahlen als XLSX

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#185]
Das BAG publiziert nun seinen eigenen offiziellen Zahlen, als XLSX.

https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

Nun kann man vergleichen. cc @andreasamsler @mmznrSTAT 

ich würde diese Daten unbedingt reinziehen, jeden Tag, ein Backup machen.

**Comment by andreasamsler** [comment]
Hallo Zeno, was möchtest du mit welchem Ziel miteinander vergleichen?

**Comment by zukunft** [comment]
Das Problem ist wohl, dass das BAG die Zählung am Tag der Probenentnahme macht, während die Kantonen sich wohl eher auf den Tag des positiven Ergebnisses beziehen. Oder liege ich hier falsch?
Bisher geben die Kantone die Daten auf Personenstufe kaum bekannt, von einzelnen Ausnahmen zu Beginn der Pandemie mal abgesehen. Im Moment wäre ich schon froh, wenn zum Beispiel Freiburg überhaupt Zahlen liefern würde. Ich habe heute mit denen telefoniert und würde mehrmal verbunden, aber am Ende haben wir (noch) keine Zahlen.
Ich habe gehört, das externe Firmen dem BAG jetzt helfen. Es kann also sein, dass sich das ganz bald entspannt und auch diese Plattform einfacher zu besseren Daten kommt.

**Comment by baryluk** [comment]
I just started automatic archiving of this XLSX document, hourly.

Can't open at the moment, because my libreoffice is crashing (not a fault of the document).

**Comment by oschihin** [comment]
@baryluk natürlich kann man die Excelblätter des BAG auf einem Server abspeichern, das ist unproblematisch. Mir ist aber der Sinn davon nicht klar, da 1) die Daten / Excel auf de Webseite des BAG verfügbar sind und wohl vorläufig auch bleiben werden 2) diese Daten gemäss Archivgesetz einmal vom Bundesarchiv archiviert werden. Mit "archivieren" meine ich nicht eine Sicherungskopie so nützlich das sein kann, sondern ein Aufbewahren und Zugänglichhalten über eine unbestimmte Dauer.

Wichtig ist: Dass die Datengrundlage in diesem Repository auch einmal archiviert wird (gemäss obiger Kürzestdefinition). Aber davon gehe ich aus, da es sich ja auch um eine Aktivität einer kantonalen Fachstelle handelt.

**Comment by zdavatz** [comment]
> Can't open at the moment, because my libreoffice is crashing (not a fault of the document).

You are archiving the PDF, better archive the XLSX. ;)

**Comment by zdavatz** [comment]
> Das Problem ist wohl, dass das BAG die Zählung am Tag der Probenentnahme macht, während die Kantonen sich wohl eher auf den Tag des positiven Ergebnisses beziehen. Oder liege ich hier falsch?
> Bisher geben die Kantone die Daten auf Personenstufe kaum bekannt, von einzelnen Ausnahmen zu Beginn der Pandemie mal abgesehen. Im Moment wäre ich schon froh, wenn zum Beispiel Freiburg überhaupt Zahlen liefern würde. Ich habe heute mit denen telefoniert und würde mehrmal verbunden, aber am Ende haben wir (noch) keine Zahlen.
> Ich habe gehört, das externe Firmen dem BAG jetzt helfen. Es kann also sein, dass sich das ganz bald entspannt und auch diese Plattform einfacher zu besseren Daten kommt.

Ja, das sehe ich auch so. Ich weiss jetzt von zuverlässiger Quelle, dass das BAG die Fax-Formulare am überarbeiten ist. HIN wird/will das editierbare PDF Formular auch bei den Praxis-Software-Anbieter einbinden (die haben grosses Interesse), somit sollten wir vom BAG bald viel bessere Zahlen kriegen. Das wird dann auch wieder Druck auf die Kantone machen, zum bessere Zahlen publizieren. Ein guter, positiver Public Domain Data Loop.

**Comment by zdavatz** [comment]
> Hallo Zeno, was möchtest du mit welchem Ziel miteinander vergleichen?

Gute Frage. Ich würde sie aber auf jeden Fall sofort täglich abspeichern. @baryluk please save the XLSX file (PDF ist not so important AFAICT). Only save the file if the file size changed.

**Comment by baryluk** [comment]
> > Can't open at the moment, because my libreoffice is crashing (not a fault of the document).
> 
> You are archiving the PDF, better archive the XLSX. ;) See link above.

I am archiving both.

**Comment by zukunft** [comment]
Aus der Differenz von zwei Tagen könnte man die Daten des BAG von der "Tage der Probenentnehma" auf das "Tag des positiven Tests" umrechnen.

**Comment by baryluk** [comment]
Automatic extraction tool in progress:

We still need extraction, because the xlsx doesn't have historical data per-canton.

But it is a very useful data.

```
$ xlsx2csv -a 200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx 
-------- 1 - COVID19 Epikurve
"Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,
Quelle: BAG/MT,,,

Abbildung 1: Fallzahlen seit Einführung der Meldepflicht für COVID-19 in der Schweiz und Fürstentum Liechtenstein,,,

Falldatum,Bestätigte Fälle,,
02-24-20,2,,
02-25-20,1,,
02-26-20,12,,
02-27-20,11,,
02-28-20,10,,
02-29-20,15,,
03-01-20,12,,
03-02-20,31,,
03-03-20,32,,
03-04-20,60,,
03-05-20,59,,
03-06-20,73,,
03-07-20,50,,
03-08-20,63,,
03-09-20,183,,
03-10-20,200,,
03-11-20,313,,
03-12-20,325,,
03-13-20,413,,
03-14-20,420,,
03-15-20,316,,
03-16-20,997,,
03-17-20,973,,
03-18-20,1146,,
03-19-20,846,,
03-20-20,1125,,
03-21-20,680,,
03-22-20,520,,
03-23-20,835,,
03-24-20,41,,
Total,9764,,
-------- 2 - COVID19 Fälle Geschlecht Alter
"Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,,,,,,,,
Quelle: BAG/MT,,,,,,,,,,

Abbildung 2: Inzidenz von COVID-19 pro 100'000 Einwohner nach Alter und Geschlecht seit Einführung der Meldepflicht in der Schweiz und Fürstentum Liechtenstein,,,,,,,,,,
,,,,,,,,,,

,Weiblich,,,Männlich,,,Fehlend,Total,,
Altersklasse,Anzahl Fälle,%,Inzidenz/100'000,Anzahl Fälle,%,Inzidenz/100'000,Anzahl Fälle,Anzahl Fälle,%,
0 - 9,21,0.4,5.0,25,0.5,5.6,3,49,0.5,
10 - 19,138,2.8,33.7,113,2.4,26.0,8,259,2.7,
20 - 29,637,13.1,123.2,443,9.6,82.0,33,1113,11.4,
30 - 39,732,15.1,120.8,610,13.2,99.0,59,1401,14.3,
40 - 49,830,17.1,137.5,717,15.5,117.8,42,1589,16.3,
50 - 59,1018,21.0,158.8,1025,22.2,157.8,62,2105,21.6,
60 - 69,554,11.4,115.5,724,15.7,157.4,31,1309,13.4,
70 - 79,460,9.5,120.6,541,11.7,164.0,32,1033,10.6,
80+,452,9.3,163.2,406,8.8,240.6,19,877,9.0,
fehlend,12,0.2,,16,0.3,,2,30,0.3,
Total,4854,100.0,,4620,100.0,,291,9765,100.0,

,,,,,,,,,,
-------- 3 - COVID19 Kantone
"Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,
Quelle: BAG/MT,,,

Abbildung 3: Kantonale Verteilung der Anzahl COVID-19 Fälle seit Einführung der Meldepflicht in der Schweiz und dem Fürstentum Liechtenstein: Anzahl bestätigter Fälle ,,,
,,,

Kanton,Bestätigte Fälle,Inzidenz/100'000,
AG,272,40.1,
AI,4,24.8,
AR,31,56.1,
BE,571,55.2,
BL,342,118.7,
BS,501,257.2,
FL,51,132.9,
FR,251,78.8,
GE,924,185,
GL,37,91.6,
GR,316,159.30000000000001,
JU,75,102.2,
LU,211,51.5,
NE,181,102.3,
NW,40,92.5,
OW,25,66.099999999999994,
SG,227,44.7,
SH,34,41.5,
SO,105,38.4,
SZ,89,55.9,
TG,77,27.9,
TI,1343,380.1,
UR,24,65.900000000000006,
VD,2170,271.5,
VS,579,168.3,
ZG,48,37.799999999999997,
ZH,1147,75.400000000000006,
Total ,9675,,

Bei den Gesamtzahlen in dieser Tabelle kann es zu Abweichungen kommen. Die Gründe sind fehlende Kantonssangaben.,,,
```

**Comment by ebeusch** [comment]
> Hallo Zeno, was möchtest du mit welchem Ziel miteinander vergleichen?

Ich denke, es wäre sicher mal interessant, um zu schauen wie gross die Gaps sind zwischen hier vs. BAG sind, und ob/wie schnell sich diese schliessen?

**Comment by zukunft** [comment]
@baryluk könnte das script auch das PDF von Genf archivieren? Siehe #180 
Ich denke, auch da müssen wir die "Tage der Probenentnehma" auf das "Tag des positiven Tests" Umrechnung machen.

**Comment by zdavatz** [comment]
> @baryluk könnte das script auch das PDF von Genf archivieren? Siehe #180
> Ich denke, auch da müssen wir die "Tage der Probenentnehma" auf das "Tag des positiven Tests" Umrechnung machen.

I think it is easier to archive PDFs using github actions. Makes much more sense.

**Comment by zdavatz** [comment]
> > Hallo Zeno, was möchtest du mit welchem Ziel miteinander vergleichen?
> 
> Ich denke, es wäre sicher mal interessant, um zu schauen wie gross die Gaps sind zwischen hier vs. BAG sind, und ob/wie schnell sich diese schliessen?

Ja, das möchten wir gerne machen, siehe https://github.com/zdavatz/covid19_ch/issues/20

**Comment by zdavatz** [comment]
> Automatic extraction tool in progress:
> 
> We still need extraction, because the xlsx doesn't have historical data per-canton.
> 
> I also don't see deceased numbers.
> 
> But it is a very useful data.
> 
> ```
> $ xlsx2csv -a 200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx 
> -------- 1 - COVID19 Epikurve
> "Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,
> Quelle: BAG/MT,,,
> 
> Abbildung 1: Fallzahlen seit Einführung der Meldepflicht für COVID-19 in der Schweiz und Fürstentum Liechtenstein,,,
> 
> Falldatum,Bestätigte Fälle,,
> 02-24-20,2,,
> 02-25-20,1,,
> 02-26-20,12,,
> 02-27-20,11,,
> 02-28-20,10,,
> 02-29-20,15,,
> 03-01-20,12,,
> 03-02-20,31,,
> 03-03-20,32,,
> 03-04-20,60,,
> 03-05-20,59,,
> 03-06-20,73,,
> 03-07-20,50,,
> 03-08-20,63,,
> 03-09-20,183,,
> 03-10-20,200,,
> 03-11-20,313,,
> 03-12-20,325,,
> 03-13-20,413,,
> 03-14-20,420,,
> 03-15-20,316,,
> 03-16-20,997,,
> 03-17-20,973,,
> 03-18-20,1146,,
> 03-19-20,846,,
> 03-20-20,1125,,
> 03-21-20,680,,
> 03-22-20,520,,
> 03-23-20,835,,
> 03-24-20,41,,
> Total,9764,,
> -------- 2 - COVID19 Fälle Geschlecht Alter
> "Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,,,,,,,,
> Quelle: BAG/MT,,,,,,,,,,
> 
> Abbildung 2: Inzidenz von COVID-19 pro 100'000 Einwohner nach Alter und Geschlecht seit Einführung der Meldepflicht in der Schweiz und Fürstentum Liechtenstein,,,,,,,,,,
> ,,,,,,,,,,
> 
> ,Weiblich,,,Männlich,,,Fehlend,Total,,
> Altersklasse,Anzahl Fälle,%,Inzidenz/100'000,Anzahl Fälle,%,Inzidenz/100'000,Anzahl Fälle,Anzahl Fälle,%,
> 0 - 9,21,0.4,5.0,25,0.5,5.6,3,49,0.5,
> 10 - 19,138,2.8,33.7,113,2.4,26.0,8,259,2.7,
> 20 - 29,637,13.1,123.2,443,9.6,82.0,33,1113,11.4,
> 30 - 39,732,15.1,120.8,610,13.2,99.0,59,1401,14.3,
> 40 - 49,830,17.1,137.5,717,15.5,117.8,42,1589,16.3,
> 50 - 59,1018,21.0,158.8,1025,22.2,157.8,62,2105,21.6,
> 60 - 69,554,11.4,115.5,724,15.7,157.4,31,1309,13.4,
> 70 - 79,460,9.5,120.6,541,11.7,164.0,32,1033,10.6,
> 80+,452,9.3,163.2,406,8.8,240.6,19,877,9.0,
> fehlend,12,0.2,,16,0.3,,2,30,0.3,
> Total,4854,100.0,,4620,100.0,,291,9765,100.0,
> 
> ,,,,,,,,,,
> -------- 3 - COVID19 Kantone
> "Daten des Coronavirussituationberichts, Stand 25/03/2020, 08:15 Uhr",,,
> Quelle: BAG/MT,,,
> 
> Abbildung 3: Kantonale Verteilung der Anzahl COVID-19 Fälle seit Einführung der Meldepflicht in der Schweiz und dem Fürstentum Liechtenstein: Anzahl bestätigter Fälle ,,,
> ,,,
> 
> Kanton,Bestätigte Fälle,Inzidenz/100'000,
> AG,272,40.1,
> AI,4,24.8,
> AR,31,56.1,
> BE,571,55.2,
> BL,342,118.7,
> BS,501,257.2,
> FL,51,132.9,
> FR,251,78.8,
> GE,924,185,
> GL,37,91.6,
> GR,316,159.30000000000001,
> JU,75,102.2,
> LU,211,51.5,
> NE,181,102.3,
> NW,40,92.5,
> OW,25,66.099999999999994,
> SG,227,44.7,
> SH,34,41.5,
> SO,105,38.4,
> SZ,89,55.9,
> TG,77,27.9,
> TI,1343,380.1,
> UR,24,65.900000000000006,
> VD,2170,271.5,
> VS,579,168.3,
> ZG,48,37.799999999999997,
> ZH,1147,75.400000000000006,
> Total ,9675,,
> 
> Bei den Gesamtzahlen in dieser Tabelle kann es zu Abweichungen kommen. Die Gründe sind fehlende Kantonssangaben.,,,
> ```
It is the very first file they published yesterday. ;)

**Comment by metaodi** [comment]
Closing this, see #210

**Comment by zukunft** [comment]
Was zum Beispiel interessant ist, dass es für den 19.3. vom 26.3. auf den 25.3. eine Abnahme um 10 gegeben hat. Möglich, dass diese Fälle korrigiert und auf einen anderen Tag legt wurde. Oder das BAG oder einzelne Kantone reporten die geheilten Fälle nicht mehr, sondern nur die aktiven Fälle. Ich denke, mann sollte jetzt bei den Kantonen nachfragen, was für Zahlen sie genau publizieren. Da gibt es offensichtlich Unterschiede.

**Comment by zdavatz** [comment]
Am Ende hat der Bund am meisten Info.
