### ISSUE TITLE
FR Disctricts: week 29 not updated

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1853]
The cases for week 29 are online (https://www.fr.ch/de/gesundheit/covid-19/coronavirus-statistik-ueber-die-entwicklung-im-kanton) but missing in the csv.

**Comment by maekke** [comment]
Should hopefully be updated again with #1852

**Comment by balzamas** [comment]
This worked, but this week again nothing happened and it seems to me that they once again updated the layout with odd columns ("-7", "-14" etc)
But they have a csv online with daily data, is that new?
https://www.fr.ch/de/document/422471

**Comment by balzamas** [comment]
Broye was imported (8/29), but the other districts failed (last record 8/16).

**Comment by maekke** [comment]
@balzamas with #1886 and #1887 things should (hopefully) be working again. Please let me know, if something is still broken!

**Comment by balzamas** [comment]
I will check next week after the next update, thank you!

**Comment by balzamas** [comment]
It worked, thank you @maekke 

https://twitter.com/CovidlawsStats/status/1442472805656928256?s=20
