### ISSUE TITLE
Avoid double counting

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#187]
To avoid double counting I suggest a definition of the reporting canton. For practical reasons I guess the cases are reported in the canton where they are in hospital or at home, which is usually identical with the "Wohnsitzkanton". 
But assume the case the a person lives in Zurich, but has been in Ticino for vacation and gets there into the hospital. This person would most likely be reported in Ticino, but latest if he/she dies, Zurich gets involved. 
To solve this, I suggest that we add to the "fallzahlen_kanton_alter_geschlecht" files an column "place_of_registration" which is supposed to be filled if a person gets the virus in another kanton than his/her "Erstwohnsitzkanton".

**Comment by jb3-2** [comment]
We face a similar issue in the canton_total files, see #193.

**Comment by zukunft** [comment]
Answers are in #238

**Comment by jb3-2** [comment]
I think we can close this issue for now and continue working on it in #238 - agree?

**Comment by zukunft** [comment]
Agreed.
