### ISSUE TITLE
Daten zu Alter und Geschlecht

### ISSUE THREAD

**Issue by TheCharlatan** [openZH/covid_19#188]
DIe `fallzahlen_kanton_alter_geschlecht_csv` scheinen nicht weitergeführt worden zu sein, ich nehme mal an, weil man unmöglich einzelne Fälle so detailiert aufnehmen kann. Ein Histogram in Altersklammern wäre jedoch interessant. Kann man diese Daten noch einholen?

**Comment by zdavatz** [comment]
Nimm einfach das XLSX vom BAG: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

im obigen File sind die Geschlechter drinnen.

**Comment by TheCharlatan** [comment]
Ich hätte vielleicht hinzufügen sollen, dass ich sie weiterhin gerne nach Kantonen aufgeteilt hätte.

**Comment by zdavatz** [comment]
wo den im XLSX vom Bund? Die kantonalen Zahlen sind hier: https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv alles nach Kanton aufglistet. Ein File pro Kanton.

**Comment by TheCharlatan** [comment]
Genau, in den kantonalen Tabellen wäre die Aufteilung in Alterklammern durchaus interessant.

**Comment by zukunft** [comment]
Die meisten Kantone haben in der Tat nach ein paar Tage aufgehört dies Daten zu publizieren. Nachdem jetzt aber die täglichen updates automatisch laufen, sollte man dies aber wohl wieder angehen. Um Doppelzählungen zu unterbinden und zur Datenvalidierung. Aber dafür macht es wohl nicht Sinn über die normalen Internetseiten der Kantone zu gehen. Vielmehr wäre eine direkte Dateneinlieferung wohl sinnvoll. Weiss jemand mal einen Kanton, mit dem man einen Prototyp starten könnte?

**Comment by andreasamsler** [comment]
ZH wird Publikation wieder aufnehmen in Kürze ..

**Comment by zdavatz** [comment]
und hoffentlich auch die Daten vom Bund.

**Comment by zukunft** [comment]
Super. Danke für das Engagement.

**Comment by jb3-2** [comment]
BS Zahlen zu den verstorbenen nach Alter und Geschlecht sind nun hier zu finden: https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Fallzahlen_Kanton_BS_alter_geschlecht.csv

**Comment by jb3-2** [comment]
Ich schliesse dieses Issue für den Moment.
