### ISSUE TITLE
AG-Scraper: daily cases instead of totals?

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1880]
There seems to be an issue with the AG-scraper: ncumul_conf seems to be daily changes instead of totals
<img width="726" alt="image" src="https://user-images.githubusercontent.com/17248257/133081887-74a5e3f8-a8d1-47a2-bca2-66fd091b63bf.png">

**Comment by andreasamsler** [comment]
Thanks für your message. We have informed our contact in AG about the incongruence of their data source: 
https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/daten_excel/Covid-19-Daten_Kanton_Aargau.xlsx

**Comment by andreasamsler** [comment]
AG's answer: "Danke für den Hinweis. Das wird heute korrigiert."

**Comment by andreasamsler** [comment]
Fixed by AG. Resolved.
