### ISSUE TITLE
Hospitalisation data doesn't match data from covid19.admin.ch

### ISSUE THREAD

**Issue by seabbs** [openZH/covid_19#1888]
Firstly, thanks for the great work on this data source! 

We currently source it as one of our supported datasets in the `covidregionaldata` R package (see [here](https://epiforecasts.io/covidregionaldata/reference/Switzerland.html)). A contributor/colleague who helps run the [ECDC forecasting hub](https://covid19forecasthub.eu) and is trying to integrate hospitalisation forecasts recently flagged a significant mismatch (https://github.com/epiforecasts/covidregionaldata/issues/412) between your data and the hospitalisation data sourced from [covid19.admin.ch]( https://www.covid19.admin.ch/en/overview). Do you have any idea what might be driving this as we are not sure which data source to now use for Switzerland and/or if we need to support both. 

Thanks, 

Sam

**Comment by andreasamsler** [comment]
Hi @seabbs 

Hospitalisation data are a tricky thing. I am sharing with you what we - to the bet of our knowledge - know about it regarding Switzerland (as a whole) and the Canton of Zurich (in particular).

The data which is available via covid19.admin.ch originates from a system run by the KSD (https://www.vtg.admin.ch/de/organisation/astab/san/ksd/spitalkapazitaeten.html). The system was built and is designed for short-term events, like e.g. a plane crash, when first responders/emergency actors need to be able to assess quickly where they can transport patients to according to their status resp. medical needs. Medical institutions are required to update their capacities in that system once a day (as far as I know).

During the pandemic the system has proven to not be fully suitable for a long term situation like the present one, and flexible enough to cover e.g. additional capacities. Those are two reasons why certain Cantons, like e.g. Zurich, began to collect data independently form the KSD-System. In the case of the Canton of Zurich that data is more accurate in terms of time and completeness, that the one for Zurich being reported from the KSD. What's the status for other Cantons in this regard, I cannot assess. I can only state, that in our repository we make openly accessible the data which each Canton is making public on its website. In some cases that's the KSD data about their Canton, in others it's data from their own collections.

Hope this helps, best
Andreas
