### ISSUE TITLE
Empty lines in COVID19_Belegung_Intensivpflege.csv

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1889]
There are new hospitals included in the https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_zh/COVID19_Belegung_Intensivpflege.csv file, but they include no data besides the names.

It is:
Kinderklinik Kantonsspital Winterthur
and
Kinderklinik Stadtspital Triemli

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/17248257/135319495-9b3a000f-3abf-4650-9d53-983ea6d6a157.png">

**Comment by andreasamsler** [comment]
Hi @gmacauda, could you look into this, and state, if sth. needs to be done? Thanks, a

**Comment by gmacauda** [comment]
Those shouldn't be there. We'll take them out.
Thanks  @rsalzer
