### ISSUE TITLE
Bug: Wrong values for Valais disctricts in Week 42

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1900]
In the csv, the following districts have a 0 new cases in wek 42, even thought there are new ones in the source pdf:

Goms
Raron  
Sierre  
Visp  
St-Maurice  
Monthey   
Martigny

Source document:
https://www.vs.ch/documents/6756452/7008787/2021%2010%2027%20-%20Synthese%20COVID-19%20Woche42

**Comment by balzamas** [comment]
Same in Week 43

**Comment by maekke** [comment]
Should be fixed with #1901

**Comment by balzamas** [comment]
Lovely thank you!
