### ISSUE TITLE
Valais Week 46 not loaded

### ISSUE THREAD

**Issue by balzamas** [openZH/covid_19#1907]
It's groundhog day again, the municipality data from Valais is not imported. Powerpoint-to-PDF ftw

Source Week 46:
https://www.vs.ch/documents/6756452/7008787/2021%2011%2024%20-%20Synthese%20COVID-19%20Woche46

**Comment by maekke** [comment]
Should be fixed with https://github.com/openZH/covid_19/commit/78108e5b5b56c377f52ea94e42c21f5efbe97502 / https://github.com/openZH/covid_19/commit/d7daa77bbafe5e23b931cbf3f8eab445b56cb32c
