### ISSUE TITLE
Scraper for SG does not catch hospitalisations anymore

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#1912]
The last update was on November 23th. Cases and deceased numbers seem to work though.
See: https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_SG_total.csv

**Comment by maekke** [comment]
Thanks for the heads up, this should be fixed with https://github.com/openZH/covid_19/commit/69b499f3fab2d3466d65a2b59760c47045721bdc
