### ISSUE TITLE
Date cases Geneva

### ISSUE THREAD

**Issue by dkoltg** [openZH/covid_19#1959]
Hi, there seems to be a problem with the case numbers from Geneva. Thanks for having a look at it.

**Comment by andreasamsler** [comment]
After a quick check of the data source: It seems to me that GE has changed from daily to cumulative weekly values. 

We do not include weekly cumulative values as an indicator in our repository.

Measures:
- We reset the GE data to the status of the penultimate update: https://github.com/openZH/covid_19/commit/b5a8746e4a614b540a23b78a4bd313172e92cd64
- We pause the GE scraper and thus the updating of the GE data until further notice.

.cc @rsalzer

**Comment by andreasamsler** [comment]
What do you think about the measures taken, @maekke @metaodi ?

**Comment by andreasamsler** [comment]
Is there a relation to https://github.com/openZH/covid_19/commit/ec50698e0a95a7ef696f1c2eb22fe7d0c5c9cf0a, @maekke ?

**Comment by g-bar** [comment]
@andreasamsler Daily cases are being reported here (https://infocovid.smc.unige.ch/session/dda26a50cf8df3ee0bb0b4a3a712ebf2/download/download_table_cas_deces_csv?w=)

**Comment by dkoltg** [comment]
Thanks for solving the problem so quick :)

**Comment by maekke** [comment]
@andreasamsler the page was updated and https://github.com/openZH/covid_19/pull/1958 has the changes to the scraper.
It looks to me that their time series is in the wrong order (I didn't spot it for the cases, but for the deaths).

**Comment by dkoltg** [comment]
Hi, there seems to be that the same as 22 ago happened when having a look at the CH-total. Could you check that? Thanks in advance :)

**Comment by andreasamsler** [comment]
Thanks @dkoltg, I am checking ..

**Comment by andreasamsler** [comment]
If we want to continue an updated time series for GE from 2022-03-22 in our repo, we need an additional process for GE that puts the time series of the source CSV in reverse order, i.e. oldest date on top .. latest date at the bottom.

I reordered the time series now manually, updated the CSV in our repo once, and paused the GE scraper again.

**Comment by andreasamsler** [comment]
Couldn't find an e-mail contact of the 'Service du médecin cantonal' (SMC), responsible for https://infocovid.smc.unige.ch

I'll leave it at that.

**Comment by dkoltg** [comment]
Thank you for your efforts

**Comment by maekke** [comment]
@andreasamsler it looks to me, that the time series in https://infocovid.smc.unige.ch/ was corrected. Could you please double check that? Thanks in advance!

**Comment by andreasamsler** [comment]
Thanks @maekke, checking without running the scraper is too cumbersome for me, bc the issues were manifold. I therefore re-started the GE scraper, and we will see what happens ...

**Comment by andreasamsler** [comment]
There's an
`Error: Row 4: cumulative field ncumul_conf: 0 < 5`
according to https://github.com/openZH/covid_19/runs/6253766583?check_suite_focus=true

**Comment by andreasamsler** [comment]
Drop from >300 to ~80 hospitalisations from 2022-04-29 to 2022-04-30 is strange. Since https://github.com/openZH/covid_19/issues/1959#issuecomment-1102405018, we'll leave it at that.

**Comment by andreasamsler** [comment]
Double checked; looks valid now.
