### ISSUE TITLE
Contact FL (Principality of Liechtenstein) to provide more structured info daily

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#196]
Right now, information is scattered in random PDFs and videos on: https://www.regierung.li/coronavirus

Optimally the information about number of confirmed cases would be directly on apage.

Possible contacts:

Coronavirus:
```
Allgemeine Fragen                      
T+423 236 76 82 - Montag-Freitag; Bürozeiten
```

```
Presse / Medien - Kontakt

Information und Kommunikation der Regierung
Peter-Kaiser-Platz 1
9490 Vaduz
Fürstentum Liechtenstein
Telefon: +423 236 67 23
email: office at regierung dot li

Medien- und Interviewanfragen:
email: office at regierung dot li
```

Good exemplary formats:
  * https://www.zg.ch/behoerden/gesundheitsdirektion/amt-fuer-gesundheit/corona  (right side box)
  * https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948  (last line in Allgemeine Informationen section)
  * https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/Seiten/Start.aspx

that would be most clear and easy to use.

**Comment by zukunft** [comment]
I will write an email.

**Comment by baryluk** [comment]
@zukunft Much appreciated.

**Comment by baryluk** [comment]
Anything heard back?

**Comment by zukunft** [comment]
Not yet.

**Comment by zukunft** [comment]
I tried another email address .. I will call tomorrow, if I still have no reaction.

**Comment by zukunft** [comment]
FL does not want to change the format at the moment. They will continue to report daily at 17:00 on www.regierung.li/coronavirus. Like ZG the numbers are domicile based, not current location / hospital based

**Comment by baryluk** [comment]
Good to know. Fortunately the numbers for FL are low, and it is only of few exceptions, so it is not a huge burden to look them up.

Thanks Timon @zukunft for updating csv files manually :)

**Comment by metaodi** [comment]
Closing this for now
