### ISSUE TITLE
CSVs with indicators of all Cantons combined haven't been generated after 2022-04-12

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#1961]
Affected:
- https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total_v2.csv
- https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv

Measures taken:
- manually run Validate CSV #8120
- analysing issues

**Comment by andreasamsler** [comment]
Issue:
- https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_SO_total.csv

Analysis:
- Error in Row 531: cumulative field ncumul_conf: 108915 < 109485

Measures taken:
- Invalid value in Row 531 manually deleted
- manually run Validate CSV #8121

**Comment by andreasamsler** [comment]
Measures taken:
- nanually run Run scrapers #44213

**Comment by andreasamsler** [comment]
According to
- https://www.githubstatus.com/incidents/p5zql65p615b
- https://www.githubstatus.com/incidents/vxvyrmy9w1vp
there were issues with GitHub Actions on April 12 and 13, which - according to the info above - should be resolved by now.

Measures:
- assess with tech squad, how to proceed.

**Comment by andreasamsler** [comment]
While the reason for this issue is not yet found, the ressource **for ZH only** was manually updated:
- https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_zh/COVID19_Fallzahlen_Kanton_ZH_total.csv

Commit details: https://github.com/openZH/covid_19/commit/b0088074cc4158bff748e3ed54b7ccb9b58e1e35

**Comment by metaodi** [comment]
Will have a look soon-ish

**Comment by metaodi** [comment]
@andreasamsler okay the most urgent problem is fixed now. The scraper can finally commit again and the combined CSV is generated and commited as well.

As you noticed, there are still some scrapers with errors, I will check them another time and see which of those can be fixed.

**Comment by amslera** [comment]
Many thanks @metaodi !

Further note:
Our initiative to adapt individual cantonal scrapers to ongoing changes to cantonal websites remains limited. Especially in cases where cantons do not provide data in a structured form.
