### ISSUE TITLE
Validate cummulative fields in CSVs

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#197]
Some fields like `ncumul_tested` are supposed to be cummulative. Add a simple validation to check if this number is either the same or greater than the previous number or empty.

**Comment by gaberoo** [comment]
Something like this?

https://github.com/gaberoo/covid_19/blob/validate_cumul/scripts/validate_csv.rb

The script checks all fields that start with `ncumul` for inconsistencies, i.e. the subsequent number is smaller than the previous one.

```
 ❯ ruby scripts/validate_csv.rb scripts/validate_csv_test.csv                                                                   
Error on line 1, canton BS, field ncumul_conf: 9 < 10
```

**Comment by metaodi** [comment]
Yes that looks good.

But unfortunately not all fields starting with `ncumul` are _actually_ cummulative ([see README](https://github.com/openZH/covid_19/blob/master/README.md#data-structure) for details). Can you create a PR with the updated script?

I'm anyways working on a "validation" workflow, so I'll include that there.

**Comment by gaberoo** [comment]
Gotcha. I’ll look into this in a bit.

**Comment by metaodi** [comment]
So the cummulative fields are:

- `ncumul_tested`
- `ncumul_conf`
- `ncumul_released`
- `ncumul_deceased`
