### ISSUE TITLE
ncumul_vent for Canton GE seems wrong

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#198]
You use this data for ncumul vent:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/17248257/77620719-46373c00-6f3b-11ea-9171-c9a248f381c4.png">

While it should be this one:
<img width="122" alt="image" src="https://user-images.githubusercontent.com/17248257/77620762-5ea75680-6f3b-11ea-8d6e-88f3c5e56b00.png">

ncumul_vent is always a subset of ncumul_icu. You can find the historized data here:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/17248257/77620831-87c7e700-6f3b-11ea-8fb5-f277c6b668fd.png">

**Comment by rsalzer** [comment]
Source: https://www.ge.ch/document/covid-19-situation-epidemiologique-geneve/telecharger

**Comment by rsalzer** [comment]
I corrected it ... and will make a PR

**Comment by rsalzer** [comment]
[https://github.com/openZH/covid_19/pull/199](url)

**Comment by zukunft** [comment]
And I guess, we need the "day taken" to "date reported" conversion to make the data of the cantons compatible.

**Comment by tlorusso** [comment]
merged. Thx @rsalzer. Closing this. Can you open a separate issue for the 'date reported' issue @zukunft ?
