### ISSUE TITLE
Question: Why not a simple JSON?

### ISSUE THREAD

**Issue by herbertvonkaramalz** [openZH/covid_19#209]
Why don't you directly generate a clear JSON document from the case numbers, which could be used for the display in apps and websites? Surely an automation would be easier for all users.

**Comment by zukunft** [comment]
I have started with a JSON conversion script to forward the data to wikidata, because for wikidata the item and property enrichment is needed. I paste later here a prototype of the format suggestion.

**Comment by zdavatz** [comment]
> Why don't you directly generate a clear JSON document from the case numbers, which could be used for the display in apps and websites? Surely an automation would be easier for all users.

Just build your own and reference it here. Or send a PR.

**Comment by baryluk** [comment]
@herbertvonkaramalz Can't you just read csv file?

**Comment by zdavatz** [comment]
> @herbertvonkaramalz Can't you just read csv file?

Javascript people like JSON ;)

**Comment by tlorusso** [comment]
@herbertvonkaramalz This repo focuses on data collection, thats why we exclusively offer csv, to keep thins as overseeable as possible. Everyone who wants to build an API or build jsons for reusage containing this data is free to do so. We've built a csv with all the cantonal data to make this easier : 

https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total.csv

As we welcome such efforts we gladly reference any valuable external resource in the Readme.

**Comment by rsalzer** [comment]
I create the json very simply with D3.js.
d3.csv(...) creates a json for you.

**Comment by grssnbchr** [comment]
@tlorusso Please keep the data format (CSV) ;-)
