### ISSUE TITLE
Discussion: Add missing cantonal data from the BAG-Excel

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#210]
The BAG has released an [excel](https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx) with data for the cantons.
We could use those case numbers for missing cantons (especially FR...)
What do you think?

**Comment by baryluk** [comment]
Duplicate: https://github.com/openZH/covid_19/issues/185

**Comment by rsalzer** [comment]
I am talking specifically about filling gaps in cantonal data with the BAG-data. I dont see a sense in using the data otherwise.

**Comment by zdavatz** [comment]
@rsalzer I think this is a good idea! We parse the XLSX from BAG every day for `FR` as long as they do not publish anyhting on their website. I also called them up today by phone.

**Comment by zdavatz** [comment]
I may also happen, that the better the Daten from BAG become, the less the cantons will publish. Maybe. Maybe also the opposite will happen and the Cantons will go into data-publication-competition with the federal government ;) -> That would be even better.

**Comment by tlorusso** [comment]
I think for the moment we should stick to providing a complementary but separate source from the BAG data, containing just the officialy published figures by the Cantons. What's your opinon on this @andreasamsler?

**Comment by zdavatz** [comment]
I am sure @baryluk could out put the numbers from the BAG XLSX in his terminal output too: https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt - XLSX format should stay the same otherwise I will complain to them.

**Comment by grssnbchr** [comment]
@tlorusso I second your opinion. Mixing up cantonal and federal sources is not a good idea at the moment, imho. The documentation of BAG data has been very sub-standard and I wouldn't want them to pollute this beautiful data set. That's also one of my main criticisms regarding corona-data.ch.

**Comment by rsalzer** [comment]
When I think about it ... you are actually right @grssnbchr 
It is just my urgent need to use actual data from FR :-)

**Comment by zdavatz** [comment]
> @tlorusso I second your opinion. Mixing up cantonal and federal sources is not a good idea at the moment, imho. The documentation of BAG data has been very sub-standard and I wouldn't want them to pollute this beautiful data set. That's also one of my main criticisms regarding corona-data.ch. There _must_ be a way to finally get data from FR directly.

still, comparing the data makes sense. It is the federal government.

**Comment by metaodi** [comment]
Compare the data, but this is imho outside the scope of this repo.

**Comment by zdavatz** [comment]
yes, that is why just show the data in the Scraper output.

**Comment by ebeusch** [comment]
If this discussion is mostly about FR, we can close this discussion now ;) see #129 
FR has published historic data. Finally.

**Comment by andreasamsler** [comment]
Thanks to everyone, we are continuing to stick to our approach to not mix Cantonal and BAG data.
