### ISSUE TITLE
Integrate BAG XLSX file into python scraper to compare cantonal with federal numbers

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#211]
@baryluk Can you please output the official cantonal numbers from the BAG XLSX here as well: https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt

Just add another column beside the number your are Python-Scraping from the cantons. Then we have straight comparison between the cantons and the federal government numbers. ;)

XLSX is here: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

Looking forward to this ;).

cc @AlexBobAlex

**Comment by baryluk** [comment]
Maybe. Probably in a separate file tho.

**Comment by metaodi** [comment]
Closing this, see #210

**Comment by zdavatz** [comment]
Not a smart move, to close this.
