### ISSUE TITLE
Consolidate scraper workflows

### ISSUE THREAD

**Issue by gaberoo** [openZH/covid_19#213]
Each canton now runs its own workflow. All cantons could be combined into a single workflow. This would simplify managing automated tasks.

**Comment by zdavatz** [comment]
good idea!

**Comment by baryluk** [comment]
Maybe yes. Maybe no. Having them separate do have advantages, in case of failures in some scrapers not being well isolated.

**Comment by metaodi** [comment]
it works quite well, I'm closing this for now.
