### ISSUE TITLE
GR scraper fails

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#217]
https://github.com/openZH/covid_19/actions/runs/63809393

**Comment by zdavatz** [comment]
GR scraper is not failing if you use the python script: 
`GR 2020-03-26T          373       9 OK 2020-03-26T14:31:30+01:00 https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/Seiten/Start.aspx`
https://github.com/zdavatz/covid_19/blob/master/scrapers/scrape_gr.sh

**Comment by baryluk** [comment]
Bash version indeed shows `Deaths: `. Python version works.

**Comment by zdavatz** [comment]
Python works veeeerryyyy well ;)
