### ISSUE TITLE
TI python scraper fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#220]
```
TI 2020-03-26T08:00    1401      67 OK 2020-03-26T14:54:38+01:00 https://www4.ti.ch/dss/dsp/covid19/home/
Error: Unknown date/time format: None
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 177, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 143, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: None
```
cc @baryluk

**Comment by baryluk** [comment]
Works for me just fine.

When it started failing for you?

**Comment by pedrodude** [comment]
I don't know much about scrapers but for Ticino there is more detail in the press releases (found here: https://www4.ti.ch/area-media/comunicati/) than on the COVID-19 page (https://www4.ti.ch/dss/dsp/covid19/home/).

The press releases appear to be structured consistently (titles and wording) and, if it helps, there's an RSS feed (of all updates, not just COVID-19 ones) here: https://www3.ti.ch/xml/rss/rss-comunicati.xml

**Comment by baryluk** [comment]
@zdavatz Your issue report is simply invalid. Please close it.

The AssertionError is not about TI, but NEXT line.

Clearly TI returned OK with results.

**Comment by baryluk** [comment]
@pedrodude That is good to know. Thanks.

This issue however is invalid, and should be closed.

**Comment by zdavatz** [comment]
Ok!
