### ISSUE TITLE
Expose extra (optional) data in scraper parser output

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#237]
Right now we only print confirmed cases and deaths (or `-` if not known). But in many scrapers we capture some extra information (like hospitalized, recovered, etc.).

We already are reading it in parser, but not exposing it out.

To not break existing tools, the best is to simply add a "new" parser, or a parser flag, that will then use a new format.

Possible, CSV with headers directly.

**Comment by metaodi** [comment]
Yes I was thinking the same, but I'm not yet sure about the format. Since the result is anyway parsed and put in SQLite currently, headers are not necessary. On the other hand, it would allows us to change the output again in the future.

**Comment by baryluk** [comment]
I just started working on it. I will try to make the output format easy to parse in other tools, but be expandable for our use cases.

**Comment by baryluk** [comment]
Would something like:

```
AG 2020-03-27T16:00     364       2 OK 2020-03-27T16:14:27+01:00 https://www.ag.ch/de/....jsp # Extra: ncumul_hosp=12,ncumul_ICU=10,ncumul_vent=8,ncumul_released=30
```

Maybe work? It would be still human readable, and easy to extract in tools (just some match on `Extra: ([^#]+)` plus `split` on `,` and `=`, and not brake existing tools.

I can update `add_db_entry.py` to work with this too.

**Comment by baryluk** [comment]
BTW. Are ncumul_ICU ncumul_vent actually cumulative, or instantaneous?

**Comment by baryluk** [comment]
Looks promising:

```
$ ./scrape_ge.sh | ./parse_scrape_output.py | SCRAPER_KEY=GE SCRAPER_SOURCE=test ./add_db_entry.py
{'date': '2020-03-27', 'time': '12:00', 'area': 'GE', 'tested': '', 'confirmed': 1924, 'hospitalized': 313, 'icu': 54, 'vent': '', 'released': '', 'deceased': 23, 'source': 'test'}
$ ./scrape_vd.sh | ./parse_scrape_output.py | SCRAPER_KEY=VD SCRAPER_SOURCE=test ./add_db_entry.py 
{'date': '2020-03-26', 'time': '', 'area': 'VD', 'tested': '', 'confirmed': 2532, 'hospitalized': 327, 'icu': '', 'vent': '', 'released': 148, 'deceased': 38, 'source': 'test'}
```
