### ISSUE TITLE
Improve data quality by harmonizing the reporting - "date of test" vs "date of result"

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#238]
It looks like GE is reporting based on the "date of test" whereas other cantons use the "date of result". At least it should be clarified, which canton uses which standard. And in a second step e.g. for GE the complete report should be saved on daily bases, so that numbers based both methods can be displayed.

**Comment by zukunft** [comment]
The Informationsdienst Kantonaler Krisenstab of BL has confirmed via email to use "date of result".

**Comment by zukunft** [comment]
"date of result" is used in ZG and FL.

**Comment by baryluk** [comment]
Could you make a commit / PR that summarized our understanding of this data for each canton? And what BAG is recommending for reporting?

`TIMING.md` maybe?

**Comment by tlorusso** [comment]
Thanks @zukunft , your research is truly valuable. I think its a good idea to create an overview over these differences @baryluk . We'll look into this shortly.

ZH relies on date of result and for cases on domicile.

**Comment by jb3-2** [comment]
BS uses "date of result", as I see from the press releases. Regarding domicile, I have created a pull request that clarifies which columns cover residents of a canton and which cover all cases irrespective of residence, see https://github.com/openZH/covid_19/pull/355, to be reviewed / merged by @tlorusso

**Comment by jb3-2** [comment]
@baryluk @zukunft Please let me know if I can be of any help in clarifying and documenting which cantons use which type of date (date of test vs. date of confirmation).

**Comment by zukunft** [comment]
I just receive from SO 

Diese Angaben sind schweizweit geregelt und sind überall gleichen.
Alle Antworten zu Ihren Fragen finden Sie in den einschlägigen Meldeverordnungen und den dazugehörigen Dokumenten beim BAG.

At least on some Kantons it seems that at least at the beginning this was not fully clear to all. And the question is, why the BAG reports with the "date of sample taking".
I have not yet asked AI, AR,GE, JU, TI,VD and VS. For AI, AR and VS I have the email ready.

**Comment by zukunft** [comment]
@baryluk The list of answers is getting longer. Should we create a file or page for the overview? This way I could add the link to my answers to the cantons, so that they can double check.
I suggest that we add this to "Cantonal / FL data ressources" in the readme. Sould I make a suggestion?

**Comment by tlorusso** [comment]
@zukunft that would be great :)

**Comment by tlorusso** [comment]
We're solving this by declaring differences in reporting in the sources repo: 

https://github.com/openZH/covid19_sources_caseNumbers

The information coming from the sources-file is integrated into the dashboard as well:

https://www.web.statistik.zh.ch/covid19_dashboard/#/

**Comment by zukunft** [comment]
I have seen the dashboard. Thanks for the great work.
