### ISSUE TITLE
REST-API in own repo

### ISSUE THREAD

**Issue by apfeuti** [openZH/covid_19#250]
I've created a REST-API to get the data collected by openZH. Data can be filtered by country (CH, FL), cantons and date. Figures for whole Switzerland are also available (totals over all cantons). Output is available in json and csv.

https://covid19-rest.herokuapp.com/
https://github.com/apfeuti/covid19-rest

**Comment by zukunft** [comment]
Thanks. Maybe have also a look here for future ideas: https://covidtracking.com/software/ and https://github.com/COVID19Tracking/covid-tracking-api . This seems to be a similar project.

**Comment by apfeuti** [comment]
Yes, they are similar, but seems to be dedicated to data of the US. There are many COVID19-Rest-APIs out there, most of them are based on data of https://github.com/CSSEGISandData/COVID-19 (Johns Hopkins University).

Maybe openZH can somehow provide their data per canton (area) to JHU? Currently they are reporting for Switzerland only one grand-total.
