### ISSUE TITLE
canton GE: cumulative values should not decrease

### ISSUE THREAD

**Issue by lcalmbach** [openZH/covid_19#253]
In the canton of GE, the number of deaths decreases between 2020-03-21 and 2020-03-22 from 10 to 9. if the series is truly cumulative, this is not possible. the value of 2020-03-21 should be verified and probably reduced to 9.

**Comment by metaodi** [comment]
I already opened an issue to validate the cumulative fields to avoid this in the future: #197

**Comment by metaodi** [comment]
In #316 the numbers for GE were fixed. And in #305 a validator script was merged, so that these situations should no longer happen.
