### ISSUE TITLE
Adapt JU Scraper to scrape ncumul_hosp, ncumul_ICU and deceased

### ISSUE THREAD

**Issue by tlorusso** [openZH/covid_19#256]
Currently, the JU scraper does only collect confirmed cases. Hospitalized and ICU cases as well as deceased (still empty) would be available as well:

https://www.jura.ch/fr/Autorites/Coronavirus/Accueil/Coronavirus-Informations-officielles-a-la-population-jurassienne.html

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_JU_total.csv

**Comment by metaodi** [comment]
Related to #237

**Comment by baryluk** [comment]
Looks like duplicate of https://github.com/openZH/covid_19/issues/146
