### ISSUE TITLE
TI scraper excludes ICU patients from ncumul_hosp

### ISSUE THREAD

**Issue by tlorusso** [openZH/covid_19#257]
TI: scraper incorrectly excludes ICU patients from ncumul_hosp, @SarahNadeau has fixed this manually today. The scraper should take the first value for ncumul_hosp, the second one reports the number of patients in regular hosiptalization (excluding ICU).

Example for 26.03.2020:
> Nelle strutture ospedaliere dedicate alla cura dei pazienti affetti dal virus sono attualmente ricoverate **358** persone: 298 in reparto e 60 in terapia intensiva, di cui 56 intubate.

Source:
https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187523&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=982795a2c13394282accc3a8506c9ba0

**Comment by metaodi** [comment]
Related to #237

**Comment by baryluk** [comment]
Actually, at the moment we only use https://www4.ti.ch/dss/dsp/covid19/home/ in the scraper. Rest of data is done manually.

I can add a secondary scrape in TI scraper, to try extract data from latest article listed on https://www4.ti.ch/area-media/comunicati/

**Comment by baryluk** [comment]
I started working on getting extra information (hospitalized, ICU, ventilated/intubated) for TI scraper.

**Comment by baryluk** [comment]
```
$ ./scrape_ti.sh 
TI
Downloading: https://www4.ti.ch/dss/dsp/covid19/home/
Scraped at: 2020-03-28T02:05:35+01:00
Date and time: 27 marzo 2020, ore 8.00
Confirmed cases: 1688
Deaths: 76
Downloading: https://www4.ti.ch/area-media/comunicati/
Downloading: https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187533&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=0f01b9fd5e63dbb0f6f5cec02aa32b40
Scraped at: 2020-03-28T02:05:37+01:00
Date and time: 27.03.2020 ore 08:00
Hospitalized: 386
ICU: 61
Vent: 51
```

ICU numbers are inclusive (they also include people intubated).

**Comment by baryluk** [comment]
Works today too:

```
$ ./scrape_ti.sh 
TI
Downloading: https://www4.ti.ch/dss/dsp/covid19/home/
Scraped at: 2020-03-28T18:40:20+01:00
Date and time: 28 marzo 2020, ore 8.00
Confirmed cases: 1727
Deaths: 87
Downloading: https://www4.ti.ch/area-media/comunicati/
Downloading: https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187538&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=736a7f1a780ed9bdb1d8e45f8a0326ff
Scraped at: 2020-03-28T18:40:21+01:00
Date and time: 28.03.2020 ore 08:00
Hospitalized: 385
ICU: 69
Vent: 60
$
```

and

```
$ ./scrape_ti.sh | ./parse_scrape_output.py 
TI 2020-03-28T08:00    1727      87 OK 2020-03-28T18:40:54+01:00 # Extras: ncumul_hosp=385,ncumul_ICU=69,ncumul_vent=60 # URLs: https://www4.ti.ch/dss/dsp/covid19/home/, https://www4.ti.ch/area-media/comunicati/, https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187538&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=736a7f1a780ed9bdb1d8e45f8a0326ff
```

So, stable enough.
