### ISSUE TITLE
intensive care

### ISSUE THREAD

**Issue by cybermax** [openZH/covid_19#260]
can one safely assume that on a specific day:
num_intensive_care = ncumul_ICU + ncumul_ICU_intub + ncumul_ICF + ncumul_vent

is this correct?

**Comment by tlorusso** [comment]
Hi @cybermax, `ncumul_ICU` should be the column containing the total number of patients in intensive care (with or without ventilation / incubation). This column is already available in the merged swiss file. The same stands for the `ncumul_vent`, which should contain the number of patients requiring ventilation. In a next step, we want to include the column for the intubated cases in all files as well (this column is available for selected Cantons only at the moment). We will make some changes shortly, so it might be better to wait before using the columns beyond the total ICU column.

We still need some feedback from the Cantons that report these numbers and what the definitions are, see : #215 

As soon as we are ready to make the needed changes we will comunicate this actively.

https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total.csv

**Comment by tlorusso** [comment]
A significant share of patients in ICUs appear to be intubated (or 'künstlich beatmet'):

Currently in AG 9/10, TI 51/61 , GE 48/52

So i ask myself how relevant it is to even include 'ncumul_vent' and 'ncumul_intub'  besides the 'ncumul_ICU' column in the merged Swiss file. If we can't get precise definitions of what is meant by 'künstlich beatmet' or 'intubato' in the different Cantons, we can't grant comparability and cannot judge if we should count cases as 'ncumul_vent' or 'ncumul_intub', or if the reported number contains both cases. 

One option would be to could exclude those detail-columns from the merged Swiss Dataset alltogether and just leave them in the Cantonal-files, while highlighting in the Readme, that only the columns in the Swiss file fulfill the criteria of good comparability. 

I'm still trying to get the definitions from the competent authorities... but i guess it will not be that easy.

However, i'm really not an expert in this domain, so i'd be very interested to hear your opionion on this @SarahNadeau .

**Comment by SarahNadeau** [comment]
To be fair, I am absolutely not an expert in this domain either! For now, I really like the idea of having the cantonal data as descriptive as possible and at the national level aggregating only the fields we are confident are directly comparable. This assumes that at least data from the same canton is comparable day-to-day and allows us to present everything the cantons make available.

More importantly for the long term, is it feasible to ask for changes in the data that is reported? E.g. can we ask the Krisenstäbe/ hospitals to adhere to particular definitions of ventilated and intubated patients? This question is going in the direction of whether the OGD team are just data scrapers or also involved in data generation.

**Comment by tlorusso** [comment]
Definitions i've received so far:

TI just reports intubated (as intubato)

ZH reports intubated and ventilated together (künstlich beatmet)

... further will follow.

**Comment by baryluk** [comment]
AFAIK. ncumul_ICU_intub (or ninst_ICU) and ncumul_vent are already included in ncumul_ICU.

**Comment by tlorusso** [comment]
Thx for tracking and contributing to this discussion on definitions @baryluk besides all the scraping / technical ones. Indeed, the total number of patients in ICU (ncumul_ICU) already gives a very good idea of how many patients need ventilation / intubation, as most of the ICU-cases do. However, we will try to clarify how to handle the additional information on how many ICU patients need which kind of ventilation in a consistent way within the next days (still waiting for some answers...).

**Comment by tlorusso** [comment]
After extensive research and having received feedback by several Cantons we have confirmation that the numbers they report focus on invasive ventilation. The figures seem thus to be consistent.

Shortly, we will adapt to this. The `intub` columns in the files for GE and TI will thus become obsolete, the respective values will be stored in the `ncumul_vent`-column. If selected Cantons will start reporting figures on non-invasive ventilation we can then still add an additional column in the Cantonal files. However, this seems not to be likely to happen at the moment.

@baryluk @metaodi @SarahNadeau

**Comment by baryluk** [comment]
@tlorusso That make sense. Thanks for a work on this.

This is really good to converge on common definitions. Do we have some place to track if reported ventilation numbers are inclusive of mechanical ventilation and non-invasive respiration aids for each canton?

**Comment by tlorusso** [comment]
Practice has been to ask whenever a Canton publishes data on this. So far those who report these numbers seem to count invasive-respiration aids. At this point we just mention in the definition in the Readme that the data is based on invasive ventilation. But if further Cantons start publishing we might turn to them as well to ensure that the data is comparable, if not we might have to create an overview and declare differences. @baryluk

**Comment by tlorusso** [comment]
i'll close this issue for now - we can reopen it if differences in counting show up.
