### ISSUE TITLE
Python Scraper OW fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#276]
Link seems to still be the same.

Link: https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962

New Text: `Bisher ist bei 37 Personen im Kanton Obwalden das Coronavirus nachgewiesen worden. Bereits genesene Personen sind in dieser Zahl ebenfalls enthalten (Stand: 27. März 2020).`

```OW 2020-03-27T            -       - FAILED 2020-03-27T18:30:11+01:00 https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962 # Errors: Missing cases. Confirmed cases is None```

**Comment by zdavatz** [comment]
https://www.web.statistik.zh.ch/covid19_dashboard/index.html#/

**Comment by baryluk** [comment]
There is already PR for this sent hour ago. Please check for PRs before opening issues if possible.

**Comment by zdavatz** [comment]
Sorry, closed. Sometimes you merge your PR into a separate branch and sometime into master. So `git remote show baryluk` will not always show me the fresh breads. ;)
