### ISSUE TITLE
Update history? e.g. VS hospitalizations

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#278]
Looks like VS has adjusted the number of hospitalizations of the last days. Should we also do the updates. I suggest yes, because most likely they have simply e.g. added the reports of another hospital.

**Comment by tlorusso** [comment]
My opinion : yes. If they officially correct the history (this is what they did, right?), we should too. What do you think about this @andreasamsler ?

**Comment by andreasamsler** [comment]
Hi Timon (@zukunft ), yes, we do that, if there are official sources with URLs, which we can attribute to the values. Do you have got a list of these sources already?

**Comment by zukunft** [comment]
E.g. for VS the urls are 
https://www.vs.ch/documents/6756452/7008787/Sit%20Epid%20-%20%C3%89tat%20Stand%2027.03.2020.pdf
and 
https://www.vs.ch/documents/6756452/7008787/Sit%20Epid%20-%20%C3%89tat%20Stand%2026.03.2020.pdf

The number of "COVID-19 hospitalisés" for the 24.03.2020 changed from 79 to 81. Small thing, but to be correct.

**Comment by metaodi** [comment]
Fixed with #622
