### ISSUE TITLE
Issue with GR data of today

### ISSUE THREAD

**Issue by grssnbchr** [openZH/covid_19#287]
The data introduced in this commit https://github.com/openZH/covid_19/commit/4f5784ac193e86a4b7bfe75179a2bcc5233f34fd seem to be corrupted, they are too low. As I can see, the canton has not published 2020-03-28 data yet. 

Maybe generally: Should there be an automatic check that refuses case numbers / deaths that are lower than the day before?

**Comment by zdavatz** [comment]
The data for GR as of 28.3.2020 is `409` and `9`. See Scraper output: https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt

**Comment by andreasamsler** [comment]
thanks, checking ..

**Comment by daenuprobst** [comment]
> Maybe generally: Should there be an automatic check that refuses case numbers / deaths that are lower than the day before?
IMO: Deaths yes, however, case numbers no, that would be a bit pessimistic, no?

**Comment by metaodi** [comment]
Yes, I'm on it #197

**Comment by metaodi** [comment]
@daenuprobst confirmed case numers are cumulative in the dataset, so the number must be at least as high as the day before.

**Comment by metaodi** [comment]
fyi: since #271 was resolved, we now have an additional JSON source for GR.
