### ISSUE TITLE
Bitte Files in den Ordnern unterscheiden

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#29]
Könnt Ihr bitte die Files in unterschiedlichen Ordner sammeln, Vorschlag:

* fallzahlen_kanton_total_csv -> für alle Updates. Ein File pro Kanton.
* fallzahlen_kanton_alter_geschlecht_csv -> für detailliertere Infos. Ein File pro Kanton.

Die Files in den Ordner sollten validiert sein, d.h. gleiche Anzahl Spalten, gleiche Spalten Titel.

**Comment by tlorusso** [comment]
Done. Bei den Total-Files ist es nun so, dass sie alle die ersten 11 Spalten gemeinsam haben. Bei vereinzelten Kantonen hat es zu hinterst aber noch zusätzliche Spalten (Infos die es nur für diese Kantone gibt). Die Alter / Geschlecht Files sind noch nicht harmonisiert.

**Comment by zdavatz** [comment]
Danke!

**Comment by zdavatz** [comment]
Lass mich wissen, wann ich `git pull` machen kann.

**Comment by zdavatz** [comment]
Als Referenz für unsere Karte. https://github.com/zdavatz/covid19_ch/issues/5
