### ISSUE TITLE
VD Scraper fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#290]
cc @baryluk 
```
VD - - - FAILED 2020-03-28T16:00:11+01:00
```

**Comment by metaodi** [comment]
Failed GitHub actions run: https://github.com/openZH/covid_19/runs/541865187?check_suite_focus=true

**Comment by zdavatz** [comment]
New Stats now seem to be here: https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/
