### ISSUE TITLE
AG scraper with wrong date

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#297]
Today the scraper added a new entry with the same numbers as yesterday. When checking [the website](https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp), these numbers were not there.

But the scraper code extracts the first entry in the timeline and then proceeds to get the first numbers on the page (in this case from yesterday). So they were erroneously assigned with todays date.

**Comment by fabian** [comment]
Looking into it.

**Comment by baryluk** [comment]
It looks like the code is not very smart, and captures numbers from different days.

The solution would be to find most recent article with numbers, then download only the one article, and parse it. We do similar thing  few other scrapers.
