### ISSUE TITLE
Missing data in `ncumul_released` field (should be carried forward)

### ISSUE THREAD

**Issue by Pseudomanifold** [openZH/covid_19#309]
Thanks for providing this service!

I saw that, contrary to the description of the data frame, the `ncumul_released` column is missing data for certain cantons (for example `AG`: the number increases to 4, but then no more data is being reported). I suggest forward-filling data or making a mention of this in the README.

Let me know if I can support this in any way!

**Comment by fabian** [comment]
Unfortunately AG stopped recording number of patients released on 19.03.2020 as instructed by BAG:

> Aarau, 19. März 2020 15.00 Uhr
> LAGEBULLETIN Nr. 15 Coronavirus (COVID-19)
> Gemäss der Weisung des BAG werden die Anzahl der Geheilten nicht mehr erfasst.

 https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200319_KFS_Coronavirus_Lagebulletin_15.pdf

**Comment by metaodi** [comment]
My understanding is, that if we put a number in a column, that number was communicated by a canton for that date. If there is no information (like for AG as @fabian mentioned), the field is empty.
We have a validation step, to ensure values only stay the same or increase for a the cumulative fields.

But I agree, this should be documented.

**Comment by Pseudomanifold** [comment]
Thanks for clarifying! This behaviour makes a lot of sense. Let me know if I can help in documenting it or related behaviours.

**Comment by baryluk** [comment]
Yes, to an extent filling the gaps is to be done by consumer of the files. If the row has some empty field, the consumer is free to use some previous rows to fill it up, with all the caveats of this approach. The data itself shouldn't be really filled / guessed, because it is not what the source is providing, and we would be giving a bad picture of what actually is going on.

**Comment by metaodi** [comment]
@Pseudomanifold please review #337, does that clarify things? Any feedback is appreciated.

**Comment by Pseudomanifold** [comment]
Yes, thanks a lot!
