### ISSUE TITLE
VS scraper fails

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#312]
[VS scraper currently fails](https://github.com/openZH/covid_19/runs/543415944?check_suite_focus=true):

```
Run the scraper...
Error: Not matched input line: VS 2020-03-29T            -      21 FAILED 2020-03-29T15:39:13+00:00  # URLs: https://www.vs.ch/de/web/coronavirus
# Errors: Missing cases. Confirmed cases is None
```

**Comment by zdavatz** [comment]
sees like it is in a PDF now. https://www.vs.ch/documents/6756452/7008787/Sit%20Epid%20-%20%C3%89tat%20Stand%2029.03.2020.pdf

cc @baryluk

**Comment by baryluk** [comment]
Not at the computer at the moment.

I suggest you call and also send email to bring  the up to date numbers
back to where they were.

**Comment by baryluk** [comment]
Actually looking into his pdf, i would say it is rather nice display and
analysis, and is helpful. Plus it allows for historical reference.

But direct current numbers and graphs were really nice before.

**Comment by baryluk** [comment]
@zdavatz , @metaodi off topic, but I also track most recent failed scrapers at this link: https://www.functor.xyz/covid_19/scrapers/outputs/latest_failures.txt  , just in case if you want to verify if the failure you are seeing, is just you or everybody ;)

**Comment by baryluk** [comment]
I will send a fix to VS in ~2 hours. It looks to be a rather easy. Anybody else want to grab it to code maybe? A scraper for GE could be a good example how to deal with PDFs.

**Comment by baryluk** [comment]
Actually current numbers are still available on the main site, with different format:

Aktuelle Situation im Kanton Wallis
```
29.03.2020: Derzeit gibt es 964 bestätigte Fälle von Coronavirus-Infektionen im Kanton. Insgesamt hat das Virus bisher den Tod von 21 Personen im Wallis verursacht. Eine Übersicht über die epidemiologische Lage im Wallis ist hier verfügbar. 
```

**Comment by baryluk** [comment]
Actually, the format is almost the same and should work with the current scraper. Looking into this.

**Comment by zdavatz** [comment]
thank you @baryluk

**Comment by baryluk** [comment]
Ok. Fix ready for merging.

I will still look into scraping the data from PDFs, as they contain also hour of a day, and ICU and intubation numbers.

**Comment by zdavatz** [comment]
> Ok. Fix ready for merging.
> 
> I will still look into scraping the data from PDFs, as they contain also hour of a day, and ICU and intubation numbers.

That would be supercool!
