### ISSUE TITLE
BS scraper adds old source url

### ISSUE THREAD

**Issue by jb3-2** [openZH/covid_19#321]
The BS Scraper seems to add an old source url instead of using the current url, see e.g. [here](https://github.com/openZH/covid_19/commit/8db54222e73c371f76d9134378b26a38f02c4721), were the scraper uses the url dating back from 27.3.2020 instead of the [url](https://www.coronavirus.bs.ch/nm/2020-tagesbulletin-coronavirus-621-bestaetigte-faelle-im-kanton-basel-stadt-gd.html) of today (30.3.2020). 

It's not such a big problem since I go and enhance the data everyday anyway, thereby replacing the old url with the correct one.

**Comment by metaodi** [comment]
The source is currently hardcoded, I'll look into getting the actual URL from the scraper.

**Comment by baryluk** [comment]
BS scraper should be extracting the latest URL and latest data correctly.

It gives me now: https://www.gd.bs.ch//nm/2020-tagesbulletin-coronavirus-621-bestaetigte-faelle-im-kanton-basel-stadt-gd.html  , which is the correct URL. Not sure why CVS got other URL.

**Comment by baryluk** [comment]
Oh. I see @metaodi . I see. It is not a problem with scraper, but with the workflow.

In `add_db_entry.py` we should do similar to what we do in `convert_parsed_to_csv.py`, and not use SCRAPE_SOURCE from environment.

**Comment by metaodi** [comment]
@baryluk exactly 😉 I'm on it. I anyway touch this code currently to support custom schemas (i.e. cantons with extra fields in their CSV).

**Comment by andreasamsler** [comment]
Same issue for BL. Thanks.

**Comment by baryluk** [comment]
@metaodi Great work Stefan! Thanks.
