### ISSUE TITLE
Released individuals TI

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#322]
TI: "Seit dem 28.03.2020 wurden 58 Personen aus den sanitären Einrichtungen entlassen."
Source: https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187546&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=1465eace9ac68357130a7327d0c9b8f9

**Comment by baryluk** [comment]
To be updated by hand I think. We will see if the daily bulletins stay consistent with providing this information.

**Comment by baryluk** [comment]
Yesterday (2020-03-30) it was saying:

> Dal 28.03.2020 sono state dimesse dalle strutture sanitare 58 persone. Questa informazione sarà da ora aggiornata quotidianamente.  

Today (2020-03-31) it is saying:

> Dall’inizio della pandemia sono state dimesse dalle strutture sanitarie 202 persone, 37 delle quali nelle ultime 24 ore. Questa informazione è stata recuperata sulla base di un’analisi retroattiva e sarà da ora aggiornata quotidianamente.

The data is there. Still unstable to scrape automatically.

Will wait one more day.

**Comment by tlorusso** [comment]
The infos regarding from the 2020-03-20 do just say "from the 28.03 on 58 people have been released", but we do not know how many on the 28. and how many on the 29. Also, in contrast to later press releases, it does not say how many from the beginning of the pandemic. However, based on this information, by doing some substraction, we could assume that until the 28.03.30 117 patients have been released. But as there is no official statement in which this number is confirmed - i'd say we better leave the entries before the 31.03 empty for now. 

Should i leave this open @baryluk or can we close?

**Comment by baryluk** [comment]
Let me write a provisional code to scrape this information from bulletins. It looks relatively stable.

Yesterday (2020-04-02):

> Dall’inizio della pandemia, sono state dimesse dalle strutture sanitarie 263 persone, 34 delle quali nelle ultime 24 ore.

Today (2020-04-03):

> Dall’inizio della pandemia sono state dimesse dalle strutture sanitarie 287 persone, 24 delle quali nelle ultime ventiquattro ore.  

and similar days before.
