### ISSUE TITLE
BAG reported complete wrong numbers today or they are now faster then the cantonal reporting.

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#323]
This is the total per today as of 13.05 
[latest.csv.zip](https://github.com/openZH/covid_19/files/4402543/latest.csv.zip)
https://www.functor.xyz/covid_19/scrapers/outputs/

<img width="613" alt="Bildschirmfoto 2020-03-30 um 14 09 39" src="https://user-images.githubusercontent.com/4953/77911018-66932d80-7290-11ea-9572-529a9f6ed1b2.png">

BAG reports 
<img width="884" alt="Bildschirmfoto 2020-03-30 um 14 14 01" src="https://user-images.githubusercontent.com/4953/77911204-b83bb800-7290-11ea-9ac2-6ea96ee0ce92.png">

If you ask me, BAG has a big reporting Error today.

<img width="1415" alt="Bildschirmfoto 2020-03-30 um 14 15 04" src="https://user-images.githubusercontent.com/4953/77911294-dc979480-7290-11ea-980e-fea9eff8ea43.png">

or they are a lot faster now counting the cases together.

**Comment by andreasamsler** [comment]
Dear @zdavatz, I don't see a reason, why you would post this in here. I would advise you to address these concerns - in a constructive manner (if I allow myself to suggest that) - to the respective data source. We are not playing counterstrike or alike here. We are filling a gap (as long as it is necessary), we are following an open approach, and we are offering an additional data source. Nothing more, nothing less.

**Comment by zdavatz** [comment]
Just comparing the numbers. But feel free to close the issue.

**Comment by zdavatz** [comment]
let me know what you think of this @cclauss
