### ISSUE TITLE
tagesanzeiger numbers: Do you know why they differ

### ISSUE THREAD

**Issue by fabiomariotti** [openZH/covid_19#334]
Hoi guys,
Thanks a lot for this effort and for everything!

I see in this link: 

https://interaktiv.tagesanzeiger.ch/2020/wuhan-schweiz/?fbclid=IwAR2eAwbDIMw9VmZ4ZEa7p8DvbF5PK4TiJDpGIwhmcEI404e0WquXV-Rhbls

Different data.

In particular the "recovered".

Do you you know what it is and why it does not match?

In the same line, it appears that here: 

https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Are communicated different numbers. I mean the difference is/might be just the time of the communication.

Do you have any information about this?

**Comment by fabiomariotti** [comment]
I just want to remark: Thanks!
The questions above are details compared to your effort.

**Comment by tlorusso** [comment]
1. The Tagesanzeiger calculates the «recovered» based on some assumptions (see notes below the visualizations). The Cantons don't report this numbers. A few Cantons report the number of people released from hospital or isolation. Thats the number we collect. 

2. I assume the source for the Swiss Case numbers in this Dashboard is the BAG.

If you're interested in the differences between the data sources:

https://observablehq.com/@republik/sars-cov-2-covid-19-data
