### ISSUE TITLE
should  non reported changes be updated to last known value?

### ISSUE THREAD

**Issue by lcalmbach** [openZH/covid_19#335]
In many time series, reported values are discontinued. This is particularly true for series with rare changes e.g. the number of deceased. e.g. for AG a number of deceased is reported until 2020-03-18. After that the BAG still provides daily reports but apparently no number of released patients. Would it not be safe to assume that the number of deceased has hence not changed and report the last known number since these numbers are cumulative? It's not a problem in time series where the user sees previous numbers and can connect the dots. However, I am building an application where cantons are compared in a bar chart where the bar chart represents a date. If no value is reported, the respective canton is missing from the plot, but we would actually know the minimum number of cases as being the last reported value. See example bar chart in www.calmbach:8501 (address sometime does not work from within a firewall). 

I suggest to continue the series of cumulative values with the last known value if no new value is reported. However, I understand if you prefer not to report any number not explicitly published b the BAG. In this case, would you consider it methodologically wrong to interpret missing values as a lack of change in plots and e.g. show the number of deceased as 4 for AG from 2020-03-19 to 2020-03-30? I would not want to use your data and then change it in a way you do not approve of.

**Comment by fabian** [comment]
Related to #309

**Comment by metaodi** [comment]
I'd argue that we report exactly what the cantons report. If you want to "assume" that a value has not changed, you're free to do so (and explain your methodology). But an empty value means that there is no data for this field on this date.

Note: this is my personal opinion, maybe @andreasamsler or @mmznrSTAT have a different take on this.
