### ISSUE TITLE
Issue with SO data today

### ISSUE THREAD

**Issue by JBeyel** [openZH/covid_19#336]
SO has updated the report on its cantonal site and is already updated on the site here. The cantonal report says that there are a total of 190 cases as of today which is the same number reported on 29.3. but in brackets it says that the total is a + of 6 cases compared to 29.3. Both information cannot be correct. Maybe someone can check that. I didn't find a short solution to contact the person that delivered the information.

**Comment by metaodi** [comment]
I quickly checked [archive.org their website on the 29.3.](https://web.archive.org/web/20200329080917/https://corona.so.ch/):

![so_2020-03-29](https://user-images.githubusercontent.com/538415/78025340-2ac49a80-735a-11ea-808a-2bd53d1ac134.png)

So this suggest that 190 was their actual value on the 29.3. (and +17 is consistent with the value 173 from the 28.3.).

So most probably the value of today should be higher or the +6 is wrong.

**Comment by metaodi** [comment]
I just checked their website again, they updated the number to 196.
