### ISSUE TITLE
NEW URL for VD data

### ISSUE THREAD

**Issue by jeanbrouille** [openZH/covid_19#341]
Hi, 

I'm caring about datas for vd. Please find the new url : https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/

where you can find datas uptodate.

BR
JR

**Comment by tlorusso** [comment]
Thx @jeanbrouille !

**Comment by tlorusso** [comment]
@jeanbrouille will the figures regarding the patients in instensive care units also be published on that site?

**Comment by metaodi** [comment]
We are currently consuming the datawrapper API of the website of VD, it seems the new URL still uses the same datawrapper source, so currently no change is needed on our side.

**Comment by stat1x** [comment]
If I search in the code of this repository I can find this URL 3 times here : https://github.com/openZH/covid_19/search?q=https%3A%2F%2Fwww.vd.ch%2Ftoutes-les-actualites%2Fhotline-et-informations-sur-le-coronavirus%2F&unscoped_q=https%3A%2F%2Fwww.vd.ch%2Ftoutes-les-actualites%2Fhotline-et-informations-sur-le-coronavirus%2F

**Comment by metaodi** [comment]
@stat1x true, I updated the SCRAPER_SOURCE so that the correct source is noted in the CSV.

**Comment by jeanbrouille** [comment]
@tlorusso "will the figures regarding the patients in instensive care units also be published on that site?" Yes new data coming up tomorrow.
