### ISSUE TITLE
ncumul_conf empty between 5.3.-11.3 despite sources available (TI)

### ISSUE THREAD

**Issue by tlorusso** [openZH/covid_19#343]
Have these values been omitted intentionally? It seems like just the sources have been added when those rows have been created. I think we should insert the values too.

Example (5.03.2020)

[> Allo stato attuale in Ticino si registrano 18 casi di persone risultate positive al Coronavirus. ](https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187385&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=a9ddddfae2c7446e5b856451e178a61a)

.. but there's no trace of this value in the data:

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_TI_total.csv

The same stands for the days following.

**Comment by metaodi** [comment]
I traced it back to it's original location here: https://github.com/openZH/covid_19/commit/0a237dea91a90120211f0cc81e8b020a33309d74

They were not added then and never updated since then. It seems to be an oversight.

**Comment by tlorusso** [comment]
Ok. Will add them tonight.

**Comment by baryluk** [comment]
@tlorusso Thanks Thomas for spotting the issue and providing the backfill of data! Cheers.
