### ISSUE TITLE
BE Scraper fails 

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#351]
```
BE -                      -       - FAILED 2020-03-31T17:30:02+02:00  # URLs: https://www.besondere-lage.sites.be.ch/besondere-lage_sites/de/index/corona/index.html # Errors: Missing date. Missing cases
```
cc @baryluk

**Comment by baryluk** [comment]
Looking into it. Table parsing failure. Some rows / columns changed again.

**Comment by zdavatz** [comment]
I may be easier if we just start parsing the XLSX file from BAG: 

https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/covid-19-datengrundlage-lagebericht.xlsx.download.xlsx/200325_Datengrundlage_Grafiken_COVID-19-Bericht.xlsx

if a parser fails.

**Comment by baryluk** [comment]
@zdavatz I will create a parser for the file. It is useful to have as a backup and cross-reference anyway.

**Comment by metaodi** [comment]
But as said before, we won't put the numbers from the BAG in this repo. It's meant as an alternative data source directly from the cantons. It's not about having _any_ number.

**Comment by zdavatz** [comment]
> @zdavatz I will create a parser for the file. It is useful to have as a backup and cross-reference anyway.

@baryluk Great!! And please output is as a separate file on functor.xyz. We are already parsing that file with [Javascript ](https://github.com/zdavatz/covid2019_ch_map/) ;) and building this [Map](https://twitter.com/zdavatz/status/1245057239578218498?s=20) in case you want a code reference and you like Javascript.

**Comment by baryluk** [comment]
Fix coming soon.
