### ISSUE TITLE
Number of tested people

### ISSUE THREAD

**Issue by Kuurusch** [openZH/covid_19#362]
It seams that there is no data about the number of tested people, is this so? What do you know about the amount of tests each day in switzerland? I hope this is fixed, otherwise it will be quite difficult do make reliable assumtions about the data! Normally you would need to normalize the positive tested cases with the amount of tests each day...

**Comment by zdavatz** [comment]
The number is in the PDF of BAG. See [this link](https://twitter.com/rob_salzer/status/1245032309486649346?s=20)

**Comment by andreasamsler** [comment]
In our repo we are strictly relying on data officially published by official sources from Cantons and FL. If they have reported data for ncumul_tested, we publish it, too. If not, we don't.

And once more, and again, we do not mix BAG data and data of Cantons & FL.
