### ISSUE TITLE
NE new data / correction of data

### ISSUE THREAD

**Issue by claudia013** [openZH/covid_19#364]
NE provides the case numbers in a PDF file since yesterday and the scraper doesn't pick up on that anymore. Further, they seem to have corrected all of the case numbers and added hospitalized, ICU and ventilated cases for most of March, so this data needs to be corrected / added. Thanks

**Comment by claudia013** [comment]
The NE scraper also reported an error (25min ago)
##[error]Process completed with exit code 1.

**Comment by andreasamsler** [comment]
I contacted NE about the correction of their data in retrospect, asking about what data we should rely on.

**Comment by metaodi** [comment]
For the failed scraper we have a separate issue: #357

**Comment by andreasamsler** [comment]
Will update retrospectively, and communicate changes publicly (Tweet).

**Comment by andreasamsler** [comment]
@simgraworldwide can you take care of this?

**Comment by janetzkoa** [comment]
NE has corrected the past 4-5 days of its data for confirmed cases and deaths. Our data might have to be corrected.

**Comment by baryluk** [comment]
I was just looking for ncumul_ICU for 2020-04-05 for NE, and in CSV file we have value 12:

```csv
2020-04-05,16:00,NE,,459,58,12,8,,26,https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.pdf
```

But in https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.pdf  in the table at the end I read 17.

My guess, is that you only count COVID-19-related ICUs? How? `max(icu_covid, icu_covid_non_tube + icu_covid_tube)`, `icu_total - icu_non_covid` ?

**Comment by janetzkoa** [comment]
NE has corrected the past 5-6 days of its data for confirmed cases and deaths. Our data might have to be corrected.

**Comment by baryluk** [comment]
@janetzkoa I would still like to know how to compute ncumul_ICU based on the pdf data.

**Comment by baryluk** [comment]
Is somebody going to take a look into this? The pdf published by Neuchâtel canton in the PDF, do keep changing, especially the deceased and confirmed cases, look to be changing retroactively.

**Comment by simgraworldwide** [comment]
We are still trying to get a hold of somebody who is responsible for the publication of the data in NE, I hope we can raise awareness and solve the issue sometime this week.

**Comment by tlorusso** [comment]
I guess we can close this @simgraworldwide ?
