### ISSUE TITLE
Fallzahlen VD changed from 16.3 to 30.3

### ISSUE THREAD

**Issue by JudithBouman2412** [openZH/covid_19#367]
VD changed their numbers for the hospitalization, intensive care and deceased from 16.3 to 30.3. https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/ 
These need to be updated.

**Comment by andreasamsler** [comment]
Will update retrospectively, and communicate changes publicly (Tweet).

**Comment by claudia013** [comment]
as far as i remember they changed the whole format of reporting case numbers, might be an issue for the scraper in general?

**Comment by metaodi** [comment]
No the scraper uses the API of their website, a PR (#368) to change to the new format was merged and everything should be fine the next time the scraper runs

**Comment by andreasamsler** [comment]
@simgraworldwide can you take care of this?

**Comment by metaodi** [comment]
Fixed with #609
