### ISSUE TITLE
Differences to official pub Canton NE

### ISSUE THREAD

**Issue by pnwscm60** [openZH/covid_19#385]
Just checked the publication from Canton NE https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.pdf

The data in this document shows differences to collected data by openZH. Should we check other cantons also for difs?

**Comment by andreasamsler** [comment]
Hi, are you relating to differences for today or yesterday (2020-04-02, 2020-04-01) or to differences for the days before? For the latter there's already #364 to be solved.

**Comment by pnwscm60** [comment]
Hallo Adrian

Sorry, diese Meldung nicht gesehen. Es geht um die vorherigen Daten, die weichen ja ziemlich deutlich ab.

Danke und Gruss

Markus
___________________________________________

Covid-19 geht uns alle an: Bleibt zu Hause, haltet Abstand und befolgt die Weisungen von Bund und Kanton!

Grafik zur Entwicklung ohne Massnahmen: https://ebpswiss.ch/animation.html <https://ebpswiss.ch/animation.html>
Seite Bundesamt für Gesundheit: https://www.bag.admin.ch/bag/de/home.html <https://www.bag.admin.ch/bag/de/home.html>
Aktuelle Fallzahlen: https://corona-data.ch <https://corona-data.ch/>
Patientenverfügung FMH (Kurzversion): https://www.fmh.ch/files/pdf23/fmh_pv_kv_2019_d.pdf <https://www.fmh.ch/files/pdf23/fmh_pv_kv_2019_d.pdf>

**Comment by andreasamsler** [comment]
Allright, it's already on the way to be fixed retrospectively. Thanks.
