### ISSUE TITLE
NW scraper adds ncumul_deceased = 0

### ISSUE THREAD

**Issue by fab-benz** [openZH/covid_19#399]

**Comment by baryluk** [comment]
And what is the issue?

That is not a bug.

**Comment by fab-benz** [comment]
I don’t know about the bug thing but I opened an issue cause I spotted today on the rsalzer overview that there was a 0 reported for deceased.
This was also in the NW.CSV and I concluded that the scraper likely also transfers 0 fo deceased, which should not be reported.
Does that make sense?

Best
--------------------
Fabienne Benz
fabienne.benz@env.ethz.ch<mailto:fabienne.benz@env.ethz.ch>
Integrative Biologie
Universitätsstrasse 16
8092
CHND31.1

On 3 Apr 2020, at 12:10, Witold Baryluk <notifications@github.com<mailto:notifications@github.com>> wrote:



And what is the issue?

That is not a bug.

**Comment by baryluk** [comment]
0 in deceased columns is correct.

https://www.nw.ch/gesundheitsamtdienste/6044  says explicitly 0 deceased as of 2020-04-02 16:00.
 
Not a bug.

In the CSV, if the field is empty, it usually means zero, and can be assumed zero, but more often than not it means data is unavailable or not explicitly reported. If the value is 0, that means we know it is zero.

**Comment by metaodi** [comment]
I agree, not a bug. It's actually the communicated value from NW.
