### ISSUE TITLE
Rmd or Jupyter notebooks

### ISSUE THREAD

**Issue by betatim** [openZH/covid_19#40]
Does someone know of Rmd or Jupyter notebooks that read and visualise the data?

If yes it could be nice to include one or two of them here. We can also add a mybinder.org link to let people run them.

Great work!

**Comment by jb3-2** [comment]
Maybe one of those here is close to what you're looking for? https://db.schoolofdata.ch/project/65

**Comment by rokroskar** [comment]
@betatim we started a project on the Renku platform for this: https://renkulab.io/projects/covid-19/covid-19-public-data

The notebook for this data is here: https://renkulab.io/projects/covid-19/covid-19-public-data/files/blob/notebooks/examples/openzh-covid-19-example.ipynb

We would be very happy if people contributed more visualizations and analysis! In particular, I would love to scale these by population data...

**Comment by baryluk** [comment]
I just tested the Jupyter notebook, and it works really nice, and is easy to use. Good job.

**Comment by zdavatz** [comment]
@rokroskar Where do you get the population data from?

**Comment by rokroskar** [comment]
@zdavatz good question, it took me a while to find the right table. It's from the [Bundesamt für Statistik](https://www.bfs.admin.ch) and I got it from a data request form that now I cannot for the life of me locate again. This is the link it was obtained from: https://www.bfs.admin.ch/bfsstatic/dam/assets/9635943/master

However, I just now found a better document: https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/stand-entwicklung/raeumliche-verteilung.assetdetail.9486060.html

All the available data that I could find is from 2018 unfortunately... if you have a better source please let me know!

**Comment by rokroskar** [comment]
Ah I just realized those don't have the same data - the first one is reported on 31.12.2018 the second one on 1.1.2018. 🤷‍♂

**Comment by metaodi** [comment]
See #246 for a Rmd document

**Comment by ivanek** [comment]
The Rmd is now at #246

**Comment by rokroskar** [comment]
@zdavatz or anyone else that is interested in population numbers - I recently started pulling them out of Wikidata (as per the suggestion of someone commenting in the youtube channel during the livestream of the hackathon of all places). You can play with the query [here](https://query.wikidata.org/#SELECT%20DISTINCT%20%3FregionIso%20%3FregionLabel%20%28MAX%28%3Fpopulation_count%29%20AS%20%3Fpopulation%29%20%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%23%20select%20country%20by%20its%20iso-3%0A%20%20%20%20%20%20%20%20%3Fcountry%20wdt%3AP298%20%22CHE%22%20.%0A%20%20%20%20%20%20%20%20%23%20region%20has%20an%20iso%20%3Fiso%0A%20%20%20%20%20%20%20%20%3Fregion%20wdt%3AP300%20%3FregionIso%20.%0A%20%20%20%20%20%20%20%20%23%20region%20has%20a%20population%20of%20%3Fpopulation%0A%20%20%20%20%20%20%20%20%3Fregion%20wdt%3AP1082%20%3Fpopulation_count%20.%0A%20%20%20%20%20%20%20%20%23%20country%20contains%20region%20%3Fregion%0A%20%20%20%20%20%20%20%20%3Fcountry%20wdt%3AP150%20%3Fregion%20.%0A%20%20%20%20%20%20%20%20%23%20country%20is%20an%20instance%20of%20sovereign%20state%0A%20%20%20%20%20%20%20%20%3Fcountry%20wdt%3AP31%20wd%3AQ3624078%20.%0A%20%20%20%20%20%20%20%20%3Fregion%20wdt%3AP1082%20%3Fpopulation_count%20.%0A%0A%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22de%22%20%7D%0A%20%20%20%20%7D%0AGROUP%20BY%20%3FregionIso%20%3FregionLabel).

**Comment by zdavatz** [comment]
@rokroskar great, Thank you!
