### ISSUE TITLE
TG scraper did not update

### ISSUE THREAD

**Issue by JudithBouman2412** [openZH/covid_19#403]
TG scraper did not update the new data during roundtrip of 10 am.

**Comment by baryluk** [comment]
More details please or close this issue. TG scraper works.

**Comment by baryluk** [comment]
This feels like an invalid bug. TG scraper works, and github actions for this scraper all succeeded.

Please reference a specific problem, with error message / any other output, link to github action, or commit, or URLs showing discrepancy.

Otherwise please just close the issue.

**Comment by metaodi** [comment]
It's a misunderstanding: the scraper runs every hour. So it's possible it has not yet picked up the new numbers. I propose to wait for the next scraper run before opening an issue about the scraper "not updating".
