### ISSUE TITLE
No '0' as values

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#414]
There's an inconsistent behaviour between manually updated cantons and updates by scraping.

We aim for empty values, instead of some with zeros.

Looking forward to hearing about constraints and conditions.

Many thanks, a

**Comment by baryluk** [comment]
AFAIK, empty means we don't have info about it from canton. 0 means we know it is zero from reports.

I.e. many cantons that doesn't have deaths, don't even mention it, but some say it is 0.

The same is with other fields. If the ventilated / intubated numbers is not reported by a canton, we simply don't know if it is 0, or some non-zero number, that just happens to not be reported. So the field will be empty.

**Comment by andreasamsler** [comment]
Many thanks @baryluk for your insights. What are yours', @tlorusso @mmznrSTAT ?

**Comment by tlorusso** [comment]
I agree with @baryluk . If we have reliant and very clear information that a variable was 0 (e.g. no deceased until date X), we could integrate this. But we might have to provide clear criteria, to ensure that this is handled in a consistent way.

**Comment by andreasamsler** [comment]
@tlorusso it is quite hard to introduce clear criteria with all the teams invoved here. In the manner of a Scrum Master, I therefore ask: Is it an issue which needs to be solved at all?

And as a Product Owner my answer is: Yes, it does, because some day there will be '0' hospitalizations.

So, I ask you to write down the criteria, and let me know, when done - so that I can inform the manual update/review team.

A team btw which I would ask you to treat with care; most of them are GitHub newbies, and their focus is on data quality. Please respect them, thanks!

**Comment by metaodi** [comment]
I agree with @baryluk and @tlorusso and imho the criteria is very simple: the goal of this repo is to collect and provide data _communicated by the cantons_.

| Value | Meaning |
|---------- | -------------- |
| 0         | they communicated 0 on that date|
|empty | they communicated nothing/did not provide a value for this variable on that date|

**Comment by tlorusso** [comment]
Is this something we should add to the Readme to highlight this general rule? If we want this to be clear to everybody we might want to make it as visible as possible @baryluk @andreasamsler  @metaodi

**Comment by metaodi** [comment]
Let's add it to the README then.
