### ISSUE TITLE
BL scraper did not pick up data 3-4

### ISSUE THREAD

**Issue by JudithBouman2412** [openZH/covid_19#417]
Sorry if this is due to too fast manual adaptation, but I have been asked to still report this. 

The BL scraper did not pick up the data of today (3-4-2020) before the manual update round of 14.00.

**Comment by baryluk** [comment]
More details please.

What it is as of time of report? What it should be? How did you get the numbers (i.e. URL please / screenshot).

**Comment by baryluk** [comment]
Before reporting issues, please run the scraper manually and find out if it is broken.

**Comment by baryluk** [comment]
@JudithBouman2412 We have various automated tools to find out broken stuff, and they got fixed quickly. If you are not sure, please do not create unnecessary issue reports. We monitor all the cantons few times a day, and act on failures and missing data very quickly (in less than a 24h, usually way faster).

**Comment by JudithBouman2412** [comment]
@andreasamsler instructed us to report all scraper issues when we review all cantons manually.

**Comment by baryluk** [comment]
Yes, but this is not a scraper issue, so shouldn't be reported.

Please verify it it is a scraper issue before reporting.

Thank you.
