### ISSUE TITLE
GL scraper missed did not pick up number of hospitalized and deceased

### ISSUE THREAD

**Issue by JudithBouman2412** [openZH/covid_19#419]
The GL scraper did not add the number of hospitalized and deceased cases of 3-4 at the 14.00 roundtrip.

**Comment by baryluk** [comment]
Duplicate of https://github.com/openZH/covid_19/issues/416 and https://github.com/openZH/covid_19/pull/418

**Comment by baryluk** [comment]
Please check existing bugs before opening new ones!

**Comment by baryluk** [comment]
Also a tip, what is this 3-4? Please use sane date formats.
