### ISSUE TITLE
GR switched to BAG as data source

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#435]
https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/aktuell/Seiten/fallzahlen-erklaehrung.aspx

Decision: We are continuing to take the data published on the Cantonal website until Monday (there are no data being published Sat/Sun anyway). The switch of GR makes sense; it is likely that other Cantons will follow their path. By Monday we will decide, if we are adding another column to our data structure, specifying the 'data source' and/or are taking other measures.

**Comment by baryluk** [comment]
The data on the website was updated on Monday and Today (2020-04-08). So they still continue things.

I am not sure what they mean by 'BAG as a data source'. I guess they refer to the xlsx file updated daily offered by BAG. There is also a new tableau based visualisation from BAG that provides full breakdown by cantons, age and sex, but it is not fully available by mechanical means AFAIK (there is a csv dump of data there, but the link changes every day).

**Comment by Nicicalu** [comment]
@baryluk Exactly

**Comment by simgraworldwide** [comment]
The entire data published by GR at https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/Seiten/Start.aspx is taken out of the ISM of the BAG, as can be seen at https://github.com/openZH/covid19_sources_caseNumbers/blob/master/COVID19_Quellen_CH_total_v2.csv. This does not mean that they discontinue publishing data, however, they seem to have exchanged the source at some point.
