### ISSUE TITLE
2020-04-05 same source as 2020-04-04 in COVID19_Fallzahlen_Kanton_TI_total.csv

### ISSUE THREAD

**Issue by omarelabed** [openZH/covid_19#441]
Hey, I checked some sources on [`COVID19_Fallzahlen_Kanton_TI_total.csv`
](https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_TI_total.csv) and I noticed that 2020-04-05 has the same [source](https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187575&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=4b3f64139a9dd36b9fd30a1ace23654a) as the line above for 2020-04-04.

I found this URL for 2020-04-05: [`https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187576`](https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187576). Probably this is more correct.

**Comment by metaodi** [comment]
Probably related to #515
