### ISSUE TITLE
BL: "geheite kalkuliert" in ncumul_released

### ISSUE THREAD

**Issue by SarahNadeau** [openZH/covid_19#442]
I propose we stop reporting "geheite kaluliert" from BL as ncumul_released, because I do not think the derived (estimated) value from BL should be aggregated with the primary data other cantons are reporting for ncumul_released. Data users could make this caclulation themselves if they want this information. What do you at OpenZH think?

**Comment by metaodi** [comment]
So is the method different from other cantons? My guess would've been that the value is always derived/calculated.

**Comment by SarahNadeau** [comment]
That’s a good point. I was assuming other cantons had real data on this since they do not cite any calculation or estimation methods. At least for the cantons which report the number of patients released from the hospital, I think it is fair to assume those numbers are not estimates.

**Comment by metaodi** [comment]
Yes I see. We merged the two fields "recovered" and "released" together some time ago.

Maybe it's safest to simply add a new BL-specific field like `ncumul_recovered_calc`, and leave `ncumul_released empty` for BL.

**Comment by SarahNadeau** [comment]
Given that we are not sure if other Cantons are also calculating the values they publish for recovered individuals, it would probably be easier and more accurate to just add a note to the README explaining that ncumul_released should be interpreted with caution and that at least the BL values are calculated.

**Comment by tlorusso** [comment]
The description field of this variable in the Readme already points to the fact that there might indeed be differences. 

> Reported number of patients released from hospitals or reported recovered as of date 

An option would be to emphazise this: 

> Reported number of patients released from hospitals OR reported recovered as of date (defintions may vary)

As an alternative, we could start to count released from hospitals only in `ncumul_released` and create the new variable `ncumul_recovered_calc` to store the calculated values (however, also in that case there still might be differences in the way the values are calculated). I haven't seen people using this variable very much so far... so i cannot tell if it would be worth th effort.

**Comment by grssnbchr** [comment]
I was actually wondering the same thing and thus asked all cantons that publish "released" data for the general public (not just hospitalized persons, as e.g. GE does). These cantons are *ZG*, *BS*, *SZ*, *UR* and *BL* to my knowing. The latter uses a model to calculate the released/healed persons. 

**All the other cantons in this list (they all responded to me within hours) track patients and register them after a certain time without symptoms (generally 48 hours) - so the number is quite useful**. 

I'd suggest to keep the current data model nonetheless.

**Comment by SarahNadeau** [comment]
This is super useful information, great that the cantons responded so quickly.

To add to your list, AG has just begun publishing this information and it seems they also report a calculated estimate. ("Gemäss einer Schätzung des Kantonsärztlichen Dienstes gelten im Aargau rund... als geheilt.”)

Since we now know that BL (and AG?) exceptionally calculates this value and the other cantons do not, I think it does make sense to publicise this knowledge as part of the README. Maybe:

ncumul_released	Reported number of patients released from hospitals or reported recovered as of date
*at least the cantons BL and AG report calculated estimates for this value	Number	Irrespective of canton of residence

**Comment by grssnbchr** [comment]
Thanks for the info. The only problem with AG now is that they don't have such a nice sequence of figures... it basically stays at 4 released until 04/06/20 and then jumps to 170.

**Comment by baryluk** [comment]
It would be really nice to have data from cantons about released from hospitalization, and recovered cases (released from home quarantine / isolation I guess?), and use them separately in the csv files. Second one could be approximate.

**Comment by simgraworldwide** [comment]
There is an ongoing survey that tries to figure out the exact definitions of the different published data concerning released or cured. We will shortly publish this in our [source repository](https://github.com/openZH/covid19_sources_caseNumbers)
