### ISSUE TITLE
Urgent: wrong timestamp for GE 

### ISSUE THREAD

**Issue by cybermax** [openZH/covid_19#443]
the timestamp for GE in the following file is wrong (last row):
https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total.csv#L682

please fix ASAP, it's breaking websites.

thanks a lot!

**Comment by zdavatz** [comment]
![Bildschirmfoto 2020-04-05 um 19 34 39](https://user-images.githubusercontent.com/4953/78505577-aec0bd00-7774-11ea-9d15-cdcd8bcf45e1.png)
