### ISSUE TITLE
Error in the TI datas

### ISSUE THREAD

**Issue by cenadia** [openZH/covid_19#460]
There is an error in the total positive cases of 04.04.20 of Ticino. The real data is 2’442 positive cases and not 2422. The reported number of positives of 05.04.20 is indeed correct.

(see: https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187575&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=4b3f64139a9dd36b9fd30a1ace23654a)

**Comment by andreasamsler** [comment]
Checking, thans

**Comment by baryluk** [comment]
Looks like a human error during a review in https://github.com/openZH/covid_19/commit/aae4e7ee0555883b24a99798ab88cca53c68e0ae by @viktoria023 ?

TI scraper did scrape 2422:

```
...
TI 2020-04-04T08:00    2442     165 OK 2020-04-04T11:05:45+02:00 # Extras: ncumul_released=287,ncumul_hosp=370,ncumul_ICU=75,ncumul_vent=67 # URLs: https://www4.ti.ch/dss/dsp/covid19/home/, https://www4.ti.ch/area-media/comunicati/, https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187570&tx_tic
...
```

**Comment by simgraworldwide** [comment]
Corrected the row, we're in contact with TI to raise awareness. Hopefully we'll see more easily readable publications soon.
