### ISSUE TITLE
Discussion: Cumulative hospitalizations

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#473]
We only track instantaneous hospitalizations (in column `ncumul_hosp`), but it is very hard to actually figure out total number of hospitalizations. It is very easy to figure total number of confirmed cases (assuming no duplicated reporting for tests for the same person, which shouldn't happen), and total number of recovered, and deceased.

But cumulative hospitalizations is not something that is actually reported by cantons.

From the perspective of understanding the current situation and health care resource usage, instantaneous hospitalizations and trends of it are obviously very important and useful to be available and analysed.

However, cumulative hospitalizations are also important to know. It tells us how many people were treated, and how much cost overall it was to the health care system. And what percentage of all (cumulative) confirmed cases were hospitalized overall.

Technically one would think: `ncumul_hosp = ninst_hosp + ncumul_released + ncumul_deacesed`.

But that is not 100% accurate:

1. What about deceased that were not ever hospitalized, and were found to be positive post mortem, i.e. after unrelated accident, or death outside of a hospital (very unlikely in Switzerland at the current moment, but possible in some other situations).
2. Not all cantons provide information about released / recovered cases. Actually most of them don't provide this information.  So if on a day 1, canton reports `ninst_hosp=10`, and on a day 10, canton reports `ninst_hosp=20`, it is impossible to tell how many people were hospitalized in total. 20? 30? 40? Who knows.
3. Possible patient movements between cantons (also unlikely, especially at the current moment)?

**Comment by metaodi** [comment]
See the new proposed data structure in #461, it contains the new field `new_hosp`, i.e. the number of people newly admitted to hospital care.
This should cover your issue (?)

**Comment by baryluk** [comment]
Ooo. That is interesting. So summing new_hosp across days would give the cumulative hospitalizations then.

**Comment by metaodi** [comment]
@baryluk yes this is my understanding

**Comment by baryluk** [comment]
@metaodi Ok. That sounds great, but how we are going to obtain data for `new_hosp`?

**Comment by metaodi** [comment]
Some cantons already provide this data, e.g. [NW](https://www.nw.ch/gesundheitsamtdienste/6044) (see the column "Veränderung"). Others are in the process of providing it (afaik ZH).

I guess it's the same as with any other number. Be on the lookout :wink:

**Comment by metaodi** [comment]
I just noticed that I was wrong about NW: the "Veränderung" is the difference to the day before. But new_hosp is only for new cases (so not accounting for released patients).

It's a subtile difference, but it's important to note, that new_hosp can not be negative (which actually happend today since the manual reviewers put the "Veränderung" in new_hosp).

**Comment by metaodi** [comment]
Since we now have new_hosp from some cantons, we can close this issue. Feel free to re-open it if needed.
