### ISSUE TITLE
fix scraper BL 

### ISSUE THREAD

**Issue by CorinneHuegli** [openZH/covid_19#474]
Please make sure the [BL-scraper](https://github.com/openZH/covid_19/blob/master/scrapers/scrape_bl.py) does correctly calculate "Hospitalizations" as a sum of "Normale Station" and "Intensivstation". Thanks.
![Scraper](https://user-images.githubusercontent.com/62387508/78779159-bf537c00-799c-11ea-89c1-e286525043bc.png)

**Comment by baryluk** [comment]
@CorinneHuegli Thanks for spotting this. Fix sent for merging.

Fortunately we can also go over historical data to recheck if did put wrong data before in csv files.

**Comment by CorinneHuegli** [comment]
@baryluk the uploaded data BL is correct so far. Thanks.
