### ISSUE TITLE
add ncumul_tests from bag

### ISSUE THREAD

**Issue by grbos** [openZH/covid_19#481]
On the daily "Situationsbericht zur epidemiologischen Lage in der Schweiz und im Fürstentum Liechtenstein" PDF of the BAG one finds the number of total tests up to today. To my knowledge this number is not available anywhere else and also the PDF itself is not archived. 
I am archiving the German version of the PDF since March 31st and could restore via web.archive.org all PDFs since March 25th, the day of the first publication of the number of tests. (on the 27th only the French version was archived)
All PDFs are in [this](https://www.dropbox.com/sh/frmtfmuqbwnboax/AAARF52DeeJFDcgdpORXvd-da?dl=0) Dropbox folder together with the Excel files containing the "Daten des Situationsberichtes" which is published together with the "Situationsbericht".

I think it would be interesting to add the total number of tests and maybe also the positive percentage to the data set and maybe to archive the PDFs and Excel files.
For example for some reason the daily number of tests went down from over 6500 last week to about 4500 this week.

Gregor

The numbers from the PDFs 
Date        | Tests     | Positive [%]
25-03-20 |   84000 | 12
26-03-20 |   91400 | 14
27-03-20 |   97012 | 12
28-03-20 | 106000 | 12
29-03-20 | 111000 | 13
30-03-20 | 116700 | 13
31-03-20 | 123150 | 13
01-04-20 | 130700 | 15
02-04-20 | 139330 | 15
03-04-20 | 145780 | 15
04-04-20 | 153440 | 15
05-04-20 | 158000 | 15
06-04-20 | 162500 | 15
07-04-20 | 167429 | 15
08-04-20 | 171938 | 15

**Comment by baryluk** [comment]
FYI. I also have a dump of all PDFs since 2020-03-23 here: https://www.functor.xyz/covid_19b/

In file `unique_pdfs.txt` you can find a list.

**Comment by grssnbchr** [comment]
On Wednesday, I received a detailed daily overview of tests, directly from the BAG. 

I haven't checked whether these data are consistent with what they publish in their PDFs.

Nonetheless, you can download their Excel sheet right here (never mind the emoji in the URL...): 

https://srgssr-my.sharepoint.com/:x:/g/personal/timo_grossenbacher_srf_ch/EQU7Mw27pVdKk6lZ8imEjUcBslzN6VOq0k4OR4KxfAlPPg?e=yFegzZ

![grafik](https://user-images.githubusercontent.com/2305708/78975126-b76a1800-7b13-11ea-8c3b-911b155db1c5.png)

More context: https://www.srf.ch/news/schweiz/daten-zur-krise-die-wichtigsten-fragen-und-antworten-zu-den-corona-zahlen

**Comment by rokroskar** [comment]
@grssnbchr this is great, thanks for the link to the spreadsheet! Is this being updated by the BAG or by you? And is there a downloadable link somewhere? Are there any limitations with sharing the data? I'd like to include it as a dataset in our [covid-19 public data project](https://renkulab.io/projects/covid-19/covid-19-public-data).

**Comment by grbos** [comment]
@grssnbchr thank you very much for your article and the link to your data. 
The two data sets seem to be somewhat consistent as far as I can tell. At least in order of magnitude and tendency. One can expect some differences since the PDF data probably represents the number of finished tests per day while the data from SRF represents the number of tests started on a given day. However, what surprises me, is that the PDF data seems to be almost consistently larger than the SRF data. Not sure whether this can be explained by the testing delay.
![grafik](https://user-images.githubusercontent.com/63354316/79015427-fa0c0e80-7b6c-11ea-83d0-63f52bd206bc.png)

**Comment by grssnbchr** [comment]
@rokroskar @grbos 
As said: I received the Excel that is available for download *as is* from the BAG on a one-time-basis. I cannot explain the differences to the PDFs either. All information I received is within the Excel, there was no context provided. As far as I know, the BAG does not publish the test frequencies anywhere else. I might ask them again soon, but you're free to do that as well.

**Comment by metaodi** [comment]
I'm closing this issue for now, since we decided not to mix BAG and cantonal data. Feel free to re-open this issue if needed.
