### ISSUE TITLE
ZG hospitalization data

### ISSUE THREAD

**Issue by cybermax** [openZH/covid_19#489]
It seems like the v1 data related to the hospitalizations for canton ZG do not match the detailed stats on the official webpage: 
https://www.zg.ch/behoerden/gesundheitsdirektion/statistikfachstelle/themen/gesundheit/corona

**Comment by baryluk** [comment]
There is PR in progress to use this data for hospitalization numbers, and other stats: https://github.com/openZH/covid_19/pull/488

**Comment by baryluk** [comment]
Should be fixed now.

**Comment by cybermax** [comment]
Thanks a lot! But there still seems to be a problem:
https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_ZG_total.csv
The number of hospitalizations is > 1 as you can see here:
https://www.zg.ch/behoerden/gesundheitsdirektion/statistikfachstelle/themen/gesundheit/corona

**Comment by baryluk** [comment]
Thanks @cybermax .

Yes, indeed, the existing data need to be updated for all previous days with this new data.

**Comment by cybermax** [comment]
That would be great. Thanks a lot!

**Comment by metaodi** [comment]
Fixed with #613
