### ISSUE TITLE
SH provides excel sheet

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#490]
we should switch to the xls as source (just like SZ)

**Comment by baryluk** [comment]
@metaodi I can work one SH or GL, if you can take the other one.

I just familiarised myself with `xlrd`, and managed to read some xlsx files from BAG.

**Comment by metaodi** [comment]
You should check the SZ scraper, as they all use the same excel template, it should be a fairly easy adaption.

**Comment by metaodi** [comment]
Here:

https://github.com/openZH/covid_19/blob/1e88739ab354febbd8d9036d7fe4391c76c70fe3/scrapers/scrape_sz.py#L12-L31

**Comment by baryluk** [comment]
A small research into URL handling.

https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Departement-des-Innern/Gesundheitsamt-3209198-DE.html

load json from https://sh.ch/CMS/content.jsp?contentid=3209198&language=DE&_=1584807070095

(we already load it in the existing scraper)

In it there this part:

```json
{
"data_post_content": "<p class=\"post_text\"><strong><a contentid=\"3666465\" href=\"javascript:;\" label=\"Aktuelle Fallzahlen\" language=\"DE\" linktype=\"internal\" phoenixlink=\"true\" target=\"_blank\">Aktuelle Fallzahlen</a></strong></p>...."
}
```

Note the contentid=3666465

Upon clicking, JS loads another json via javascript:

https://sh.ch/CMS/content.jsp?contentid=3666465&language=DE&_=1586425353254

then it extracts URL and asks browser to download it.

Important parts of 


```json
{
"data_publication_date": "09.04.2020",
"data_file_name": "Fallzahlen Corona Kanton Schaffhausen.xlsx",
      "data_filemeta":"{\"uploaded\":1,\"fileName\":\"e1f50d26-f2c8-41d4-8b81-44eb857b4fcb\",\"key\":\"TEMPUPLOADFILES\",\"url\":\"\/CMS\/get\/file\/e1f50d26-f2c8-41d4-8b81-44eb857b4fcb\",\"originalname\":\"Fallzahlen Corona Kanton Schaffhausen.xlsx\",\"fileid\":\"e1f50d26-f2c8-41d4-8b81-44eb857b4fcb\",\"category\":\"null\",\"title\":\"null\",\"filesize\":11743}",
        "data_custom_publication_date_time":"07:12",
        "data_permalink":"\/Webseite\/Kanton-Schaffhausen\/Beh-rde\/Verwaltung\/Departement-des-Innern\/Gesundheitsamt-3666465-DE.html",
}
```

The end URL to actual data is:

https://sh.ch/CMS/get/file/e1f50d26-f2c8-41d4-8b81-44eb857b4fcb  (~11kB, xlsx, Excel 2007+)

**Comment by baryluk** [comment]
@metaodi Yes, I notice the SZ. And I am familiar with xlrd now.

Still, my question remains: Do you want to work on both, or I should take this one maybe? I don't want to duplicate work.

**Comment by metaodi** [comment]
Please do this one, I will only have time to code later in the evening. If both are already done by then: perfect, more time for other for me :tada: . If not: I'll do it :factory_worker:

**Comment by baryluk** [comment]
Ok. I will do SH one.

I checked the SH and GL and SZ, and they don't really use same Excel template:

GL: 

```csv
COVID-19-Fallzahlen Kanton Glarus,,,
Datum,Bestätigte Fälle (kumuliert),Personen in Spitalpflege,Todesfälle (kumuliert)
03-10-20,1,0,0
03-11-20,1,0,0
...
04-09-20,67,2,2
,,,
,,,
,,,
,,,
,,,
,,,
,,,
,,,
,,,
,,,
```

SH:

```csv
Datum,Uhrzeit,Positiv,Hospitalisiert_Iso,Hospitalisiert_Intensiv,Verstorben
03-11-20,,1,,,0
03-12-20,,1,,,0
...
04-08-20,09:30,50,13,2,1
04-09-20,09:30,52,15,2,1




Hinweise:,,,,,
- Die Zahlen zu den Anzahl Hospitalisationen (Isolation und Intensiv) werden erst seit dem 25.03.2020 erhoben.,,,,,
- Die Uhrzeit wird erst seit dem 07.04.2020 ausgewiesen.,,,,,
```

SZ:

```csv
Fallzahlen Kanton Schwyz,,,
Datum,Bestätigte Fälle (kumuliert),Todesfälle (kumuliert),Genesene (kumuliert)
04-09-20,213,9,113
```

They are all different.

So I am not sure what you mean by "You should check the SZ scraper, as they all use the same excel template".

**Comment by metaodi** [comment]
What I meant is, that they all provide their data on one sheet, with no fancy excel formula and each row is a new day (basically like a CSV). So if you use the SZ scraper as a template, you only have to adapt the columns.

But yes they are not the same, and you have to check each one. E.g. for SH some logic is needed to find the last row.

**Comment by baryluk** [comment]
> What I meant is, that they all provide their data on one sheet, with no fancy excel formula and each row is a new day (basically like a CSV). So if you use the SZ scraper as a template, you only have to adapt the columns.
> 
> But yes they are not the same, and you have to check each one. E.g. for SH some logic is needed to find the last row.


Oh. I see, now I understand what you meant. Thanks.

**Comment by metaodi** [comment]
@baryluk have you already started with SH?
