### ISSUE TITLE
GL provides excel sheet

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#491]
we should switch to the xls as source (just like SZ)

**Comment by baryluk** [comment]
Info about URLs:

XLSX file is directly linked as https://www.gl.ch/public/upload/assets/27574/COVID-19_Fallzahlen_Kanton_Glarus.xlsx

on https://www.gl.ch/verwaltung/finanzen-und-gesundheit/gesundheit/coronavirus.html/4817

**Comment by metaodi** [comment]
on it.
