### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by RamiKrispin** [openZH/covid_19#510]
Hi,

Thank you for pulling this data. I am using this repo to pull the data into R package, is there any specific citation that I should about this repo and the data sources?

Best,
Rami

**Comment by mmznrSTAT** [comment]
Hey Rami
It is a collaborative approach, many are contributing. You can link to the Repo and write: "Data Repository made available by "Specialist Unit for Open Government Data Canton of Zurich". 

Is this ok for you?

Best
Matthias

**Comment by RamiKrispin** [comment]
Thanks!
