### ISSUE TITLE
NE death are not updated

### ISSUE THREAD

**Issue by JBeyel** [openZH/covid_19#513]
The scraper for NE doesn't work properly for the death cases. The total number of death cases in NE still shows the date of 20-4-8 and 34 wheras the latest publication is from 20-4-10 and has 38 cases.

**Comment by baryluk** [comment]
FYI. NE provide death numbers only day or two after. That is why scraper usually don't provide it.

See https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.pdf
