### ISSUE TITLE
TI scraper inconsistency between two sources.

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#515]
TI scraper reads from two sources. Main TI page for COVID-19, and daily bulletins.

But they are updated at different times.

This leads to extra information to be inconsistent.

I.e. look at the first scrape done on 2020-04-04 at 12:05 CEST, it says ICU=75, hosp=370. But it is data for 2020-04-03T08:00 (previous day), because it was the most recent bulletin at 12:05 CEST.

Data at 13:05 CEST looks correct, because the new buletin for 2020-04-04 was released.

```
TI 2020-04-04T08:00    2442     165 OK 2020-04-04T12:05:48+02:00 # Extras: ncumul_released=287,ncumul_hosp=370,ncumul_ICU=75,ncumul_vent=67 # URLs: https://www4.ti.ch/dss/dsp/covid19/home/, https://www4.ti.ch/area-media/comunicati/, https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187570&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=bf727072887350e7700586450c3cf957
TI 2020-04-04T08:00    2442     165 OK 2020-04-04T13:05:42+02:00 # Extras: ncumul_released=314,ncumul_hosp=363,ncumul_ICU=72,ncumul_vent=67 # URLs: https://www4.ti.ch/dss/dsp/covid19/home/, https://www4.ti.ch/area-media/comunicati/, https://www4.ti.ch/area-media/comunicati/dettaglio-comunicato/?NEWS_ID=187575&tx_tichareamedia_comunicazioni%5Baction%5D=show&tx_tichareamedia_comunicazioni%5Bcontroller%5D=Comunicazioni&cHash=4b3f64139a9dd36b9fd30a1ace23654a
```

This can be solved programmatically probably.

One of the options is to just use bulletins.

Another is to cross check both sources, and not use bulletin data if it is not the same date as the main TI page for COVID-19.

**Comment by metaodi** [comment]
I would opt to use one source only, otherwise it's really hard to be sure if the sources are in sync. Eslecially if they are not updated at the same time.

**Comment by metaodi** [comment]
It seems there is now an excel sheet with the complete data: https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github.xlsx
