### ISSUE TITLE
COVID19_Fallzahlen_Kanton_GL_total.csv uses different column names compared to rest

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#53]
Please correct this:

COVID19_Fallzahlen_Kanton_GL_total.csv uses different column names compared to rest

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_GL_total.csv

Reference: https://github.com/zdavatz/covid19_ch/issues/12

**Comment by zdavatz** [comment]
@tlorusso please check this.

**Comment by tlorusso** [comment]
Feel free to open a PR and fix it! Otherwise i'll correct this this evening.

Thx for the hint.

**Comment by zdavatz** [comment]
ok

**Comment by zdavatz** [comment]
Correct: date,time,abbreviation_canton_and_fl,ncumul_tested,ncumul_conf,ncumul_hosp,ncumul_ICU,ncumul_vent,ncumul_released,ncumul_deceased,source
Wrong:
date,time,abbreviation_canton,ncumul_tested,ncumul_conf,ncumul_hosp,ncumul_ICU,ncumul_vent,ncumul_released,ncumul_deceased,source

Looks like only abbreviation_canton is wrong. Should be abbreviation_canton_and_fl.
