### ISSUE TITLE
SG and SH current_hosp has to be added manually

### ISSUE THREAD

**Issue by simgraworldwide** [openZH/covid_19#536]
The scrapers for SG (https://www.sg.ch/tools/informationen-coronavirus.html) and SH (CSV can be found under https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Departement-des-Innern/Gesundheitsamt-3209198-DE.html) do not add up the different numbers (they both report hospitalised isolated and hospitalised icu separately) for hospitalised to get the current_hosp.

**Comment by baryluk** [comment]
That is easy to fix, but do you have some direct clarification from SG and SH that the numbers are separate and `hospitalized isolated` does not include ICU patients?

**Comment by simgraworldwide** [comment]
That is correct, both cantons confirmed that to get the total number of hospitalised, one needs to add their reported numbers of isolation and icu.
