### ISSUE TITLE
Validation error in BE data

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#540]
The [validation of the BE data currently fails](https://github.com/openZH/covid_19/runs/595131245?check_suite_focus=true):

```
COVID19_Fallzahlen_Kanton_BE_total.csv failed the following checks:
Row 37: cumulative field ncumul_conf: 69 < 1515
Row 37: cumulative field ncumul_deceased: 44 < 55
```

**Comment by metaodi** [comment]
I'm not sure if the structure changed, but maybe we should switch to scrape the table (like we do for LU) instead of using this huge regex.

**Comment by dominikgehl** [comment]
@metaodi I'm having a look

**Comment by dominikgehl** [comment]
#543

**Comment by metaodi** [comment]
I need to check this again, the BE scraper has an error, but did not fail.
