### ISSUE TITLE
Neuenburg (NE) with wrong dates...

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#544]
Please standardize the Neuenburg-Dates

<img width="331" alt="image" src="https://user-images.githubusercontent.com/17248257/79590451-532cf280-80d7-11ea-9e3c-57acf84d0c66.png">

**Comment by rsalzer** [comment]
I added a quick-fix in my code so it does not crash ... but please correct the date format to standard YYYY-MM-DD

**Comment by metaodi** [comment]
Fixed with https://github.com/openZH/covid_19/commit/b18e6f0942a8b11f331c3abf6835dffd7fd100bb
