### ISSUE TITLE
CSV to JSON

### ISSUE THREAD

**Issue by matjung** [openZH/covid_19#57]
https://www.micro-work.net/covid/
I am planing to add you to my repository of slave covid webservices
First in csv, later in json format

**Comment by baryluk** [comment]
Why is this the issue? It is better to keep the data in this repo in one format. If you can convert it to any data you want. Or consume as csv in javascript for the best results.

**Comment by metaodi** [comment]
I agree with @baryluk. Can we close this issue?

**Comment by zdavatz** [comment]
For sure I agree with @baryluk too. @matjung just clone the Repo and do whatever you want.

**Comment by matjung** [comment]
Thanks
