### ISSUE TITLE
GE URL has changed

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#570]
new data seems to be published at https://www.ge.ch/document/20094/telecharger

**Comment by dominikgehl** [comment]
Unfortunately the tables at the top of the PDF file don't seem to be text

**Comment by naspert** [comment]
it also seems there is an issue with GE data, as it reports a negative number of new cases for 20.04

**Comment by simgraworldwide** [comment]
They adjusted data from early March, something is wrong there.

**Comment by simgraworldwide** [comment]
For some reason a lot of data changes on a daily basis. We are currently overwriting the complete file daily. We are trying to contact the right people to raise awareness there.
However, the URL in the file https://www.ge.ch/document/covid-19-situation-epidemiologique-geneve/telecharger seems to work again.
