### ISSUE TITLE
Other not tested data - not really an issue

### ISSUE THREAD

**Issue by fabiomariotti** [openZH/covid_19#576]
Hoi, this is not really an issue with the current repo.

BTW, hi all, and many thanks for the current work! appreachiared!

As CH is on a testing only hanvy cases, I wander if there is a correlation with
other not covid-19 marked cases.

Do you think it is possible to get the death rate from cantons and compare it
with the same period in the past?

To try to detect untested behaviours?

Also, it appears that we have carriers without symptoms.

Thanks!
Fabio

**Comment by metaodi** [comment]
There is a dataset with the number of deaths: https://github.com/statistikZH/covid19monitoring_health_mortality/blob/master/README.md

see also https://twitter.com/mmznr/status/1245393190083010563?s=19
