### ISSUE TITLE
GE: URL used in parser isn't accessible any more

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#590]
current URL https://www.ge.ch/document/point-coronavirus-maladie-covid-19/telecharger now returns 403 error.

Information is now available at https://www.ge.ch/document/covid-19-situation-epidemiologique-geneve/telecharger but the PDF contains the data tables as images, and pdf2text doesn't work on them.

**Comment by simgraworldwide** [comment]
Currently, we are updating the data of GE manually, we are trying to get them to publish properly!

**Comment by gvb1234** [comment]
I've asked them as well to publish properly. They revise their data so much, it is insane. And now they won't even publish daily (only Mon-Wed-Fri).

**Comment by naspert** [comment]
Another 'Genferei'...

**Comment by simgraworldwide** [comment]
Will update it manually in a bit

**Comment by gvb1234** [comment]
They have revised several old dates again, back to March 16th.

**Comment by simgraworldwide** [comment]
I close this issue for now and open a new one as soon as this mess is cleaned up and there is actually data to scrape.
