### ISSUE TITLE
Feature request - infections per inhabitant

### ISSUE THREAD

**Issue by ProBeta1** [openZH/covid_19#599]
What I miss here is the opportunity to switch the unit: As not all the cantons have the same number of inhabitants (Zurich being the canton with the most inhabitants), a comparison “infections per inhabitant” over time would be interesting.

**Comment by tlorusso** [comment]
Dear @ProBeta1, that would indeed be interesting, however this repo focusses exclussively on data collection. We welcome any efforts which aim at enriching the data (e.g. with population numbers), but would like to keep things as overseeable as possibly here. If someone is willing to build an enhanced file with per inhabitant numbers in a separate repo we would gladly link to it in our Readme.
