### ISSUE TITLE
SQL Database

### ISSUE THREAD

**Issue by tgdbepe4** [openZH/covid_19#618]
I as consumer of your data are continuously irritated by the CSV‘s which have every few days new fields in the data structure which cause to fail my processing. 

Therefore I kindly ask you to enable an access via SQL as soon as possible.

Peter

**Comment by metaodi** [comment]
[The data structure](https://github.com/openZH/covid_19/blob/master/README.md#data-structure) does not change every few days. There has been one major change to the data structure, but even then we kept the old files for backwards compatibility.

Internally we use SQLite to manage the CSV, feel free to use [our script to generate a SQLite database](https://github.com/openZH/covid_19/blob/master/scrapers/populate_database.py) from the CSV.

Last but not least: [check the REST-API](https://covid19-rest.herokuapp.com/) that was build on top of our data by @apfeuti.
