### ISSUE TITLE
VD changes location for scraper

### ISSUE THREAD

**Issue by simgraworldwide** [openZH/covid_19#621]
For some reason, VD has started publishing its xlsx-file on https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/ and have informed us that they are going to stop the publication via https://partage.vd.ch/userportal/#/shared/public/hUApwTjAKdaXQCnB/StatistiquesDSAS. Scraper needs to be updated (hopefully for the last time in a while).

**Comment by dominikgehl** [comment]
Looking into it

**Comment by dominikgehl** [comment]
solved in #626
