### ISSUE TITLE
SZ Scraper fails

### ISSUE THREAD

**Issue by simgraworldwide** [openZH/covid_19#631]
SZ has false positivs in its publication (excel accessible via https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948) on 2020-03-25. This leads to a negative development of ncumul_conf and a failing scraper (https://github.com/openZH/covid_19/runs/629465214?check_suite_focus=true).
SZ is unwilling to adapt the data. We should either adapt the scraper to ignore 2020-03-25 or ignore the check that leads to the error, should that be possible for a single scraper.
I prefer to ignore a single date and leave the cell for that date empty, as it is now.

**Comment by metaodi** [comment]
works again: https://github.com/openZH/covid_19/commit/9541afca054c08ecf347ec2a19ff896fe5b8a8f4
