### ISSUE TITLE
FR scraper is failing

### ISSUE THREAD

**Issue by simgraworldwide** [openZH/covid_19#636]

**Comment by metaodi** [comment]
[Failed run](https://github.com/openZH/covid_19/runs/630595905?check_suite_focus=true):

```
Run the scraper...
Traceback (most recent call last):
  File "/home/runner/work/covid_19/covid_19/scrapers/scrape_fr.py", line 22, in <module>
    print('Date and time:', row['Date'].date().isoformat())
AttributeError: 'int' object has no attribute 'date'
```

**Comment by metaodi** [comment]
FR has entered a wrong date for today, instead of `29.4.2020` (which is recognized by Excel as date) they entered the number `2904.202`.

**Comment by simgraworldwide** [comment]
I thought it was failing before they added yesterday's data but might have been wrong. Never mind, manually updated the data, I'm sure FR will notice the error today and correct it. Until then, FR will fail for today...
I'll close the issue as soon as they update their data today.

**Comment by metaodi** [comment]
FR does not fail: https://github.com/openZH/covid_19/actions?query=workflow%3A%22Run+FR+scraper%22

I updated the scraper in #637 to skip entries with an invalid date. So this means those rows are silently ignored until they are fixed.

**Comment by metaodi** [comment]
It's fixed now: https://github.com/openZH/covid_19/commit/50196a23cfc60a46758c540e2a7b464ab55f7821
