### ISSUE TITLE
ZH Data Issue

### ISSUE THREAD

**Issue by Drewsmits** [openZH/covid_19#688]
According to the update today, the canton of Zürich saw +411 cases for a total of 3,545. However, if you look at the Gesundheitsdirektion PDF, it shows there was only a +9 increase from yesterdays total of 3,536. 

It looks like you are using the same source, but how are the numbers different?

https://gd.zh.ch/internet/gesundheitsdirektion/de/themen/coronavirus.html#medienmitteilungen

**Comment by andreasamsler** [comment]
Thanks for the issue @Drewsmits, we're already clarifying with our colleagues. They are committing directly to the repo; the increase is not plausible. See the latest commit: https://github.com/openZH/covid_19/commit/9af41dd95f036f7bf6eb145d2cbb8d5d88106e4a

Keep you posted, best @andreasamsler

**Comment by andreasamsler** [comment]
For the time being there is no reason to worry. The update of the case numbers of the Canton of Zurich from today Friday (2020-05-08) has been withdrawn and will be reviewed again.

**Comment by Drewsmits** [comment]
No problem, really appreciate the work you are doing to keep this up to date!

**Comment by andreasamsler** [comment]
Issue fixed and resolved:
- latest commit: https://github.com/openZH/covid_19/commit/f7ef7dd76ae344d5d28dd85f815b297b68ef5201
