### ISSUE TITLE
Primitive scraper for SH

### ISSUE THREAD

**Issue by baryluk** [openZH/covid_19#69]
```bash
echo SH; d=$(curl --silent 'https://sh.ch/CMS/content.jsp?contentid=3209198&language=DE&_=1584807070095' | grep data_post_content | sed -E -e 's/\\n/\n/g'); echo "Scraped at $(date --iso-8601=seconds)"; echo -n "Date and time: "; echo "$d" | grep "Im Kanton Schaffhausen gibt es" | sed -E -e 's/^.*\(([0-9.]+)\).*$/\1/'; echo -n "Confirmed cases: "; echo "$d" | grep "best&auml;tige" | sed -E -e 's/^.*strong>([0-9]+)[^0-9]*$/\1/'
```

```
SH
Scraped at 2020-03-21T16:19:46+00:00
Date and time: 20.03.2020
Confirmed cases: 14
```

This is really hacky, because sh.ch is absolutely abhorrent with amount of JavaScript and content that is loaded dynamically. But it works.

The URL that generates json content, was reverse engineered from looking at network traffic when loading this site: https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Departement-des-Innern/Gesundheitsamt-3209198-DE.html

I have no idea what the `_` parameter is, some kind of timestamp I think, but I am not sure. Could be caching, and might not work. To be seen.

**Comment by zdavatz** [comment]
;) thanks for hacking!

**Comment by ebeusch** [comment]
Please do UR too :)

**Comment by zdavatz** [comment]
@baryluk great hacking Sir, great Hacking!

**Comment by baryluk** [comment]
> Please do UR too :)

Done. https://github.com/openZH/covid_19/issues/72
