### ISSUE TITLE
Add plausibility check when values change too much

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#691]
The validation script should check if values change too much from one day to another and issue a warning/error.

**Comment by metaodi** [comment]
I will try to find a solution. I'm thinking of something like an outlier detection of the time series. But I think it should be based on the difference to the previous day.

**Comment by metaodi** [comment]
Here is a notebook describing the approach: https://github.com/metaodi/covid-meta/blob/master/Covid-19%20Case%20numbers%20-%20outlier%20detection.ipynb

**Comment by naspert** [comment]
maybe something based on this approach ? https://stackoverflow.com/questions/22583391/peak-signal-detection-in-realtime-timeseries-data
