### ISSUE TITLE
Re-activate BL scraper

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#718]
There are now two more iframes with the before missing numbers, so it should be possible to scrape all data from there:

https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/covid-19-faelle-kanton-basel-landschaft

**Comment by CorinneHuegli** [comment]
Direct iframe-links:
https://cocontrol.bl.ch/public/dbw/78
for
ncumul_conf = Geheilte (kalkuliert) + Aktive Fälle (kalkuliert) + Todesfälle
ncumul_released = Geheilte (kalkuliert)
ncumul_deceased = Todesfälle

https://cocontrol.bl.ch/public/dbw/80
for
current_hosp = Normale Station + Intensivstation (nicht beatmet) + Intensivstation (beatmet)
current_icu = Intensivstation (nicht beatmet)
current_vent = Intensivstation (beatmet)

**Comment by dominikgehl** [comment]
on it

**Comment by CorinneHuegli** [comment]
Thanks :-)

**Comment by dominikgehl** [comment]
#729

**Comment by CorinneHuegli** [comment]
Sorry isn't there a mistake with "icu"? 
See line 150 (icu should be sum of "Intensivstation (nicht beatmet)" and "Intensivstation (beatmet)")
![grafik](https://user-images.githubusercontent.com/62387508/82095279-0d2b7480-96ff-11ea-8e43-59b38e76a503.png)

**Comment by metaodi** [comment]
@CorinneHuegli good catch, will fix this

**Comment by metaodi** [comment]
Fixed again :)
