### ISSUE TITLE
More confirmed cases than tests

### ISSUE THREAD

**Issue by emanuele-guidotti** [openZH/covid_19#723]
Hello and thank you for your work!

I'd like to notify a few bugs in the data.
For example, Schwyz on 2020-03-14 shows more confirmed cases (12) than tests (10).

You might want to have a look here were it is provided a log for these kind of issues:
https://covid19datahub.io/articles/iso/CHE.html
I hope this tool can help you to spot bugs in the data.

Best
-- Emanuele

**Comment by emanuele-guidotti** [comment]
The change in the title is fine but there seems to be also more hospitalized than confirmed cases sometimes

**Comment by simgraworldwide** [comment]
Deleted the row of SZ since it does not stem from an official source.

**Comment by baryluk** [comment]
@emanuele-guidotti hospitalized numbers are instantious (amount of people at the hospitalized / ICU at the moment), where confirmed cases are cummulative, and can include non-hospitalized cases.

As of the confirmed > tests, that is a bit sketchy, unless the canton counts differently legal residents of the canton, and current people in the canton. It is a bit unclear

**Comment by emanuele-guidotti** [comment]
@baryluk Than you for the comments.

Yes hospitalized are on date and confirmed are cumulative. https://covid19datahub.io/articles/doc/data.html

I find weird when hospitalized > confirmed: more hospitalized people on date than the total number of confirmed cases? In that case I would think that - hospitalized include non covid cases or - cumulative cases are under reported or - there is some lag in reporting the values. Same observations for the (cumulative) tests. What do you think?

**Comment by emanuele-guidotti** [comment]
Btw, I have linked this issue from our repo in the use case section
https://github.com/covid19datahub/COVID19
Just let me know if you are not comfortable with that and I'll drop it

**Comment by emanuele-guidotti** [comment]
Hope you find the tool useful. I'm going to close the issue. 
Thanks
