### ISSUE TITLE
JU source file changed name or location

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#731]
Scraper consumes https://www.jura.ch/Htdocs/Files/v/34455.xlsx/Departements/CHA/SIC/Carrousel/Coronavirus/Cornavirus/Chiffres/donnees_14_05.xlsx?download=1 - result: 404

A new source files is accessible on their webpage (https://www.jura.ch/fr/Autorites/Coronavirus/Chiffres-H-JU/Evolution-des-cas-COVID-19-dans-le-Jura.html):
"Cas confirmés (XLSX, 14 Ko)" https://www.jura.ch/Htdocs/Files/v/34465.xlsx/Departements/CHA/SIC/Carrousel/Coronavirus/Cornavirus/Chiffres/donnees_15_05.xlsx?download=1

**Comment by metaodi** [comment]
Yes it changes every day. The scraper uldated the data at 18:43 CEST in https://github.com/openZH/covid_19/commit/97dfe481674a2392162217a97ec8252b9bdc2fdc, so it looks like you missed it by a couple of minutes.
