### ISSUE TITLE
Cumulative case numbers GE compromised

### ISSUE THREAD

**Issue by gjeschke** [openZH/covid_19#735]
Update COVID19-Fallzahlen_Kanton_GE_total.csv by simgraworldwide-patch-2 on May 15, 16:49 removed all cumulative test numbers from the dataset for canton Geneve from April 1st onwards and replaced them by wrong numbers that add only the number of confirmed positive tests per day.

**Comment by andreasamsler** [comment]
Thanks @gjeschke, while GE yesterday changed the format of its data publication retrospectively starting from April 1st onwards, we have unfortunately slipped one column in our latest update. We will correct it immediately and report as soon as it is done.

**Comment by andreasamsler** [comment]
Resolved: https://github.com/openZH/covid_19/pull/736#issue-418950055
