### ISSUE TITLE
Correct Names of Appenzell

### ISSUE THREAD

**Issue by Oliver-Gloor** [openZH/covid_19#737]
On the webpage https://rsalzer.github.io/COVID_19_CH/, the two cantons of Appenzells
- Appenzell Ausserrhoden
- Appenzell Innerrhoden
are misspelled. (The second consecutive 'r' is missing.)
See:
- https://rsalzer.github.io/COVID_19_CH/#detail_AR
- https://rsalzer.github.io/COVID_19_CH/#detail_AI
and e.g. https://de.wikipedia.org/wiki/Kanton_(Schweiz)
Thanks!

**Comment by metaodi** [comment]
Please report this issue on @rsalzer's repo here: https://github.com/rsalzer/COVID_19_CH

This repository is only providing the data.

**Comment by rsalzer** [comment]
Its corrected. Thanks for pointing it out.
