### ISSUE TITLE
TI: file location

### ISSUE THREAD

**Issue by joelgautschi** [openZH/covid_19#761]
Currently you are scraping
[https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github.xlsx](https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github.xlsx)

However, at the moment https://www4.ti.ch/dss/dsp/covid19/home/  (access date: 2020-05-22 14:55) is pointing to:
[https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github_.xlsx](https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github_.xlsx)

(notice the `_` between github and .xlsx)

this seems to be the more recent file. Maybe this is just a temporary issue.

**Comment by metaodi** [comment]
Thanks for pointing this out. I think I will adapt the scraper to check the website to get the correct URL of the xlsx File.
