### ISSUE TITLE
Add neighbouring countries' regions

### ISSUE THREAD

**Issue by Eisit** [openZH/covid_19#77]
As the borders are not closed (and even if closed, wouldn't be foolproof), it would be interesting to collect and display the contamination rates of neighbouring France/Italy/Germany/Austria; ideally not the country-wide average, but the border regions only.

For France, one can find the numbers for _Ain_ and _Haute-Savoie_ faily clearly in "_point de situation_"-titled PDFs:
https://www.auvergne-rhone-alpes.ars.sante.fr/liste-communiques-presse
_Jura_, _Belfort_, _Doubs_ don't have clear separate numbers so far:
https://www.bourgogne-franche-comte.ars.sante.fr/liste-communiques-presse
_Haut-Rhin_ has again clear numbers in PDFs here:
https://www.grand-est.ars.sante.fr/liste-communiques-presse?field_archive_ars_value=0

Otherwise an unofficial data repository is here:
https://github.com/opencovid19-fr/data

Italy has a faily complete official repository from which one could pull numbers:
https://github.com/pcm-dpc/COVID-19

Found this for Germany, at _Landkreise_ level:
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_1/
Here is an unofficial repository, but I can't vouch for it:
https://github.com/marlon360/rki-covid-api

And this for Austria:
https://info.gesundheitsministerium.at/
Again, maybe scraping from Wikipedia is more feasible, with the risk it may be unreliable or defaced.

**Comment by baryluk** [comment]
What do you mean "display"?

Yes, it is in our best interest, to have this data, but not necessarily in this repo. If the data for neighbouring countries' regions are already available, maybe these things should be aggregated in some different project? If this repo is then consumed back by other project, it could be really convoluted to figure out who is the source of truth on what.

**Comment by zdavatz** [comment]
I agree with @baryluk lets focus on the cantons of Switzerland.

**Comment by Eisit** [comment]
Ah, you are right this may not be in scope for this project.

**Comment by baryluk** [comment]
Thanks for the links tho. Will be useful.
