### ISSUE TITLE
Add isolation and quarantine variables to COVID19_Fallzahlen_CH_total_v2.csv 

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#771]
Following #770 the combined CSV of all Cantonal & FL CSVs would need to comprise the two additional variables, too, right?

**Comment by metaodi** [comment]
And I guess the scrapers would need to be adapted as well to add the two new fields.

**Comment by andreasamsler** [comment]
@metaodi yes, am working on that here: https://docs.google.com/spreadsheets/d/1pkXsSBbpfnNfJViGgHFCnftqEMApStg-eWaIQotpGxg/edit#

Will create new issues per canton today.

**Comment by andreasamsler** [comment]
GE time series is done #776

**Comment by metaodi** [comment]
Done: https://github.com/openZH/covid_19/pull/792
