### ISSUE TITLE
Scrape 'current_isolated' and 'current_quarantined' of Canton AG

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#772]
With regard to #771, we aim to integrate the respective values from AG's official source file (PDF): https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200525_KFS_Coronavirus_Lagebulletin_59.pdf (example)

The values are located below the title "1. Aktuelle Lage im Kanton Aargau" in the second paragraph; atm the respective phrase reads: "Gegenwärtig betreut sind 33 infizierte Personen und 91 enge Kontaktpersonen."

"33 [infizierte Personen]" corresponds to the value of the variable 'current_isolated'
"91 [enge Kontaktpersonen]" corresponds to the value of the variable 'current_quarantined'

**Comment by fabian** [comment]
I can implement this.

**Comment by andreasamsler** [comment]
@fabian: AG published today's Lagebulletin, which looks different; see [https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200528_KFS_Coronavirus_Lagebulletin_60.pdf](https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200528_KFS_Coronavirus_Lagebulletin_60.pdf)

**Comment by fabian** [comment]
@andreasamsler Yeah saw it and tested it, matching for "betreut sind XX infizierte Personen" and "XX enge Kontaktpersonen" still works 👍
