### ISSUE TITLE
Scrape 'current_isolated' and 'current_quarantined' of Canton AR

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#773]
With regard to #771, we aim to integrate the respective values from AR's official source (webpage): https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/

On the webpage the values are located in the accordeon element "Zahlen" below the title "Contact tracing"; atm the respective phrases read:

"[Aktuell COVID-19-Erkrankte in Isolation:] 0" corresponds to the value of the variable 'current_isolated'
"[Aktuell im Kanton wohnhafte Kontaktpersonen in Quarantäne:] 0" corresponds to the value of the variable 'current_quarantined'

**Comment by dominikgehl** [comment]
#786 

Let me know if the pull requests works like this. If yes, I'll also add the necessary logic to the other scrapers.
