### ISSUE TITLE
Add 'current_isolated' and 'current_quarantined' of Canton ZH

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#774]
With regard to #771, we are asking Cantons to integrate the respective values.

Please add two additional rows to the right of your CSV resource; according to [https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_Beispiel.csv](https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_Beispiel.csv)

**Comment by dominikgehl** [comment]
#789

**Comment by metaodi** [comment]
#793
