### ISSUE TITLE
Add 'current_isolated' and 'current_quarantined' of Canton TG

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#777]
With regard to #771, we are asking Cantons to integrate the respective values.

Please add two additional rows to the right of your CSV resource; according to https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_Beispiel.csv

**Comment by dkoltg** [comment]
Following a decision, that the BAG and the Cantonal Medical Officer made this week, we don't publish these numbers at the moment. Thanks for your understanding...

**Comment by andreasamsler** [comment]
Clarified and obsolete.
