### ISSUE TITLE
Status Dashboard does not load 

### ISSUE THREAD

**Issue by jb3-2** [openZH/covid_19#778]
https://www.web.statistik.zh.ch/covid19_dashboard/index.html does not load at the moment.

**Comment by andreasamsler** [comment]
checking ..

**Comment by andreasamsler** [comment]
Line 2 in https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total_v2.csv is empty .. checking for reason

**Comment by andreasamsler** [comment]
Couldn't find the reason; deleted empty line 2 in https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total_v2.csv manually
