### ISSUE TITLE
REST-API to provide our data

### ISSUE THREAD

**Issue by apfeuti** [openZH/covid_19#78]
I'm developing a REST-API to provide our data in a machine-readable way. This helps other projects to integrate our data. Read more here: https://github.com/apfeuti/covid_19/blob/rest-api/rest/README.md

Leave your comment - if you find it useful, then I will make a pull-request.

I'm unsure if my REST-API is reading the correct file.

Regards
Andreas

**Comment by zdavatz** [comment]
please make a pull request.

**Comment by metaodi** [comment]
I don't think the API should be part of this repo. Consume the data, the CSVs are perfectly machine-readable 😉

To be clear: an API would be awesome, I would just propose to do this as a separate thing.

**Comment by zdavatz** [comment]
@apfeuti you could just add it into a separate repo or publish it on your Fork, if it is not accepted here. I will pull it for my fork.

**Comment by apfeuti** [comment]
> @apfeuti you could just add it into a separate repo or publish it on your Fork, if it is not accepted here. I will pull it for my fork.

It's already published on my fork - in the branch 'rest-api':
https://github.com/apfeuti/covid_19/tree/rest-api/rest

**Comment by zdavatz** [comment]
@apfeuti sehr schön! Kannst du das irgendwo auf einem Server laufen lassen, sodass andere darauf zugreifen können?

**Comment by zdavatz** [comment]
I also pulled you branch: https://github.com/zdavatz/covid_19 and updated the README on my Fork. https://github.com/zdavatz/covid_19

**Comment by zdavatz** [comment]
Übrigens werden die Scrapper Fallzahlen jetzt hier gesammelt. https://www.functor.xyz/covid_19/scrapers/outputs/

**Comment by apfeuti** [comment]
Ich habe es bereits auf meinem Server deployt (temporäre Lösung, bis wir eine besser Hosting-Lösung haben). Siehe Example-Calls in README.
https://github.com/apfeuti/covid_19/blob/rest-api/rest/README.md

**Comment by zdavatz** [comment]
Sehr schön! Kannst du diese Daten auch als REST-API zur Verfügung stellen? https://www.functor.xyz/covid_19/scrapers/outputs/

**Comment by tlorusso** [comment]
Wow, nice API! You guys are just awesome. But could we, as @metaodi has already suggested, keep that separate? This repo should focus on data collection and stay as 'slim' as possible so that we can manage things better. We sure will link to the API (and the respective repo) in the Readme! Thanks a lot for your contributions! @apfeuti @zdavatz

**Comment by apfeuti** [comment]
OK, we will move discussion about the REST-API to my repo: https://github.com/apfeuti/covid_19/issues

Two last questions here:

1) On which data-source should the API rely on? Under discussion are:
https://github.com/openZH/covid_19/blob/master/COVID19_Cases_Cantons_CH_total.csv
https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv
https://www.functor.xyz/covid_19/scrapers/outputs/

I'm a bit confused, about which one would be the most appropriate. Thanks for clarification.

2) Does openZH provide some infrastructure to deploy the Rest-API to? It's based on NodeJs.
   Or are there other proposals?

**Comment by metaodi** [comment]
@apfeuti can't speak for openZH, but if you want to deploy something with no cost, I'd recommend [Heroku](https://www.heroku.com/).

**Comment by zdavatz** [comment]
@apfeuti decide yourself! Oleg in Mattermost said, that Kanton of Zürich does have some computing resources they can offer.

**Comment by tlorusso** [comment]
Closing this for now - this repo aims at data collection only.
