### ISSUE TITLE
Read variables that are specific for a canton by scraper

### ISSUE THREAD

**Issue by jb3-2** [openZH/covid_19#796]
For [Basel-Stadt](https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_BS_total.csv) we have two special columns for people that are not residents of BS: ncumul_confirmed_non_resident, current_hosp_non_resident. Currently I calculate and add these numbers to the dataset manually. It would be a relief if the scraper could automagically add these two data points, too.

**Comment by metaodi** [comment]
With #814 the groundwork of scraping canton-specific variables has been laid.
