### ISSUE TITLE
Cases für Solothurn

### ISSUE THREAD

**Issue by schw4b** [openZH/covid_19#80]
Gibt es Daten ebenfalls für Solothurn, sonst wären ja alle Kanton da

Also,  COVID19_Fallzahlen_Kanton_SO_total.csv

**Comment by metaodi** [comment]
Von Solothurn fehlen aktuell offizielle Zahlen. Du kannst gerne mithelfen, diese Lücke zu schliessen.

**Comment by andristei** [comment]
Habe eine Email an den kantonalen Führungsstab von Solothurn betreffend Publizierung der Daten geschickt. Mal schauen ob sie Zeit haben darauf zu antworten

**Comment by zdavatz** [comment]
@andristei super Danke Dir!

**Comment by zdavatz** [comment]
> Habe eine Email an den kantonalen Führungsstab von Solothurn betreffend Publizierung der Daten geschickt. Mal schauen ob sie Zeit haben darauf zu antworten

Ich versuche es auch via Twitter: https://twitter.com/zdavatz/status/1241650896762699777?s=20

**Comment by schw4b** [comment]
Wunderbar, danke!

**Comment by baryluk** [comment]
We now have a scraper for Solothurn / SO.

Nice.
