### ISSUE TITLE
BS Scraper does not interpret current_isolated correctly

### ISSUE THREAD

**Issue by jb3-2** [openZH/covid_19#801]
BS publishes active cases _including_ people in hospital, whereas current_isolated should not contain people in hospital. Thus the scraper needs to substract people in hospital from the number of isolated. How to proceed on days when current_hosp are not communicated? I have no idea yet. 

See today's text from BS: https://www.gd.bs.ch//nm/2020-tagesbulletin-coronavirus-982-bestaetigte-faelle-im-kanton-basel-stadt-gd.html: 

"Die Zahl der 982 Infektionen setzt sich zusammen aus 924 genesenen Personen (-), 50 Todesfällen (-) und acht aktiven Fällen (+ 3). Von den aktiven Fällen befinden sich drei Personen in Spitalpflege. "

I have manually fixed today's numbers here: https://github.com/openZH/covid_19/commit/e6c3275b205a9be3a132974d11e50224fc7baf66

...but the scraper has overwritten my correction again here: https://github.com/openZH/covid_19/commit/8d7f8d1629868ec12350c55766f0ca588274ca2a 

So the scraper actively produces wrong numbers at the moment. Thanks for any help!

**Comment by metaodi** [comment]
@jb3-2 quick fix: we'll disable the scraper for BS until we have a bugfix. Ok?

**Comment by jb3-2** [comment]
OK thank you!

**Comment by dominikgehl** [comment]
#802

**Comment by metaodi** [comment]
Thanks @dominikgehl! After merging #802, I re-enabled the BS scraper.

**Comment by jb3-2** [comment]
Thank you @dominikgehl @metaodi!
