### ISSUE TITLE
GE is providing timeseries data as XLS

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#810]
Weppage: https://www.ge.ch/document/covid-19-situation-epidemiologique-geneve
- File-URL: https://www.ge.ch/document/20094/annexe/0
- File: 
[covid-19_ge_donnees_completes_0.xlsx](https://github.com/openZH/covid_19/files/4747263/covid-19_ge_donnees_completes_0.xlsx)

It is to be clarified, if file URL is stable, @simgraworldwide 

**Variables available from file:**
Date | 'date'
Cumul cas COVID-19 | 'ncumul_conf'
Nombre cas COVID-19 | -
Patients COVID-19 aux soins intermédiaires | 'ncumul_ICF'
Patients COVID-19 aux soins intensifs total | 'current_icu'
Patients COVID-19 aux soins intensifs intubés | 'current_vent'
Nb nouveaux patients COVID-19 admis aux soins intensifs | 
Patients COVID-19 hospitalisés en unité de soins | -
Total hospitalisations COVID-19 | 'current_hosp'
Nb nouveaux patients COVID-19 hospitalisés | 'new_hosp'
Cumul patients COVID-19 hospitalisés | -
Cumul COVID-19 sorties d'hospitalisation | 'ncumul_released'
Cumul décès COVID-19 | 'ncumul_deceased'
Nombre tests | ==> needs to be added to calculate 'ncumul_tested'

**Variables not available from file:**
'time'
'abbreviation_canton_and_fl'
'source'
'current_isolated'
'current_quarantined'

**Comment by andreasamsler** [comment]
Could you review the proposed mapping (Variable | 'variable') of the available variables, many thanks @simgraworldwide !

**Comment by metaodi** [comment]
On it.
