### ISSUE TITLE
ZH scraper distinguishes between case and contact tracing numbers

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#811]
Contact tracing numbers are updated every Tuesday and Thursday only.

Preferably the scraper is adapted, so that it is not adding the isolated and quarantined values to each daily record. Suggestion: Scrape those values only, if they differ from the values which were before?

**Comment by metaodi** [comment]
This imho a bad idea. Those numbers are communicated by ZH [on their website](https://gd.zh.ch/internet/gesundheitsdirektion/de/themen/coronavirus.html) along all the other numbers from the bulletin.

These kind of changes will lead to a lot of needed changes down the road:
- correction of data - the scraper can't determine if a value has been corrected or if the value actually changed (=new entry)
- the frequency of the update (Tuesday/Thursday) will likely change
- what if the numbers didn't change between Tuesday and Thursday?

If we really have to distinguish between those dates, this information must be provided from the source. E.g. AR provides two different dates ("Stand: DD.MM.YYYY") for the case numbers and the contact tracing numbers.

**Comment by amslera** [comment]
Thanks @metaodi, we need to advise GD-ZH KOM to mark the communicated contact tracing numbers on their webpage with a distinct timestamp, or specify at least its update frequency.

No action required regarding the ZH scraper.

**Comment by andreasamsler** [comment]
Clarified and obsolete.
