### ISSUE TITLE
Provide case numbers per district for GR

### ISSUE THREAD

**Issue by andreasamsler** [openZH/covid_19#831]
Suggestion received via e-mail:

"(..) Webseite des Kantons verweist hierzu auf eine neue Seite: https://ktgr.maps.arcgis.com/apps/opsdashboard/index.html#/3984041586964ec88a8e9f8e76529cd5 mit detaillierten aktualisierten Daten zu Fällen, Hospitalisierten, Regionen etc."

Analog der Datenstruktur, die wir mit unseren KollegInnen der Gesundheitsdirektion ZH für die Bereitstellung von Fallzahlen und Todesfällen auf Bezirksebene definiert haben (https://github.com/openZH/covid_19/blob/master/fallzahlen_bezirke/Readme.md), liesse sich via die ArcGIS-API vermutlich auch eine entsprechende CSV-Ressource für GR bereitstellen: https://github.com/openZH/covid_19/tree/master/fallzahlen_bezirke

WDYT? Is someone interested to try this?

**Comment by maekke** [comment]
Basically this [endpoint](https://services1.arcgis.com/YAuo6vcW85VPu7OE/arcgis/rest/services/Fallzahlen_Pro_Region/FeatureServer/0/query?f=json&where=Datum%3Dtimestamp%20%272020-07-19%2000%3A00%3A00%27&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Region%20asc&outSR=102100&resultOffset=0&resultRecordCount=26&resultType=standard&cacheHint=true) can be used for this.
Question is, how to integrate it in the current structure. I guess this would fit in fallzahlen_bezirke - but the ZH values are weekly, so I'm not sure if really fits there.

**Comment by metaodi** [comment]
The file is now here: https://github.com/openZH/covid_19/blob/master/fallzahlen_bezirke/fallzahlen_kanton_GR_bezirk.csv and is updated using a new GitHub Action workflow, which runs every hour.
