### ISSUE TITLE
Numbers of deceased in NE are missing though they are in their Excel

### ISSUE THREAD

**Issue by jonasoesch** [openZH/covid_19#832]
![image](https://user-images.githubusercontent.com/149315/84486623-f34d6500-ac9d-11ea-90a8-4f68d0814a40.png)

From the CSV at: https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_CH_total.csv

![image](https://user-images.githubusercontent.com/149315/84486718-0fe99d00-ac9e-11ea-8a2f-1927b62ae4ee.png)

From the Excel at: https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.xlsx

**Comment by dominikgehl** [comment]
parser script seems to work fine 
```
----------
NE
Scraped at: 2020-06-12T11:57:44.456770+02:00
Downloading: https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-St
atistiques/COVID19_PublicationInternet.xlsx
Date and time: 2020-05-31
Confirmed cases: 726
Hospitalized: 2
ICU: 0
Vent: 0
Deaths: 83
----------
NE
Scraped at: 2020-06-12T11:57:44.456792+02:00
Downloading: https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Documents/Covid-19-Statistiques/COVID19_PublicationInternet.xlsx
Date and time: 2020-06-01
Confirmed cases: 726
Hospitalized: 2
ICU: 0
Vent: 0
Deaths: 83
```

**Comment by metaodi** [comment]
@jonasoesch as you can see in the excel and our csv, the last value that was provided by NE for `ncumul_deceased` is from 2020-06-01, after that all values are empty.

**Comment by metaodi** [comment]
It looks like you're using pandas. Use something like `ffill` to fill the missing values from previous days (depending on what you want to do with the data)

**Comment by jonasoesch** [comment]
Yes, true. I missed that 👍 Thank you for the quick reply.
