### ISSUE TITLE
Complement data source of AG Scraper

### ISSUE THREAD

**Issue by amslera** [openZH/covid_19#846]
New source: https://www.ag.ch/de/themen_1/coronavirus_2/coronavirus.jsp

Instead of: Lagebulletin (PDF)

**Comment by amslera** [comment]
Maybe sth for you @fabian ?

**Comment by fabian** [comment]
Will look into it 👍

**Comment by amslera** [comment]
Lagebulletin (PDF) will be updated every Thursday.

Data in the new Source: daily 

It seems we will need to scrape both sources, to get updates of all variables, we have got from AG in the time series CSV in our repo.
