### ISSUE TITLE
Add current_isolated and current_quarantined to BL scraper

### ISSUE THREAD

**Issue by CorinneHuegli** [openZH/covid_19#847]
New iframe was added for BL with data for 'current_isolated' and 'current_quarantined'.

https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/covid-19-faelle-kanton-basel-landschaft

direct iframe-link: https://cocontrol.bl.ch/public/dbw/103

Could this be added to the BL-scaper?

Thanks!

**Comment by metaodi** [comment]
Related to #848

on it.
