### ISSUE TITLE
Geneva PDF file contains newer data than parsed xlsx

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#863]
https://www.ge.ch/document/covid-19-situation-epidemiologique-geneve links to both a PDF and an xlsx file. The PDF file seems to contain more up to date information. Do we want to parse both ?

**Comment by dominikgehl** [comment]
@andreasamsler Did you get any news from Geneva ? Should we start trying to parse the data from the PDF ?

**Comment by dominikgehl** [comment]
Latest PDF version is now https://www.ge.ch/document/20094/telecharger and contains data from today

**Comment by andreasamsler** [comment]
GE updated the XLS today; 'ncumul_deceased' is empty. We notified GE, and fix the missing values for the moment.
