### ISSUE TITLE
Some very high age-data in canton zurich

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19#869]
There are some very high age-data in Zurich ... are those true - especially the first one?
<img width="542" alt="image" src="https://user-images.githubusercontent.com/17248257/85919834-20d60900-b86f-11ea-9bb0-7947d2a12f6e.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/17248257/85919843-34816f80-b86f-11ea-9aaa-8b35def09454.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/17248257/85919866-52e76b00-b86f-11ea-8073-f57a9c7000e9.png">

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Fallzahlen_Kanton_ZH_alter_geschlecht.csv

**Comment by andreasamsler** [comment]
Thanks, @rsalzer, we're forwarding to our colleagues @GD-ZH for clarification.
Best, Andreas

**Comment by GD-ZH** [comment]
Thank you for the comment. We have checked the lab reports: The 120 years is an error, indeed, which we will correct. The other two age indications are correct according to the reports.

**Comment by andreasamsler** [comment]
Resolved.
