### ISSUE TITLE
New datasource for BS

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#875]
https://data.bs.ch/explore/dataset/100073/table/?sort=timestamp

as mentioned here https://www.gd.bs.ch/nm/2020-coronavirus-unveraenderte-fallzahlen-im-kanton-basel-stadt--tagesbulletin-wird-zum-wochenbulletin-gd.html

**Comment by metaodi** [comment]
See https://github.com/openZH/covid_19/pull/876#issuecomment-652252619
