### ISSUE TITLE
VS - website contains weekly time series data as xlsx file

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#882]
https://www.vs.ch/de/web/coronavirus/statistiques contains newer data in PDF files than the xlsx file.

**Comment by simgraworldwide** [comment]
Thanks. We are currently trying to further improve the situation concerning VS.

**Comment by andreasamsler** [comment]
https://www.vs.ch/de/web/coronavirus/statistiques?p_p_id=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_o4Vpi3Gczo3r&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_o4Vpi3Gczo3r_delta=30&p_r_p_resetCur=false&_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_o4Vpi3Gczo3r_cur=2 contains weekly time series data called "Wochenstatistiken" as XLSX.

As long as VS is not providing daily updates, we could adapt the scraper to consume the weekly XLSX.

**Comment by andreasamsler** [comment]
We at https://github.com/statistikZH are receiving structured data updates from VS more frequently than VS is publishing those on its website.

We keep the scraper as is for now, i.e. it is consuming the data update which we are dropping to https://github.com/statistikZH/covid19_drop

I am therfore closing this issue, thanks!
