### ISSUE TITLE
Bug in TI xlsx file ?

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#892]
https://www4.ti.ch/fileadmin/DSS/DSP/UMC/malattie_infettive/Coronavirus/dati/COVID19_Dati_TI_per_github.xlsx
shows today 3555 cases (yesterday: 3351). Should this be 3355 instead ?

**Comment by dominikgehl** [comment]
Looks like the file has been fixed !

**Comment by andreasamsler** [comment]
https://twitter.com/OpenDataZH/status/1280441586824941568?s=20
