### ISSUE TITLE
Integrate BAG data of tests

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#909]
With PR #908 we got a scraper the BAG data of the performed tests. At this point I'm not sure how/if we could integrate this data in this repo. Or if we just provide the scraper, and let others use it (?)

**Comment by andreasamsler** [comment]
I am in favor of sticking to the principle to only integrate data in our repo, which is being communicated by Cantons & FL.

Just providing the scraper is not in conflict with this principle imho. The question however is, if the scraper is being found.

**Comment by maekke** [comment]
I've created a BAG data repo just for fun that only contains the number of performed tests and number of isolated/quarantined people. In case someone is interested: https://github.com/maekke/bag_data

**Comment by jb3-2** [comment]
Great work, thank you very much! We'll be discussing whether we'll use the number of tests in total received by BAG in our BS dataset and get back to you all soon.

**Comment by jb3-2** [comment]
We will add the BAG numbers for ncumul_tested to the dataset of Basel-Stadt. @maekke Do you know if the number of tests per canton means (a) the number of tests by laboratories in a specific Canton, or (b) the number of tests of people living in a certain Canton? I‘d guess it is (a), but I cannot find an official definition by BAG. Do you have an answer to that? Thanks again for your work, greatly appreciated!

**Comment by metaodi** [comment]
The test data of the cantons is now part of this repository: https://github.com/openZH/covid_19/tree/master/fallzahlen_tests
