### ISSUE TITLE
Wrong data published by Kanton Luzern

### ISSUE THREAD

**Issue by deragent** [openZH/covid_19#921]
Kanton Luzern today published (most likely) wrong numbers with a totel number of positive tests of ca. 80'000.

This was (probably) automatically scrapped into the database here.

![Screen](https://user-images.githubusercontent.com/1924085/88045419-c74fba00-cb4e-11ea-8b0a-e37ad3f86118.png)

![Screen](https://user-images.githubusercontent.com/1924085/88045450-d59dd600-cb4e-11ea-91cd-ee8fca116e14.png)

**Comment by dominikgehl** [comment]
Yes, I just checked too. The data is scraped as it appears on the website

**Comment by tlorusso** [comment]
fixed.
