### ISSUE TITLE
Provide a moving average on the 7, 14 and 21 last days

### ISSUE THREAD

**Issue by Arduous** [openZH/covid_19#922]
Hello,

It would be interesting to indicate for each canton the average value for the past 7, 14 and 21 days prior to the last available data point.
It would give a more accurate sense of the current circulation of the virus rather than the total value which is heavily impacted by the peaks in March.
It may be even more interesting to normalize by the size of the population, ie 5 new cases every day in the last 7 days per 10'000 people.

Cheers

**Comment by andreasamsler** [comment]
Hi there

We are providing the date from te respective sources only.

Best regards
Andreas

**Comment by andreasamsler** [comment]
Hi there

We are providing the date from te respective sources only.

Best regards
Andreas

**Comment by amslera** [comment]
Sorry for the typos
