### ISSUE TITLE
Quarantined differences between AR and AI

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#931]
AR and AI parsers don't return the same "definition" of quarantined

Website contents:
AR:
Aktuell im Kanton wohnhafte Kontaktpersonen in Quarantäne: 41
- davon Anzahl Personen, die aus einem Risikogebiet in die Schweiz eingereist sind und aufgrund dessen aktuell im Kanton in Quarantäne sind:  37

AI
0 Personen in Quarantäne/enger Kontakt (aktuell)
12 Personen in Quarantäne/Einreise Risikoland (aktuell)

AR parser returns 41 for quarantined, AI parser returns 0, i.e. AR parser includes "Einreise Quarantäne" while AI doesn't.

**Comment by metaodi** [comment]
We had similar issues for BS and ZG, where we introduced new (canton-specific) variables for this: `current_quarantined_riskarea_travel` and `current_quarantined_total`.

I guess these new variables will become relevant for most cantons. The variable `current_quaratined` is supposed to be only the "close contact" and the contact tracing based quarantine.

**Comment by dominikgehl** [comment]
> We had similar issues for BS and ZG, where we introduced new (canton-specific) variables for this: `current_quarantined_riskarea_travel` and `current_quarantined_total`.
> 
> I guess these new variables will become relevant for most cantons. The variable `current_quaratined` is supposed to be only the "close contact" and the contact tracing based quarantine.

Ok. I'll update the AR parser accordingly.
