### ISSUE TITLE
Bring back old Design!

### ISSUE THREAD

**Issue by boogaloo7** [openZH/covid_19#944]
The new Design totally Sucks!

is the new UI developer Colorblinde?

there is also Data Missing which did show up under the old Design (specially International Data.)

So please Bring back the old Design, which was hosted under KickstStart.ch!!

Or at least offer a Switch to switch to the old Design.! (sorry to say, but the new design is just a fail.)

**Comment by metaodi** [comment]
Hi @boogaloo7

I'm not sure what design you mean. This repository contains mostly COVID-19 case data of the Swiss cantons. So it's main content is CSVs files. If you could specify what design on what page you mean, this would help a lot. Additionally I'm not sure what kind of data is missing, since this repository does not contain international data. Was this issue maybe intended for another repository?

Thanks in advance.

**Comment by boogaloo7** [comment]
its about "https://www.corona-data.ch/", earlier reachable via "kickstart.ch"
As this Account was linked on this side, i thouth this is may the right place to adress this.

As it looks, i may was wrong, if so, sry for the hassle.

reg.

**Comment by metaodi** [comment]
corona-data.ch uses the data from this repository, but it's a different project. Maybe @daenuprobst can point you to the correct place to report issues for his website.

I'm closing this issue here.

**Comment by boogaloo7** [comment]
Thanks

**Comment by daenuprobst** [comment]
>The new Design totally Sucks!
>
>is the new UI developer Colorblinde?

corona-data.ch was never available under kickstart.ch. For corona-data.ch, the latest design change was done 2 or 3 months ago...

But just as a hint, with this tone of voice, they won't listen to you and I am surprised you did get an answer here.

**Comment by boogaloo7** [comment]
> corona-data.ch was never available under kickstart.ch
if this wasnt the case it is now: [https://kickstart.ch/interaktive-coronavirus-karte](https://kickstart.ch/interaktive-coronavirus-karte)  

> But just as a hint, with this tone of voice, don't expect them to listen ;-)
Is it smart to act like this? may not, but honest.
Wondering how anybody would act, if one get a gift, and lator someone thake it away. 
Guess a UI developer knews, that if someone act emotional, that it means that thers was/is a value for what is in question.

reg.
