### ISSUE TITLE
Terminology clarification

### ISSUE THREAD

**Issue by filippo82** [openZH/covid_19#96]
Dear all,

thanks a lot for keeping this repo up-to-date! There seems to be some confusion regarding the terminology: the infection rates refer to the infection with SARS-Cov-2, whereas the disease caused by the virus is called Covid-19.

Best wishes,
-Filippo

**Comment by metaodi** [comment]
@filippo82 Could you please create a pull request with your suggestions where exactly the terminology should be changed? Thank you in advance!

**Comment by filippo82** [comment]
Will do thanks! I need to engage my better half, she is the real doctor :)

**Comment by filippo82** [comment]
Done.
