### ISSUE TITLE
FL: PDF URL not found

### ISSUE THREAD

**Issue by dominikgehl** [openZH/covid_19#967]
Latest data I could find was linked from https://hebensorg.li/
Do we want to parse this source ? Do we have a better source of data ?

**Comment by metaodi** [comment]
But https://www.llv.li/files/ag/aktuelle-fallzahlen.pdf seems to have current data. Maybe it was updated just now (?)

**Comment by dominikgehl** [comment]
Scraper still returns empty though. Looking into it.

**Comment by dominikgehl** [comment]
The PDF now contains two additional columns (recovered and deaths). scraper is updated.
