### ISSUE TITLE
Comparison data sources: openzh vs daenuprobst

### ISSUE THREAD

**Issue by cybermax** [openZH/covid_19#97]
By automatically generating summary tables of the data provided by openzh and daenuprobst, we have found incosistencies between the two datasets.

openzh:
https://github.com/zdavatz/covid19_ch/blob/master/python-scripts/output_openzh/dd-covid19-ch-openzh-cantons-latest.csv

daenuprobst:
https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv

Is there a way to align the two datasets?

All the best, Max

**Comment by zdavatz** [comment]
Also: Who is right?

**Comment by jb3-2** [comment]
@cybermax Can you maybe somehow highlight the differences so we / I can invest some time into researching what's wrong and what's right?

**Comment by zdavatz** [comment]
This can be closed. We only use OpenZH data now.
