### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by cybermax** [openZH/covid_19#98]
I think it would make sense to express date and time according to the ISO 8601:
https://en.wikipedia.org/wiki/ISO_8601

i.e. one single column (datetime) and not two separate columns (date + time).

**Comment by metaodi** [comment]
@cybermax we discussed this. Our reason to keep it separate is to be able to omit it. Most cantons do not provide the time. If we have everything in one column, we would have to use a default like "00:00" which suggest an accuracy we do not have.

**Comment by tlorusso** [comment]
@cybermax for the reason @metaodi just mentioned, we have to stick to this. If at some point we will be able to get a timestamp for all, then we can reconsider changing it. Closing this issue for now.

**Comment by baryluk** [comment]
Yes, I agree here with @metaodi, not all sources provide time information, and setting it to 00:00 is not a correct thing to do. For now we need to keep date and time separate, with time possibly being empty. So we can't use ISO-8601 fully, but date and time parts conform to ISO-8601.

Resolved.
