### ISSUE TITLE
Data by post code

### ISSUE THREAD

**Issue by Atitlan** [openZH/covid_19#988]
The 0-3 category blurs a lot ... could this be split into 0 vs 1-3?

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by andreasamsler** [comment]
Hi there

In case you're referring to https://github.com/openZH/covid_19/blob/master/fallzahlen_plz/Readme.md, our respective data steward - i.e. Department of Health Canton of Zurich - chose to apply these categories for data protection reasons.

Best, Andreas

**Comment by Atitlan** [comment]
Herzlichen Dank für die rasche Rückmeldung.
Ich halbwegs verstehen, warum man bei kleinräumigen Aufteilungen ‚ranges‘ verwendet.
Allerdings kann ich nicht nachvollziehen, wie das separate Ausweisen von ‚Null‘ ein Problem mit dem Datenschutz kreieren sollte.
Beste Grüsse

**********************
